-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.Fors.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace sphincs_c10

/-- [sphincs_c10::fors::read_bits_le]: loop body 0:
    Source: 'sphincs-c10/src/fors.rs', lines 26:4-31:5 -/
@[rust_loop_body]
def fors.read_bits_le_loop.body
  (digest : Array Std.U8 32#usize) (byte_start : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (val : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.U64) Std.U64)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done val)
  | some b =>
    let idx ← lift (core.num.Usize.wrapping_sub byte_start b)
    if idx < 32#usize
    then
      let i ← Array.index_usize digest idx
      let i1 ← lift (core.convert.num.FromU64U8.from i)
      let i2 ← b * 8#usize
      let i3 ← i1 <<< i2
      let val1 ← lift (val ||| i3)
      ok (cont (iter1, val1))
    else ok (cont (iter1, val))

/-- [sphincs_c10::fors::read_bits_le]: loop 0:
    Source: 'sphincs-c10/src/fors.rs', lines 26:4-31:5 -/
@[rust_loop]
def fors.read_bits_le_loop
  (iter : core.ops.range.Range Std.Usize) (digest : Array Std.U8 32#usize)
  (byte_start : Std.Usize) (val : Std.U64) :
  Result Std.U64
  := do
  loop
    (fun (iter1, val1) => fors.read_bits_le_loop.body digest byte_start iter1
      val1)
    (iter, val)

/-- [sphincs_c10::fors::read_bits_le]:
    Source: 'sphincs-c10/src/fors.rs', lines 19:0-34:1 -/
def fors.read_bits_le
  (digest : Array Std.U8 32#usize) (bit_offset : Std.Usize)
  (num_bits : Std.Usize) :
  Result Std.U64
  := do
  massert (num_bits > 0#usize)
  massert (num_bits <= 57#usize)
  let i ← bit_offset / 8#usize
  let byte_start ← 31#usize - i
  let bit_in_byte ← bit_offset % 8#usize
  let i1 ← num_bits + bit_in_byte
  let i2 ← i1 + 7#usize
  let bytes_needed ← i2 / 8#usize
  let val ←
    fors.read_bits_le_loop { start := 0#usize, «end» := bytes_needed } digest
      byte_start 0#u64
  let i3 ← 1#u64 <<< num_bits
  let mask ← i3 - 1#u64
  let i4 ← val >>> bit_in_byte
  ok (i4 &&& mask)

/-- [sphincs_c10::params::A]
    Source: 'sphincs-c10/src/params.rs', lines 37:0-37:24
    Visibility: public -/
@[global_simps, irreducible] def params.A : Std.Usize := 11#usize

/-- [sphincs_c10::params::K]
    Source: 'sphincs-c10/src/params.rs', lines 34:0-34:24
    Visibility: public -/
@[global_simps, irreducible] def params.K : Std.Usize := 13#usize

/-- [sphincs_c10::fors::extract_fors_indices]: loop body 0:
    Source: 'sphincs-c10/src/fors.rs', lines 44:4-46:5
    Visibility: public -/
@[rust_loop_body]
def fors.extract_fors_indices_loop.body
  (digest : Array Std.U8 32#usize) (iter : core.ops.range.Range Std.Usize)
  (indices : Array Std.U32 13#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U32
    13#usize)) (Array Std.U32 13#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done indices)
  | some i =>
    let i1 ← i * params.A
    let i2 ← fors.read_bits_le digest i1 params.A
    let i3 ← lift (UScalar.cast .U32 i2)
    let a ← Array.update indices i i3
    ok (cont (iter1, a))

/-- [sphincs_c10::fors::extract_fors_indices]: loop 0:
    Source: 'sphincs-c10/src/fors.rs', lines 44:4-46:5
    Visibility: public -/
@[rust_loop]
def fors.extract_fors_indices_loop
  (iter : core.ops.range.Range Std.Usize) (digest : Array Std.U8 32#usize)
  (indices : Array Std.U32 13#usize) :
  Result (Array Std.U32 13#usize)
  := do
  loop
    (fun (iter1, indices1) => fors.extract_fors_indices_loop.body digest iter1
      indices1)
    (iter, indices)

/-- [sphincs_c10::fors::extract_fors_indices]:
    Source: 'sphincs-c10/src/fors.rs', lines 42:0-48:1
    Visibility: public -/
def fors.extract_fors_indices
  (digest : Array Std.U8 32#usize) : Result (Array Std.U32 13#usize) := do
  let indices := Array.repeat 13#usize 0#u32
  fors.extract_fors_indices_loop { start := 0#usize, «end» := params.K }
    digest indices

/-- [sphincs_c10::params::H]
    Source: 'sphincs-c10/src/params.rs', lines 22:0-22:24
    Visibility: public -/
@[global_simps, irreducible] def params.H : Std.Usize := 18#usize

/-- [sphincs_c10::fors::extract_ht_index]:
    Source: 'sphincs-c10/src/fors.rs', lines 58:0-60:1
    Visibility: public -/
def fors.extract_ht_index
  (digest : Array Std.U8 32#usize) : Result Std.U32 := do
  let i ← params.K * params.A
  let i1 ← fors.read_bits_le digest i params.H
  ok (UScalar.cast .U32 i1)

end sphincs_c10
