-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_aa]: function definitions
import Aeneas
import Extracted.Eip1271.Types
import Extracted.Eip1271.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pqsigner_aa

/-- [pqsigner_aa::eip1271::PERSONAL_SIGN_TYPEHASH]
    Source: 'aa/src/eip1271.rs', lines 32:0-37:2
    Visibility: public -/
@[global_simps, irreducible]
def eip1271.PERSONAL_SIGN_TYPEHASH : Array Std.U8 32#usize :=
  Array.make 32#usize [
    152#u8, 62#u8, 101#u8, 229#u8, 20#u8, 142#u8, 87#u8, 12#u8, 216#u8, 40#u8,
    234#u8, 210#u8, 49#u8, 238#u8, 117#u8, 154#u8, 141#u8, 121#u8, 88#u8,
    114#u8, 26#u8, 118#u8, 143#u8, 147#u8, 188#u8, 68#u8, 131#u8, 186#u8, 0#u8,
    92#u8, 50#u8, 222#u8
    ]

/-- [pqsigner_aa::eip1271::EIP712_DOMAIN_TYPEHASH]
    Source: 'aa/src/eip1271.rs', lines 42:0-47:2
    Visibility: public -/
@[global_simps, irreducible]
def eip1271.EIP712_DOMAIN_TYPEHASH : Array Std.U8 32#usize :=
  Array.make 32#usize [
    139#u8, 115#u8, 195#u8, 198#u8, 155#u8, 184#u8, 254#u8, 61#u8, 81#u8,
    46#u8, 204#u8, 76#u8, 247#u8, 89#u8, 204#u8, 121#u8, 35#u8, 159#u8, 123#u8,
    23#u8, 155#u8, 15#u8, 250#u8, 202#u8, 169#u8, 167#u8, 93#u8, 82#u8, 43#u8,
    57#u8, 64#u8, 15#u8
    ]

/-- [pqsigner_aa::eip1271::NAME_HASH]
    Source: 'aa/src/eip1271.rs', lines 51:0-56:2
    Visibility: public -/
@[global_simps, irreducible]
def eip1271.NAME_HASH : Array Std.U8 32#usize :=
  Array.make 32#usize [
    56#u8, 95#u8, 142#u8, 6#u8, 247#u8, 77#u8, 71#u8, 147#u8, 45#u8, 224#u8,
    111#u8, 183#u8, 101#u8, 12#u8, 130#u8, 117#u8, 28#u8, 239#u8, 5#u8, 172#u8,
    246#u8, 193#u8, 231#u8, 181#u8, 13#u8, 159#u8, 130#u8, 6#u8, 132#u8, 13#u8,
    247#u8, 47#u8
    ]

/-- [pqsigner_aa::eip1271::VERSION_HASH]
    Source: 'aa/src/eip1271.rs', lines 60:0-65:2
    Visibility: public -/
@[global_simps, irreducible]
def eip1271.VERSION_HASH : Array Std.U8 32#usize :=
  Array.make 32#usize [
    200#u8, 158#u8, 253#u8, 170#u8, 84#u8, 192#u8, 242#u8, 12#u8, 122#u8,
    223#u8, 97#u8, 40#u8, 130#u8, 223#u8, 9#u8, 80#u8, 245#u8, 169#u8, 81#u8,
    99#u8, 126#u8, 3#u8, 7#u8, 205#u8, 203#u8, 76#u8, 103#u8, 47#u8, 41#u8,
    139#u8, 139#u8, 198#u8
    ]

/-- [pqsigner_aa::eip1271::domain_separator]:
    Source: 'aa/src/eip1271.rs', lines 101:0-116:1
    Visibility: public -/
def eip1271.domain_separator
  (chain_id : Std.U64) (verifying_contract : Array Std.U8 20#usize) :
  Result (Array Std.U8 32#usize)
  := do
  let buf := Array.repeat 160#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) buf
      { «end» := 32#usize }
  let s1 ← lift (Array.to_slice eip1271.EIP712_DOMAIN_TYPEHASH)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
      { start := 32#usize, «end» := 64#usize }
  let s4 ← lift (Array.to_slice eip1271.NAME_HASH)
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let buf2 := index_mut_back1 s5
  let (s6, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf2
      { start := 64#usize, «end» := 96#usize }
  let s7 ← lift (Array.to_slice eip1271.VERSION_HASH)
  let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
  let buf3 := index_mut_back2 s8
  let i ← 96#usize + 24#usize
  let (s9, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf3
      { start := i, «end» := 128#usize }
  let a ← lift (core.num.U64.to_be_bytes chain_id)
  let s10 ← lift (Array.to_slice a)
  let s11 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s9 s10
  let buf4 := index_mut_back3 s11
  let i1 ← 128#usize + 12#usize
  let (s12, index_mut_back4) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf4
      { start := i1, «end» := 160#usize }
  let s13 ← lift (Array.to_slice verifying_contract)
  let s14 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s12 s13
  let buf5 := index_mut_back4 s14
  let s15 ← lift (Array.to_slice buf5)
  pqsigner_tx_core.hash.keccak256 s15

/-- [pqsigner_aa::eip1271::replay_safe_hash]:
    Source: 'aa/src/eip1271.rs', lines 163:0-181:1
    Visibility: public -/
def eip1271.replay_safe_hash
  (chain_id : Std.U64) (verifying_contract : Array Std.U8 20#usize)
  (final_hash : Array Std.U8 32#usize) :
  Result (Array Std.U8 32#usize)
  := do
  let sbuf := Array.repeat 64#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) sbuf
      { «end» := 32#usize }
  let s1 ← lift (Array.to_slice eip1271.PERSONAL_SIGN_TYPEHASH)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let sbuf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sbuf1
      { start := 32#usize, «end» := 64#usize }
  let s4 ← lift (Array.to_slice final_hash)
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let sbuf2 := index_mut_back1 s5
  let s6 ← lift (Array.to_slice sbuf2)
  let struct_hash ← pqsigner_tx_core.hash.keccak256 s6
  let domain_sep ← eip1271.domain_separator chain_id verifying_contract
  let fbuf := Array.repeat 66#usize 0#u8
  let (s7, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) fbuf
      { «end» := 2#usize }
  let s8 ← lift (Array.to_slice (Array.make 2#usize [ 25#u8, 1#u8 ]))
  let s9 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s7 s8
  let fbuf1 := index_mut_back2 s9
  let (s10, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) fbuf1
      { start := 2#usize, «end» := 34#usize }
  let s11 ← lift (Array.to_slice domain_sep)
  let s12 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s10 s11
  let fbuf2 := index_mut_back3 s12
  let (s13, index_mut_back4) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) fbuf2
      { start := 34#usize, «end» := 66#usize }
  let s14 ← lift (Array.to_slice struct_hash)
  let s15 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s13 s14
  let fbuf3 := index_mut_back4 s15
  let s16 ← lift (Array.to_slice fbuf3)
  pqsigner_tx_core.hash.keccak256 s16

end pqsigner_aa
