-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_aa]: function definitions
import Aeneas
import Extracted.UserOp.Types
import Extracted.UserOp.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pqsigner_aa

/-- [pqsigner_aa::userop::WORD]
    Source: 'aa/src/userop.rs', lines 68:0-68:23 -/
@[global_simps, irreducible] def userop.WORD : Std.Usize := 32#usize

/-- [pqsigner_aa::userop::write_u64_in_word_be]:
    Source: 'aa/src/userop.rs', lines 77:0-80:1 -/
def userop.write_u64_in_word_be
  (word : Slice Std.U8) (v : Std.U64) : Result (Slice Std.U8) := do
  let left_val := Slice.len word
  massert (left_val = userop.WORD)
  let i ← userop.WORD - 8#usize
  let (s, index_mut_back) ←
    core.slice.index.Slice.index_mut
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) word
      { start := i, «end» := userop.WORD }
  let a ← lift (core.num.U64.to_be_bytes v)
  let s1 ← lift (Array.to_slice a)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (index_mut_back s2)

/-- [pqsigner_aa::userop::write_word_right_aligned]:
    Source: 'aa/src/userop.rs', lines 695:0-699:1 -/
def userop.write_word_right_aligned
  (buf : Array Std.U8 320#usize) (i : Std.Usize) (row : Slice Std.U8) :
  Result (Array Std.U8 320#usize)
  := do
  let i1 := Slice.len row
  massert (i1 <= userop.WORD)
  let i2 ← i + 1#usize
  let slot_end ← i2 * userop.WORD
  let i3 := Slice.len row
  let i4 ← slot_end - i3
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
      { start := i4, «end» := slot_end }
  let s1 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s row
  ok (index_mut_back s1)

/-- [pqsigner_aa::userop::compute_user_op_hash]:
    Source: 'aa/src/userop.rs', lines 702:0-733:1
    Visibility: public -/
def userop.compute_user_op_hash
  (params : userop.AaUserOpParams) (call_data_hash : Array Std.U8 32#usize) :
  Result (Array Std.U8 32#usize)
  := do
  let buf := Array.repeat 320#usize 0#u8
  let s ← lift (Array.to_slice params.sender)
  let buf1 ← userop.write_word_right_aligned buf 0#usize s
  let a := params.nonce
  let s1 ← lift (Array.to_slice a)
  let buf2 ← userop.write_word_right_aligned buf1 1#usize s1
  let s2 ← lift (Array.to_slice params.init_code_hash)
  let buf3 ← userop.write_word_right_aligned buf2 2#usize s2
  let s3 ← lift (Array.to_slice call_data_hash)
  let buf4 ← userop.write_word_right_aligned buf3 3#usize s3
  let a1 := params.call_gas_limit
  let s4 ← lift (Array.to_slice a1)
  let buf5 ← userop.write_word_right_aligned buf4 4#usize s4
  let a2 := params.verification_gas_limit
  let s5 ← lift (Array.to_slice a2)
  let buf6 ← userop.write_word_right_aligned buf5 5#usize s5
  let a3 := params.pre_verification_gas
  let s6 ← lift (Array.to_slice a3)
  let buf7 ← userop.write_word_right_aligned buf6 6#usize s6
  let a4 := params.max_fee_per_gas
  let s7 ← lift (Array.to_slice a4)
  let buf8 ← userop.write_word_right_aligned buf7 7#usize s7
  let a5 := params.max_priority_fee_per_gas
  let s8 ← lift (Array.to_slice a5)
  let buf9 ← userop.write_word_right_aligned buf8 8#usize s8
  let s9 ← lift (Array.to_slice params.paymaster_and_data_hash)
  let buf10 ← userop.write_word_right_aligned buf9 9#usize s9
  let s10 ← lift (Array.to_slice buf10)
  let inner ← pqsigner_tx_core.hash.keccak256 s10
  let outer := Array.repeat 96#usize 0#u8
  let (s11, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) outer
      { start := 0#usize, «end» := userop.WORD }
  let s12 ← lift (Array.to_slice inner)
  let s13 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s11 s12
  let outer1 := index_mut_back s13
  let i ← userop.WORD - 20#usize
  let i1 ← userop.WORD + i
  let i2 ← 2#usize * userop.WORD
  let (s14, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) outer1
      { start := i1, «end» := i2 }
  let s15 ← lift (Array.to_slice params.entry_point)
  let s16 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s14 s15
  let outer2 := index_mut_back1 s16
  let i3 ← 3#usize * userop.WORD
  let (s17, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) outer2
      { start := i2, «end» := i3 }
  let s18 ← userop.write_u64_in_word_be s17 params.chain_id
  let outer3 := index_mut_back2 s18
  let s19 ← lift (Array.to_slice outer3)
  pqsigner_tx_core.hash.keccak256 s19

end pqsigner_aa
