-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_aa]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pqsigner_aa

/-- [pqsigner_tx_core::eip1559::U256]
    Source: 'tx-core/src/eip1559.rs', lines 71:0-71:15
    Name pattern: [pqsigner_tx_core::eip1559::U256]
    Visibility: public -/
@[reducible, rust_type "pqsigner_tx_core::eip1559::U256"]
def pqsigner_tx_core.eip1559.U256 := Array Std.U8 32#usize

/-- [pqsigner_aa::userop::AaUserOpParams]
    Source: 'aa/src/userop.rs', lines 460:0-472:1
    Visibility: public -/
structure userop.AaUserOpParams where
  sender : Array Std.U8 20#usize
  entry_point : Array Std.U8 20#usize
  chain_id : Std.U64
  nonce : pqsigner_tx_core.eip1559.U256
  call_gas_limit : pqsigner_tx_core.eip1559.U256
  verification_gas_limit : pqsigner_tx_core.eip1559.U256
  pre_verification_gas : pqsigner_tx_core.eip1559.U256
  max_fee_per_gas : pqsigner_tx_core.eip1559.U256
  max_priority_fee_per_gas : pqsigner_tx_core.eip1559.U256
  init_code_hash : Array Std.U8 32#usize
  paymaster_and_data_hash : Array Std.U8 32#usize

end pqsigner_aa
