//! Minimal `no_std` BIP-39 implementation tailored to a hardware wallet.
//!
//! Two layers, separated by Cargo feature:
//!
//! * **Always-available** (no_default-features build) — the surface the
//!   FSBL needs to render the 8-BIP-39-word firmware fingerprint on the
//!   NV3007 LCD:
//!   - [`WORDLIST_PREFIX5_PACKED`] (6 KB base-27-packed prefix table,
//!     generated by `build.rs` from `src/wordlist.rs`)
//!   - [`word_prefix_at`] (constant-time index → 5-byte prefix scan + decode)
//!   - [`hash_to_word_indices`] (88-bit hash slice → 8 × 11-bit indices)
//!   - bit packing helpers + constants
//!
//! * **`full-wordlist` feature** (default-on for secure-world, off for
//!   FSBL) — the full Mnemonic codec, the constant-time `WORDLIST_FLAT` /
//!   `WORDLIST_LENS` tables, prefix / exact lookups, and PBKDF2 seed
//!   derivation. Lives in [`full`] and is re-exported at the crate root
//!   so the historical public paths (`sphincs_tz_bip39::Mnemonic`,
//!   `sphincs_tz_bip39::WORDLIST`, etc.) continue to work for callers
//!   that opt into the feature.
//!
//! Supports 24-word English mnemonics only — that is the entire surface
//! the SPHINCS+ wallet needs. The wordlist is statically compiled into
//! flash, no heap allocation is used anywhere, and the [`full::Mnemonic`]
//! type wipes its word indices on drop.
//!
//! This crate intentionally does **not** depend on the upstream `bip39`
//! crate. Avoiding `bitcoin_hashes` and the surrounding dependency tree
//! keeps the secure-world TCB tiny and lets us audit every line.

#![cfg_attr(not(test), no_std)]
#![forbid(unsafe_code)]

// `mod wordlist;` is gated because the FSBL build doesn't want the ~16 KB
// of raw word strings in its binary. Internal access from the `full`
// module is `crate::wordlist::WORDLIST` and is itself gated.
#[cfg(feature = "full-wordlist")]
pub mod wordlist;

#[cfg(feature = "full-wordlist")]
mod full;
#[cfg(feature = "full-wordlist")]
pub use full::*;

/// Number of words in the mnemonic (this crate is 24-words only).
pub const WORD_COUNT: usize = 24;

/// Raw entropy length: 256 bits.
pub const ENTROPY_BYTES: usize = 32;

/// Length of the BIP-39 seed produced by `Mnemonic::to_seed`
/// (only available with the `full-wordlist` feature).
pub const SEED_BYTES: usize = 64;

/// Number of bits per BIP-39 word index.
const BITS_PER_WORD: usize = 11;

/// Maximum byte length of any English BIP-39 word.
///
/// The longest words ("abandon", "absurd", "ability", ..., "wrestle") max
/// out at 8 bytes; this is used as the fixed stride for the constant-time
/// flat wordlist (`WORDLIST_FLAT` / `WORDLIST_LENS`). Per-word lengths are
/// in [3, 8].
pub const MAX_WORD_BYTES: usize = 8;

// ---------------------------------------------------------------------------
// Compact prefix-5 wordlist (always available — used by FSBL + measured_boot)
// ---------------------------------------------------------------------------

// Generated at build time by `build.rs` from `src/wordlist.rs`. The output
// is a single `pub static WORDLIST_PREFIX5_PACKED: [[u8; 3]; 2048]`
// declaration (base-27-packed 5-char prefixes; see `word_prefix_at`).
// Generated literally (not via `const fn` over `WORDLIST`) so it works in
// the `no_default-features` build where `WORDLIST` is absent.
include!(concat!(env!("OUT_DIR"), "/wordlist_prefix5.rs"));

/// Constant-time `target == entry` comparison for u16 — returns `0xFF`
/// iff equal, `0x00` otherwise, with no secret-dependent branches.
///
/// Duplicated here (the `full` module has its own copy) because the
/// always-available [`word_prefix_at`] needs it too and we don't want
/// to bring the rest of `full`'s helpers into the no_default build.
#[inline(always)]
fn ct_eq_u16_min(a: u16, b: u16) -> u8 {
    let x: u32 = a as u32 ^ b as u32;
    let nz: u32 = (x | x.wrapping_neg()) >> 31; // 0 iff eq, 1 iff diff
    (nz as u8).wrapping_sub(1) // 0xFF iff eq, 0x00 iff diff
}

/// Constant-time 5-byte prefix lookup by index.
///
/// Scans all 2048 entries of [`WORDLIST_PREFIX5_PACKED`] and mask-ORs the
/// 3-byte base-27 code whose index matches `idx`, then decodes that code
/// back to the exact 5-byte prefix. The displayed measurement words are
/// public (they derive from the firmware hash, which anyone can recompute
/// from the source), but routing the *table read* through this constant-time
/// scan instead of `WORDLIST_PREFIX5_PACKED[idx]` keeps the same access
/// pattern as `full::word_bytes_at`, so the leaky address-keyed-load shape
/// doesn't exist in the codebase for a future caller to inherit. The base-27
/// decode is branch-free and runs only on the already-selected public code,
/// so it adds no data-dependent access shape.
///
/// `idx >= 2048` never matches, so the code stays zero and every symbol
/// decodes to the padding byte `0x00` — an all-zero prefix (blanks).
///
/// Cost: 2048 × 3 = 6 KB stack reads plus a 5-step base-27 decode ≈ a few
/// ms on Cortex-M33 — well under the FSBL's overall boot budget.
#[must_use]
pub fn word_prefix_at(idx: u16) -> [u8; 5] {
    use core::hint::black_box;
    // Constant-time select of the packed 3-byte code for `idx`.
    let mut code_bytes = [0u8; 3];
    let mut entry_idx: u16 = 0;
    while entry_idx < 2048 {
        let entry_idx_obf = black_box(entry_idx);
        let entry = &WORDLIST_PREFIX5_PACKED[entry_idx_obf as usize];
        let mask = black_box(ct_eq_u16_min(entry_idx_obf, idx));
        let mut b = 0;
        while b < 3 {
            code_bytes[b] = black_box(code_bytes[b] | (entry[b] & mask));
            b += 1;
        }
        entry_idx += 1;
    }
    // Decode the base-27 code (big-endian in `code_bytes`) back to 5 symbols.
    let mut code = (u32::from(code_bytes[0]) << 16)
        | (u32::from(code_bytes[1]) << 8)
        | u32::from(code_bytes[2]);
    let mut out = [0u8; 5];
    let mut i = 5;
    while i > 0 {
        i -= 1;
        let sym = (code % 27) as u8;
        code /= 27;
        // sym == 0 → padding (emit NUL, rendered as a blank by the caller);
        // 1..=26 → 'a'..='z'. `letter_mask` is 0x00 for padding, 0xFF for a
        // letter, so the decode stays branch-free.
        let letter_mask = 0u8.wrapping_sub((sym != 0) as u8);
        out[i] = b'a'.wrapping_add(sym).wrapping_sub(1) & letter_mask;
    }
    out
}

// ---------------------------------------------------------------------------
// Bit packing helper used by hash_to_word_indices + (gated) Mnemonic
// ---------------------------------------------------------------------------

/// Read 11 bits MSB-first from `buf` starting at bit offset `bit`.
#[inline]
pub(crate) fn read_11_bits(buf: &[u8], bit: usize) -> u16 {
    let byte = bit / 8;
    let shift = bit % 8;
    // Load up to three bytes big-endian; the desired 11-bit window lives
    // `shift` bits down from the top of the resulting 24-bit value.
    let b0 = u32::from(buf[byte]);
    let b1 = u32::from(buf[byte + 1]);
    let b2 = if byte + 2 < buf.len() {
        u32::from(buf[byte + 2])
    } else {
        0
    };
    let combined = (b0 << 16) | (b1 << 8) | b2;
    let top = 24 - shift - BITS_PER_WORD;
    ((combined >> top) & 0x7FF) as u16
}

// ---------------------------------------------------------------------------
// Firmware measurement helpers
// ---------------------------------------------------------------------------

/// Extract 8 × 11-bit BIP-39 word indices from the first 88 bits of a
/// SHA-256 hash. Used for firmware measurement display — **not** for
/// mnemonic generation.
#[must_use]
pub fn hash_to_word_indices(hash: &[u8; 32]) -> [u16; 8] {
    let mut indices = [0u16; 8];
    for (i, slot) in indices.iter_mut().enumerate() {
        *slot = read_11_bits(hash, i * BITS_PER_WORD);
    }
    indices
}

// ---------------------------------------------------------------------------
// Firmware-fingerprint text layout (4 rows × 16 cols, 2 words per row)
// ---------------------------------------------------------------------------

/// Number of rows in the firmware-fingerprint text layout.
pub const FINGERPRINT_ROWS: usize = 4;
/// Number of columns in the firmware-fingerprint text layout.
pub const FINGERPRINT_COLS: usize = 16;

/// Pure render: 32-byte SHA-256 secure-image digest → 4 × 16 ASCII byte
/// rows ready to push to the NV3007 LCD text grid (FSBL) or feed to
/// `embedded_graphics::Text` (secure-world `measured_boot`).
///
/// Layout (2 words per row, 4 rows; matches what
/// `secure/src/measured_boot.rs::render_all_words` has been displaying):
///
/// ```text
/// Row 0: "1 close  5 grape"
/// Row 1: "2 agent  6 thoug"
/// Row 2: "3 own    7 sail "
/// Row 3: "4 deput  8 simpl"
/// ```
///
/// Each column is `"N " + 5-byte word prefix + (optional) space` = 8
/// columns. Zero bytes from [`word_prefix_at`] (words shorter than 5
/// chars) become ASCII spaces in the output so the LCD renderer can
/// blit them as blanks instead of NUL glyphs.
///
/// Used by:
///   * `fsbl/src/render.rs` for the legacy bench FSBL NV3007 LCD screen
///   * `secure/src/measured_boot.rs` for the (secondary) self-attested
///     screen the slot draws after FSBL hands over control
///
/// Hosting this function in `bip39` means **both** renderers consume
/// the same pure-logic source of truth, so the legacy FSBL row and the
/// secure-world row stay byte-identical for the same digest. The
/// `firmware_fingerprint_lines` regression test in
/// `bip39/tests/prefix5_roundtrip.rs` pins the exact byte grid.
#[must_use]
pub fn firmware_fingerprint_lines(
    digest: &[u8; 32],
) -> [[u8; FINGERPRINT_COLS]; FINGERPRINT_ROWS] {
    let indices = hash_to_word_indices(digest);
    let mut rows = [[b' '; FINGERPRINT_COLS]; FINGERPRINT_ROWS];

    for row in 0..FINGERPRINT_ROWS {
        let li = row;
        rows[row][0] = b'1' + row as u8;
        rows[row][1] = b' ';
        let lprefix = word_prefix_at(indices[li]);
        for (i, &b) in lprefix.iter().enumerate() {
            rows[row][2 + i] = if b == 0 { b' ' } else { b };
        }

        let ri = row + 4;
        rows[row][8] = b'5' + row as u8;
        rows[row][9] = b' ';
        let rprefix = word_prefix_at(indices[ri]);
        for (i, &b) in rprefix.iter().enumerate() {
            let dst = 10 + i;
            if dst >= FINGERPRINT_COLS {
                break;
            }
            rows[row][dst] = if b == 0 { b' ' } else { b };
        }
    }

    rows
}
