//! Generator for the Charon/Aeneas extraction DIFFERENTIAL gate (roadmap T1.3 (ii)).
//!
//! Runs the SHIPPED Rust `fw_manifest::signed_preimage` on deterministic vectors
//! and writes the EXPECTED outputs into a Lean data file
//! (`contracts/verification/extracted/Extracted/ExtractDiffVectors.lean`) consumed
//! by `Extracted/ExtractDiffCheck.lean`.
//!
//! NON-CIRCULARITY (load-bearing): the `expected` bytes below are the output of
//! EXECUTING this real Rust function — never copied from the Lean `#eval`. The
//! Lean check runs the EXTRACTED Lean `signed_preimage` on the same inputs and
//! asserts equality, so a consistently-wrong Charon/Aeneas translation diverges
//! here (the regen-diff gate cannot catch that).
//!
//! Run: cargo test -p fw-manifest --test gen_extract_vectors --release -- --nocapture
//! (or `make verify-extract-differential GEN=1`).

use fw_manifest::signed_preimage;
use std::fs;

fn lean_bytes(bytes: &[u8]) -> String {
    let mut s = String::from("#[");
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push_str(", ");
        }
        s.push_str(&b.to_string());
    }
    s.push(']');
    s
}

#[test]
fn gen_extract_vectors() {
    // Construct-diverse: version byte-patterns exercise `u32::to_be_bytes`; the
    // distinct per-vector hash content exercises `copy_from_slice` over the two
    // 32-byte fixed arrays + the slice index ranges.
    let versions: [u32; 6] = [0, 1, 0x0102_0304, 0xffff_ffff, 0xdead_beef, 0x00ff_00ff];

    let mut rows = String::new();
    for (i, &ver) in versions.iter().enumerate() {
        let mut sh = [0u8; 32];
        let mut nh = [0u8; 32];
        for j in 0..32 {
            sh[j] = ((i * 7 + j * 3) & 0xff) as u8;
            nh[j] = ((i * 11 + j * 5 + 0x80) & 0xff) as u8;
        }
        let out = signed_preimage(ver, &sh, &nh); // EXECUTED RUST = ground truth
        rows.push_str(&format!(
            "    ({}, {}, {}, {}),\n",
            ver,
            lean_bytes(&sh),
            lean_bytes(&nh),
            lean_bytes(&out)
        ));
    }

    let lean = format!(
        "-- AUTO-GENERATED by fw-manifest/tests/gen_extract_vectors.rs — DO NOT EDIT BY HAND.\n\
         -- Regenerate: make verify-extract-differential GEN=1\n\
         --\n\
         -- Each row is (version, secure_hash[32], nonsecure_hash[32], EXPECTED[75]).\n\
         -- The EXPECTED bytes are the output of EXECUTING the shipped Rust\n\
         -- `fw_manifest::signed_preimage` — the differential ground truth, NEVER the\n\
         -- Lean #eval. `Extracted/ExtractDiffCheck.lean` runs the EXTRACTED Lean\n\
         -- `signed_preimage` on the same inputs and asserts equality, catching a\n\
         -- consistently-wrong Charon/Aeneas translation (which regen-diff cannot).\n\
         namespace ExtractDiff\n\
         \n\
         /-- (version, secure_hash, nonsecure_hash, EXPECTED) — Rust-executed. -/\n\
         def positiveVectors : List (UInt32 × Array UInt8 × Array UInt8 × Array UInt8) :=\n\
         [\n{}]\n\
         \n\
         end ExtractDiff\n",
        rows
    );

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../contracts/verification/extracted/Extracted/ExtractDiffVectors.lean"
    );
    fs::write(path, lean).expect("write ExtractDiffVectors.lean");
    eprintln!("gen_extract_vectors: wrote {} vectors", versions.len());
}
