//! Accurate end-to-end decode vectors for the CowSwap / Gnosis-Safe /
//! Safe-MultiSend clear-signing paths.
//!
//! Unlike the hand-built fixtures in `test_vectors.rs` (whose orderDigest is
//! derived by the firmware itself), every digest and `safeTxHash` here is an
//! INDEPENDENT reference computed off-device by ethers v6's `TypedDataEncoder`
//! against a real 1000 USDC -> >=0.5 WETH GPv2 order on mainnet. The tests
//! assert the firmware's native keccak re-derivation reproduces those
//! references byte-for-byte, then decode each flow and print the resulting
//! human-readable order so `cargo test -- --nocapture` shows it decoded.
//!
//! Vectors generated by `scratchpad/gen_vectors.js` (ethers v6).
//! Re-emitted verbatim by `scratchpad/emit_rs.js` — do not edit the hex by hand.

extern crate alloc;
use alloc::string::String;
use alloc::vec::Vec;

use super::*;
use crate::tx::eip712::safe::multi_send::MsRecordIter;
use crate::tx::eip712::safe::{
    compute_safe_tx_hash, resolve_cow_binding, verify_and_bind_trailer as safe_verify_trailer,
};
use crate::erc20::calldata::{parse_erc20_calldata, Erc20Call};
use sphincs_tz_shared::{APPROVE_HASH_SELECTOR, SAFE_V1_CANONICAL_LEN};

// ---- reference vectors (hex, byte-identical to the ethers output) ---------
const ORDER_DIGEST_HEX: &str = "f97aaf408259debcbe9b251ac5e1097174cf0084fb2f382d8056617068eaa43a";
const CANONICAL_HEX: &str = "0000000000000001a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2742d35cc6634c0532925a3b844bc454e4438f44e000000000000000000000000000000000000000000000000000000003b9aca0000000000000000000000000000000000000000000000000006f05b59d3b200000000000000000000000000000000000000000000000000000000000000000000680000000000000083b9dcb2316e54fc04c10f74c9a3d5dd66a9e4c43c04ccefb9c0c03e61e5fb28";
const WALLET_OWNER_HEX: &str = "fb3C7EB936CAa12B5a884D6123939969A557D430";
const SAFE_ADDR_HEX: &str = "5aFE3855358E112B5647B952709E6165e1c1eEEe";

const DIRECT_PRESIGN_HEX: &str = "ec6cb13f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000038f97aaf408259debcbe9b251ac5e1097174cf0084fb2f382d8056617068eaa43afb3c7eb936caa12b5a884d6123939969a557d430680000000000000000000000";

const SAFE_PRESIGN_HEX: &str = "ec6cb13f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000038f97aaf408259debcbe9b251ac5e1097174cf0084fb2f382d8056617068eaa43a5afe3855358e112b5647b952709e6165e1c1eeee680000000000000000000000";
const SAFE_CANON_HEX: &str = "00000000000000015afe3855358e112b5647b952709e6165e1c1eeee9008d19f58aabd9ed0d60971565aa8510560ab410000000000000000000000000000000000000000000000000000000000000000720774a1e1bb52a564f0c33e0ba05c1bac850d236bd19a8f1c4173364de2366400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const SAFE_TX_HASH_HEX: &str = "0e436954453310227409c573f988f1b7ff49cfe3588e493320396da72791bfaa";
const SAFE_APPROVEHASH_HEX: &str = "d4d9bdcd0e436954453310227409c573f988f1b7ff49cfe3588e493320396da72791bfaa";

const MS_PRESIGN_HEX: &str = "ec6cb13f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000038f97aaf408259debcbe9b251ac5e1097174cf0084fb2f382d8056617068eaa43a5afe3855358e112b5647b952709e6165e1c1eeee680000000000000000000000";
const MS_MULTISEND_HEX: &str = "8d80ff0a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000019200a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000c92e8bdf79f0507f65a392b0ab4667716bfe0110000000000000000000000000000000000000000000000000000000003b9aca00009008d19f58aabd9ed0d60971565aa8510560ab41000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4ec6cb13f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000038f97aaf408259debcbe9b251ac5e1097174cf0084fb2f382d8056617068eaa43a5afe3855358e112b5647b952709e6165e1c1eeee6800000000000000000000000000000000000000000000000000";
const MS_SAFE_CANON_HEX: &str = "00000000000000015afe3855358e112b5647b952709e6165e1c1eeee40a2accbd92bca938b02010e17a5b8929b49130d0000000000000000000000000000000000000000000000000000000000000000044e1d2d0d84e26f34f54e2508eb075bf69058cde56c3bc78dfe645580a2114901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
const MS_SAFE_TX_HASH_HEX: &str = "540f823dbf50531a2252d640ad52141b254bc5c6eecd1c705b6132c774842cac";
const MS_APPROVEHASH_HEX: &str = "d4d9bdcd540f823dbf50531a2252d640ad52141b254bc5c6eecd1c705b6132c774842cac";

const CHAIN_ID: u64 = 1;

// ---- hex / formatting helpers ---------------------------------------------
fn unhex(s: &str) -> Vec<u8> {
    let s = s.strip_prefix("0x").unwrap_or(s);
    assert!(s.len() % 2 == 0, "odd hex len");
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("hex"))
        .collect()
}

fn fixed<const N: usize>(s: &str) -> [u8; N] {
    let v = unhex(s);
    assert_eq!(v.len(), N, "hex len mismatch for [u8; {}]", N);
    let mut a = [0u8; N];
    a.copy_from_slice(&v);
    a
}

fn hexstr(b: &[u8]) -> String {
    b.iter().map(|x| alloc::format!("{x:02x}")).collect()
}

/// Format a 32-byte BE uint256 with `decimals` fixed-point places. Test-only
/// (the order amounts fit in u128); fails loudly rather than truncating.
fn fmt_amount(amount: &[u8; 32], decimals: u32) -> String {
    assert!(
        amount[..16].iter().all(|&b| b == 0),
        "amount exceeds u128 — test fixture bug"
    );
    let mut v: u128 = 0;
    for &b in &amount[16..] {
        v = (v << 8) | b as u128;
    }
    if decimals == 0 {
        return alloc::format!("{v}");
    }
    let scale = 10u128.pow(decimals);
    let int = v / scale;
    let frac = v % scale;
    let mut frac_s = alloc::format!("{frac:0w$}", w = decimals as usize);
    while frac_s.ends_with('0') {
        frac_s.pop();
    }
    if frac_s.is_empty() {
        alloc::format!("{int}")
    } else {
        alloc::format!("{int}.{frac_s}")
    }
}

/// Known-token (symbol, decimals) for test display only — mirrors what the
/// on-device ERC-20 Merkle bundle would resolve a decoded leg to.
fn token_meta(addr: &[u8; 20]) -> (&'static str, u32) {
    match hexstr(addr).as_str() {
        "a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48" => ("USDC", 6),
        "c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2" => ("WETH", 18),
        _ => ("???", 0),
    }
}

/// Decode + pretty-print a verified 204-byte canonical GPv2 order the way the
/// trusted-UI pages present it, so `--nocapture` shows the decoded order.
fn print_decoded_order(canonical: &[u8; 204]) {
    let o = decode_canonical(canonical).expect("decode");
    let (sell_sym, sell_dp) = token_meta(&o.sell_token);
    let (buy_sym, buy_dp) = token_meta(&o.buy_token);
    let kind = if o.kind == 0 { "SELL" } else { "BUY" };
    std::println!("    ┌─ CowSwap GPv2Order ───────────────");
    std::println!("    │ chain    : {} (Mainnet)", o.chain_id);
    std::println!("    │ kind     : {kind}");
    std::println!(
        "    │ sell     : {} {sell_sym}  (0x{})",
        fmt_amount(&o.sell_amount, sell_dp),
        hexstr(&o.sell_token)
    );
    std::println!(
        "    │ buy(min) : {} {buy_sym}  (0x{})",
        fmt_amount(&o.buy_amount, buy_dp),
        hexstr(&o.buy_token)
    );
    std::println!("    │ receiver : 0x{}", hexstr(&o.receiver));
    std::println!("    │ fee      : {} {sell_sym}", fmt_amount(&o.fee_amount, sell_dp));
    std::println!("    │ validTo  : unix {}", o.valid_to);
    std::println!("    │ partial  : {}", if o.partially_fillable == 0 { "no" } else { "yes" });
    std::println!("    │ appData  : 0x{}", hexstr(&o.app_data));
    std::println!("    └───────────────────────────────────");
}

// ===========================================================================
// Flow 1 — direct CowSwap (owner = the wallet smart account)
// ===========================================================================
#[test]
fn e2e_direct_cowswap_decodes_and_matches_reference_digest() {
    let canonical: [u8; 204] = fixed(CANONICAL_HEX);
    let calldata: [u8; 164] = fixed(DIRECT_PRESIGN_HEX);
    let owner: [u8; 20] = fixed(WALLET_OWNER_HEX);
    let digest_ref: [u8; 32] = fixed(ORDER_DIGEST_HEX);

    // (1) The firmware's native EIP-712 digest equals the ethers reference.
    let digest = compute_digest(&canonical, CHAIN_ID).expect("digest");
    assert_eq!(
        digest, digest_ref,
        "firmware orderDigest diverged from ethers reference"
    );

    // (2) Structural shape + full field cross-check against the signed
    //     setPreSignature calldata.
    check_setpresig_calldata_shape(&calldata).expect("shape");
    cross_check_setpresig_calldata(&canonical, &calldata, CHAIN_ID, &owner).expect("cross-check");

    // (3) The orderUid embedded in the calldata carries the reference digest.
    assert_eq!(&calldata[100..132], digest_ref.as_slice());

    // (4) Decode trailer end-to-end (canonical-only → both legs AddrHex).
    let v = verify_and_bind_trailer(&canonical, &calldata, CHAIN_ID, &owner)
        .expect("trailer must verify");
    assert!(matches!(v.sell, CowLeg::AddrHex));
    assert!(matches!(v.buy, CowLeg::AddrHex));

    std::println!("\n[e2e direct CowSwap] decoded & bound (owner = wallet):");
    print_decoded_order(&canonical);
    std::println!("    orderDigest (ethers == firmware): 0x{}", hexstr(&digest));
}

// ===========================================================================
// Flow 2 — Gnosis Safe wrapping a CowSwap setPreSignature (owner = the Safe)
// ===========================================================================
#[test]
fn e2e_safe_wrapped_cowswap_decodes_and_matches_reference() {
    let canonical: [u8; 204] = fixed(CANONICAL_HEX);
    let safe: [u8; 20] = fixed(SAFE_ADDR_HEX);
    let presign: [u8; 164] = fixed(SAFE_PRESIGN_HEX);
    let safe_canon: [u8; SAFE_V1_CANONICAL_LEN] = fixed(SAFE_CANON_HEX);
    let safe_tx_hash_ref: [u8; 32] = fixed(SAFE_TX_HASH_HEX);
    let inner: [u8; 36] = fixed(SAFE_APPROVEHASH_HEX);

    // (1) Native safeTxHash equals the ethers reference.
    let safe_tx_hash = compute_safe_tx_hash(&safe_canon).expect("safeTxHash");
    assert_eq!(
        safe_tx_hash, safe_tx_hash_ref,
        "firmware safeTxHash diverged from ethers reference"
    );
    // The approveHash calldata commits to exactly that hash.
    assert_eq!(&inner[..4], APPROVE_HASH_SELECTOR.as_slice());
    assert_eq!(&inner[4..36], safe_tx_hash_ref.as_slice());

    // (2) Build the safe_v1 trailer bundle (canonical || u16 len || raw_data)
    //     and verify it against the approveHash calldata.
    let mut bundle = Vec::new();
    bundle.extend_from_slice(&safe_canon);
    bundle.extend_from_slice(&(presign.len() as u16).to_be_bytes());
    bundle.extend_from_slice(&presign);
    let verified =
        safe_verify_trailer(&bundle, &inner, CHAIN_ID, &safe).expect("safe trailer must verify");

    // (3) Resolve the CoW binding off the verified Safe: owner is the Safe,
    //     the bound calldata is the inner setPreSignature record.
    let wallet_sender: [u8; 20] = fixed(WALLET_OWNER_HEX);
    let bind = resolve_cow_binding(&inner, &wallet_sender, Some(&verified), None);
    assert!(bind.via_safe);
    assert_eq!(bind.owner, safe);
    assert_eq!(bind.calldata, presign.as_slice());

    // (4) The v3 cross-check passes against the order canonical with the
    //     Safe as uid.owner — and FAILS if we expect the wallet sender.
    let cd: &[u8; 164] = bind.calldata.try_into().unwrap();
    check_setpresig_calldata_shape(cd).expect("shape");
    cross_check_setpresig_calldata(&canonical, cd, CHAIN_ID, &bind.owner).expect("cross-check");
    assert_eq!(
        cross_check_setpresig_calldata(&canonical, cd, CHAIN_ID, &wallet_sender),
        Err(OrderUidMismatch::OwnerMismatch)
    );

    std::println!("\n[e2e Safe-wrapped CowSwap] decoded & bound (owner = Safe 0x{}):", hexstr(&safe));
    std::println!("    safeTxHash (ethers == firmware): 0x{}", hexstr(&safe_tx_hash));
    print_decoded_order(&canonical);
}

// ===========================================================================
// Flow 3 — Gnosis Safe -> MultiSend([ approve(vaultRelayer), setPreSignature ])
// ===========================================================================
#[test]
fn e2e_safe_multisend_approve_then_cowswap_decodes_and_matches_reference() {
    let canonical: [u8; 204] = fixed(CANONICAL_HEX);
    let safe: [u8; 20] = fixed(SAFE_ADDR_HEX);
    let presign: [u8; 164] = fixed(MS_PRESIGN_HEX);
    let multisend: Vec<u8> = unhex(MS_MULTISEND_HEX);
    let safe_canon: [u8; SAFE_V1_CANONICAL_LEN] = fixed(MS_SAFE_CANON_HEX);
    let safe_tx_hash_ref: [u8; 32] = fixed(MS_SAFE_TX_HASH_HEX);
    let inner: [u8; 36] = fixed(MS_APPROVEHASH_HEX);

    // (1) Native safeTxHash for the DELEGATECALL-into-MultiSend SafeTx equals
    //     the ethers reference.
    let safe_tx_hash = compute_safe_tx_hash(&safe_canon).expect("safeTxHash");
    assert_eq!(safe_tx_hash, safe_tx_hash_ref, "multiSend safeTxHash diverged");
    assert_eq!(&inner[4..36], safe_tx_hash_ref.as_slice());

    // (2) safe_v1 trailer verifies: the operation gate opens for the
    //     allowlisted MultiSendCallOnly DELEGATECALL target.
    let mut bundle = Vec::new();
    bundle.extend_from_slice(&safe_canon);
    bundle.extend_from_slice(&(multisend.len() as u16).to_be_bytes());
    bundle.extend_from_slice(&multisend);
    let verified = safe_verify_trailer(&bundle, &inner, CHAIN_ID, &safe)
        .expect("multiSend safe trailer must verify");
    assert_eq!(verified.canonical[112], 1, "operation must be DELEGATECALL");

    // (3) Strictly decode the multiSend payload and print BOTH inner records:
    //     record 0 = ERC-20 approve(vaultRelayer, amount) on the sell token,
    //     record 1 = setPreSignature(orderUid) on the settlement contract.
    let packed = crate::tx::eip712::safe::multi_send::decode_multisend(&multisend)
        .expect("multiSend must decode");
    let records: Vec<_> = MsRecordIter::new(packed)
        .map(|r| r.expect("record"))
        .collect();
    assert_eq!(records.len(), 2, "expected [approve, setPreSignature]");

    std::println!("\n[e2e Safe -> MultiSend] decoded & bound (owner = Safe 0x{}):", hexstr(&safe));
    std::println!("    safeTxHash (ethers == firmware): 0x{}", hexstr(&safe_tx_hash));
    std::println!("    ── MultiSend record 0 (allowance) ──");
    match parse_erc20_calldata(records[0].data) {
        Some(Erc20Call::Approve { spender, amount }) => {
            std::println!(
                "    │ approve  : spender 0x{}  amount {} USDC",
                hexstr(&spender),
                fmt_amount(&amount.0, 6)
            );
            std::println!("    │ on token : 0x{}", hexstr(&records[0].to));
        }
        other => panic!("record 0 must be an ERC-20 approve, got {other:?}"),
    }
    std::println!("    ── MultiSend record 1 (CowSwap presign) ──");
    assert_eq!(&records[1].data[..4], &[0xec, 0x6c, 0xb1, 0x3f], "record 1 = setPreSignature");

    // (4) The binding resolver targets the presign RECORD inside the batch —
    //     not the multiSend wrapper — and the v3 cross-check passes with the
    //     Safe as uid.owner.
    let wallet_sender: [u8; 20] = fixed(WALLET_OWNER_HEX);
    let bind = resolve_cow_binding(&inner, &wallet_sender, Some(&verified), None);
    assert!(bind.via_safe);
    assert_eq!(bind.owner, safe);
    assert_eq!(
        bind.calldata,
        presign.as_slice(),
        "binding must be the presign record's bytes, not the multiSend wrapper"
    );
    let cd: &[u8; 164] = bind.calldata.try_into().unwrap();
    check_setpresig_calldata_shape(cd).expect("shape");
    cross_check_setpresig_calldata(&canonical, cd, CHAIN_ID, &bind.owner).expect("cross-check");

    print_decoded_order(&canonical);
}
