-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace sphincs_c10

/-- [sphincs_c10::address::make_adrs]:
    Source: 'sphincs-c10/src/address.rs', lines 22:0-41:1
    Visibility: public -/
def address.make_adrs
  (layer : Std.U32) (tree : Std.U64) (atype : Std.U32) (kp : Std.U32)
  (ci : Std.U32) (cp : Std.U32) (ha : Std.U32) :
  Result (Array Std.U8 32#usize)
  := do
  let buf := Array.repeat 32#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
      { start := 0#usize, «end» := 4#usize }
  let a ← lift (core.num.U32.to_be_bytes layer)
  let s1 ← lift (Array.to_slice a)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
      { start := 4#usize, «end» := 12#usize }
  let a1 ← lift (core.num.U64.to_be_bytes tree)
  let s4 ← lift (Array.to_slice a1)
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let buf2 := index_mut_back1 s5
  let (s6, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf2
      { start := 12#usize, «end» := 16#usize }
  let a2 ← lift (core.num.U32.to_be_bytes atype)
  let s7 ← lift (Array.to_slice a2)
  let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
  let buf3 := index_mut_back2 s8
  let (s9, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf3
      { start := 16#usize, «end» := 20#usize }
  let a3 ← lift (core.num.U32.to_be_bytes kp)
  let s10 ← lift (Array.to_slice a3)
  let s11 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s9 s10
  let buf4 := index_mut_back3 s11
  let (s12, index_mut_back4) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf4
      { start := 20#usize, «end» := 24#usize }
  let a4 ← lift (core.num.U32.to_be_bytes ci)
  let s13 ← lift (Array.to_slice a4)
  let s14 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s12 s13
  let buf5 := index_mut_back4 s14
  let (s15, index_mut_back5) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf5
      { start := 24#usize, «end» := 28#usize }
  let a5 ← lift (core.num.U32.to_be_bytes cp)
  let s16 ← lift (Array.to_slice a5)
  let s17 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s15 s16
  let buf6 := index_mut_back5 s17
  let (s18, index_mut_back6) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf6
      { start := 28#usize, «end» := 32#usize }
  let a6 ← lift (core.num.U32.to_be_bytes ha)
  let s19 ← lift (Array.to_slice a6)
  let s20 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s18 s19
  ok (index_mut_back6 s20)

/-- [sphincs_c10::address::set_chain_index]:
    Source: 'sphincs-c10/src/address.rs', lines 46:0-50:1
    Visibility: public -/
def address.set_chain_index
  (adrs : Array Std.U8 32#usize) (idx : Std.U32) :
  Result (Array Std.U8 32#usize)
  := do
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) adrs
      { start := 20#usize, «end» := 24#usize }
  let a ← lift (core.num.U32.to_be_bytes idx)
  let s1 ← lift (Array.to_slice a)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (index_mut_back s2)

end sphincs_c10
