/-
Charon/Aeneas extraction DIFFERENTIAL gate (roadmap T1.3 (ii)).

Run (interpreted — no native compile, like `AxiomCheck.lean`):
    lake env lean Extracted/ExtractDiffCheck.lean
via `make verify-extract-differential` in `contracts/verification/`.

## What it is, and what it is NOT

The `extract-*` Makefile targets are a REGEN-DIFF gate: re-run Charon+Aeneas on
the current Rust and `diff` against the committed `Extracted/*.lean`, catching a
Rust change that was not re-extracted. They do NOT catch a *consistently-wrong*
translation — if Charon/Aeneas systematically mistranslate a construct, the regen
reproduces the same wrong Lean and the diff passes.

This gate is the complementary layer: it EXECUTES the extracted Lean functions on
input vectors whose EXPECTED outputs were produced by running the SHIPPED Rust
(`fw-manifest/tests/gen_extract_vectors.rs`), and FAILS on any divergence. A
mistranslation that changes a function's computed behaviour on a tested vector is
caught here.

**Honest scope — CORPUS evidence (tier C), not a ∀ proof.** It SHRINKS the
Charon/Aeneas faithfulness TCB (assurance-case defeater D5) to the untested-input
residual; it does not close it. A consistent mistranslation that agrees on every
tested vector but diverges elsewhere is not caught — exactly the A3.1-verifier-KAT
bound. Charon has no foundational soundness proof (arXiv:2410.18042); that stays
cited-TCB. "Strictly better, never zero."

**Non-circularity (load-bearing).** The expected outputs come from executing the
real Rust, regenerated by the `GEN=1` step — never copied from this Lean `#eval`.
Comparing the extraction to itself would be vacuous.

**Negative control (teeth).** A permanent set of vectors with deliberately-wrong
expected outputs that the gate MUST flag; if any "matches", the comparison is
broken (a harness-format bug could otherwise yield a spurious green) and the gate
fails. Checked before the positives are trusted.

**Construct coverage (no silent caps).** The risk is per-Rust-construct (slice
indexing, `to_be_bytes`, struct layout, bounds checks). Covered so far:
`signed_preimage` — slices + `copy_from_slice` + `U32::to_be_bytes` + fixed-array
layout. NOT yet covered: control-flow/bounds parsers (`decode_item`),
hash-structural derivations. Logged here so the gap is explicit; extend
`positiveVectors` + the Rust generator to grow coverage.
-/

import Extracted.FwManifest.Funs
import Extracted.ExtractDiffVectors

open Aeneas Aeneas.Std Result

namespace ExtractDiff

/-! ## Byte / Std-type bridges -/

/-- `Std.U8` → `UInt8` (fully-qualified accessor to dodge the mathlib `.val`/`.bv`
    overload swamp). -/
def u8ToByte (b : Std.U8) : UInt8 := (Aeneas.Std.UScalar.bv b).toNat.toUInt8

/-- `UInt8` → `Std.U8` via the `BitVec` field (no bounds-proof obligation, unlike
    `Std.U8.ofNat`; `BitVec.ofNat` wraps mod 2^8). -/
def byteToU8 (b : UInt8) : Std.U8 := ⟨BitVec.ofNat 8 b.toNat⟩

/-- Build a length-32 `Std.Array Std.U8` from runtime bytes (length-checked). -/
def mkArr32 (bytes : Array UInt8) : Option (Std.Array Std.U8 32#usize) :=
  let l : List Std.U8 := bytes.toList.map byteToU8
  if h : l.length = 32 then some ⟨l, by simpa using h⟩ else none

/-- Run the EXTRACTED `fw_manifest.signed_preimage` and return its 75 output
    bytes (or `none` on bad input length / Aeneas failure). -/
def runSignedPreimage (ver : UInt32) (sec ns : Array UInt8) : Option (Array UInt8) := do
  let secA ← mkArr32 sec
  let nsA ← mkArr32 ns
  match fw_manifest.signed_preimage ⟨BitVec.ofNat 32 ver.toNat⟩ secA nsA with
  | .ok out => some ((out.val.map u8ToByte).toArray)
  | _ => none

/-! ## Negative control — the gate's teeth -/

structure NegCase where
  ver : UInt32
  fill : UInt8                 -- secure_hash = nonsecure_hash = replicate 32 fill
  wrongExpected : Array UInt8

/-- Deliberately-wrong expected outputs `signed_preimage` provably never produces
    (it always emits "PQFW_V1" ‖ …), so a correct gate flags every one. -/
def negCases : List NegCase :=
  [ { ver := 0x01020304, fill := 7,  wrongExpected := Array.replicate 75 0 },
    { ver := 0,          fill := 0,  wrongExpected := Array.replicate 75 0xff },
    -- right length, wrong domain tag (first byte 0x00 instead of 'P'=0x50):
    { ver := 0xdeadbeef, fill := 42, wrongExpected := (Array.replicate 75 0).set! 0 0x00 } ]

/-- The negative control has teeth iff EVERY wrong vector mismatches. -/
def negativeControlPasses : Bool :=
  negCases.all fun c =>
    match runSignedPreimage c.ver (Array.replicate 32 c.fill) (Array.replicate 32 c.fill) with
    | some got => got ≠ c.wrongExpected      -- must MISMATCH the wrong expected
    | none => false                          -- runner failure is also a failure

/-! ## Positive vectors — the actual differential (Rust-executed expected) -/

/-- Index of the first positive vector where the EXTRACTED Lean output differs
    from the Rust-executed expected (or `none` if all agree). `positiveVectors`
    is Rust-generated (`ExtractDiffVectors.lean`); the expected is executed Rust. -/
def firstPositiveMismatch : Option Nat := Id.run do
  for i in [0:positiveVectors.length] do
    let (ver, sec, ns, expected) := positiveVectors[i]!
    match runSignedPreimage ver sec ns with
    | some got => if got ≠ expected then return some i
    | none => return some i
  return none

end ExtractDiff

open ExtractDiff in
/-- Self-test driver. Checks the negative control (teeth) — the positive
    Rust-vector pass is added with the JSON loader. Exits non-zero on failure. -/
def driver : IO Unit := do
  IO.println "== verify-extract-diff: Charon/Aeneas extraction differential =="
  -- 1. Negative control FIRST — prove the comparison has teeth before any green.
  if negativeControlPasses then
    IO.println s!"  [OK] negative control: all {negCases.length} deliberately-wrong vectors flagged"
  else
    IO.eprintln "  [FAIL] negative control: a wrong vector was NOT flagged — gate is toothless"
    IO.Process.exit 1
  -- 2. Positive differential — extracted Lean vs Rust-executed expected.
  match firstPositiveMismatch with
  | none =>
    IO.println s!"  [OK] signed_preimage: extracted Lean == Rust on all {positiveVectors.length} vectors"
    IO.println "  (CORPUS evidence — shrinks the Charon/Aeneas TCB on tested inputs; not a ∀)"
  | some i =>
    IO.eprintln s!"  [FAIL] signed_preimage: extracted Lean ≠ Rust on vector {i} — \
                   a Charon/Aeneas mistranslation (or stale vectors: regen with GEN=1)"
    IO.Process.exit 1

#eval driver
