/-
Charon/Aeneas extraction DIFFERENTIAL gate (roadmap T1.3 (ii)).

Run (interpreted — no native compile, like `AxiomCheck.lean`):
    lake env lean Extracted/ExtractDiffCheck.lean
via `make verify-extract-differential` in `contracts/verification/`.

## What it is, and what it is NOT

The `extract-*` Makefile targets are a REGEN-DIFF gate: re-run Charon+Aeneas on
the current Rust and `diff` against the committed `Extracted/*.lean`, catching a
Rust change that was not re-extracted. They do NOT catch a *consistently-wrong*
translation — if Charon/Aeneas systematically mistranslate a construct, the regen
reproduces the same wrong Lean and the diff passes.

This gate is the complementary layer: it EXECUTES the extracted Lean functions on
input vectors whose EXPECTED outputs were produced by running the SHIPPED Rust
(`fw-manifest/tests/gen_extract_vectors.rs`), and FAILS on any divergence. A
mistranslation that changes a function's computed behaviour on a tested vector is
caught here.

**Honest scope — CORPUS evidence (tier C), not a ∀ proof.** It SHRINKS the
Charon/Aeneas faithfulness TCB (assurance-case defeater D5) to the untested-input
residual; it does not close it. A consistent mistranslation that agrees on every
tested vector but diverges elsewhere is not caught — exactly the A3.1-verifier-KAT
bound. Charon has no foundational soundness proof (arXiv:2410.18042); that stays
cited-TCB. "Strictly better, never zero."

**Non-circularity (load-bearing).** The expected outputs come from executing the
real Rust, regenerated by the `GEN=1` step — never copied from this Lean `#eval`.
Comparing the extraction to itself would be vacuous.

**Negative control (teeth).** A permanent set of vectors with deliberately-wrong
expected outputs that the gate MUST flag; if any "matches", the comparison is
broken (a harness-format bug could otherwise yield a spurious green) and the gate
fails. Checked before the positives are trusted.

**Construct coverage (no silent caps).** The risk is per-Rust-construct (slice
indexing, `to_be_bytes`, struct layout, bounds checks). Covered so far:
`signed_preimage` — slices + `copy_from_slice` + `U32::to_be_bytes` + fixed-array
layout; `u256_format_decimal` (Track-1 M8, `FormatDecimalDiffVectors.lean`) —
Range loops over indexed arrays, `while`-loop digit extraction/carry, integer
div/mod, `saturating_sub`, early-`return None` bounds check, slice writes.
NOT yet covered: control-flow/bounds parsers (`decode_item`), hash-structural
derivations. Logged here so the gap is explicit; extend the vector lists + the
Rust generator to grow coverage.
-/

import Extracted.FwManifest.Funs
import Extracted.FormatDecimal.Funs
import Extracted.ExtractDiffVectors
import Extracted.FormatDecimalDiffVectors

open Aeneas Aeneas.Std Result

namespace ExtractDiff

/-! ## Byte / Std-type bridges -/

/-- `Std.U8` → `UInt8` (fully-qualified accessor to dodge the mathlib `.val`/`.bv`
    overload swamp). -/
def u8ToByte (b : Std.U8) : UInt8 := (Aeneas.Std.UScalar.bv b).toNat.toUInt8

/-- `UInt8` → `Std.U8` via the `BitVec` field (no bounds-proof obligation, unlike
    `Std.U8.ofNat`; `BitVec.ofNat` wraps mod 2^8). -/
def byteToU8 (b : UInt8) : Std.U8 := ⟨BitVec.ofNat 8 b.toNat⟩

/-- Build a length-32 `Std.Array Std.U8` from runtime bytes (length-checked). -/
def mkArr32 (bytes : Array UInt8) : Option (Std.Array Std.U8 32#usize) :=
  let l : List Std.U8 := bytes.toList.map byteToU8
  if h : l.length = 32 then some ⟨l, by simpa using h⟩ else none

/-- Run the EXTRACTED `fw_manifest.signed_preimage` and return its 75 output
    bytes (or `none` on bad input length / Aeneas failure). -/
def runSignedPreimage (ver : UInt32) (sec ns : Array UInt8) : Option (Array UInt8) := do
  let secA ← mkArr32 sec
  let nsA ← mkArr32 ns
  match fw_manifest.signed_preimage ⟨BitVec.ofNat 32 ver.toNat⟩ secA nsA with
  | .ok out => some ((out.val.map u8ToByte).toArray)
  | _ => none

/-! ## Negative control — the gate's teeth -/

structure NegCase where
  ver : UInt32
  fill : UInt8                 -- secure_hash = nonsecure_hash = replicate 32 fill
  wrongExpected : Array UInt8

/-- Deliberately-wrong expected outputs `signed_preimage` provably never produces
    (it always emits "PQFW_V1" ‖ …), so a correct gate flags every one. -/
def negCases : List NegCase :=
  [ { ver := 0x01020304, fill := 7,  wrongExpected := Array.replicate 75 0 },
    { ver := 0,          fill := 0,  wrongExpected := Array.replicate 75 0xff },
    -- right length, wrong domain tag (first byte 0x00 instead of 'P'=0x50):
    { ver := 0xdeadbeef, fill := 42, wrongExpected := (Array.replicate 75 0).set! 0 0x00 } ]

/-- The negative control has teeth iff EVERY wrong vector mismatches. -/
def negativeControlPasses : Bool :=
  negCases.all fun c =>
    match runSignedPreimage c.ver (Array.replicate 32 c.fill) (Array.replicate 32 c.fill) with
    | some got => got ≠ c.wrongExpected      -- must MISMATCH the wrong expected
    | none => false                          -- runner failure is also a failure

/-! ## Positive vectors — the actual differential (Rust-executed expected) -/

/-- Index of the first positive vector where the EXTRACTED Lean output differs
    from the Rust-executed expected (or `none` if all agree). `positiveVectors`
    is Rust-generated (`ExtractDiffVectors.lean`); the expected is executed Rust. -/
def firstPositiveMismatch : Option Nat := Id.run do
  for i in [0:positiveVectors.length] do
    let (ver, sec, ns, expected) := positiveVectors[i]!
    match runSignedPreimage ver sec ns with
    | some got => if got ≠ expected then return some i
    | none => return some i
  return none

/-! ## format_decimal (Track-1 M8) — extracted `u256_format_decimal` vs Rust -/

/-- The out-buffer fill byte. Matches `SENTINEL` in the Rust generator: the
    generator asserts the SHIPPED Rust leaves bytes past the returned count
    untouched, and `runFormatDecimal` checks the same of the EXTRACTED Lean —
    a divergent stray write is a mismatch even when the prefix agrees. -/
def fdSentinel : UInt8 := 0xAA

/-- Build a sentinel-filled `Slice Std.U8` of length `len`. -/
def mkSliceFill (len : Nat) : Option (Slice Std.U8) :=
  let l : List Std.U8 := List.replicate len (byteToU8 fdSentinel)
  if h : l.length ≤ Usize.max then some ⟨l, h⟩ else none

/-- Run the EXTRACTED `eip1559.u256_format_decimal` on a sentinel-filled
    `out` of length `outLen`. Returns `some (some prefix)` on a successful
    write, `some none` on the would-not-fit path, and `none` on any runner
    failure (Aeneas panic, count out of bounds, stray write past the count,
    write on the `none` path — none of which the shipped Rust ever does). -/
def runFormatDecimal (value : Array UInt8) (decimals fracDigits : UInt32)
    (trim : Bool) (outLen : Nat) : Option (Option (Array UInt8)) := do
  let v ← mkArr32 value
  let out ← mkSliceFill outLen
  match pqsigner_tx_core.eip1559.u256_format_decimal v
      ⟨BitVec.ofNat 32 decimals.toNat⟩ ⟨BitVec.ofNat 32 fracDigits.toNat⟩
      trim out with
  | .ok (some n, outS) =>
    let nn := (Aeneas.Std.UScalar.bv n).toNat
    let bytes := outS.val.map u8ToByte
    if decide (nn ≤ outLen) && (bytes.drop nn).all (· == fdSentinel) then
      some (some (bytes.take nn).toArray)
    else none
  | .ok (none, outS) =>
    -- Rust writes nothing on overflow; the extracted Lean must match.
    if (outS.val.map u8ToByte).all (· == fdSentinel) then some none else none
  | _ => none

/-- format_decimal negative control (teeth for the `Option`-shaped compare:
    wrong bytes, `some`/`none` confusion in both directions). -/
structure FdNegCase where
  value : Array UInt8
  decimals : UInt32
  frac : UInt32
  trim : Bool
  outLen : Nat
  wrongExpected : Option (Array UInt8)

/-- ASCII helper for the hand-written wrong expectations. -/
def asciiBytes (s : String) : Array UInt8 := s.toUTF8.data

/-- The integer 42 as a 32-byte BE U256. -/
def fdVal42 : Array UInt8 := (Array.replicate 32 0).set! 31 42

/-- Deliberately-wrong expectations `u256_format_decimal` provably never
    produces on these inputs (it renders `42` at decimals=0, and returns
    `none` for a 1-byte buffer), so a correct gate flags every one. -/
def fdNegCases : List FdNegCase :=
  [ -- right shape, wrong digits:
    { value := fdVal42, decimals := 0, frac := 0, trim := false, outLen := 16,
      wrongExpected := some (asciiBytes "43") },
    -- fits, but expectation claims it did not (some/none confusion):
    { value := fdVal42, decimals := 0, frac := 0, trim := false, outLen := 16,
      wrongExpected := none },
    -- does NOT fit (need=2 > 1), but expectation claims a truncated write:
    { value := fdVal42, decimals := 0, frac := 0, trim := false, outLen := 1,
      wrongExpected := some (asciiBytes "4") } ]

/-- The format_decimal negative control has teeth iff EVERY wrong vector
    mismatches. -/
def fdNegativeControlPasses : Bool :=
  fdNegCases.all fun c =>
    match runFormatDecimal c.value c.decimals c.frac c.trim c.outLen with
    | some got => got ≠ c.wrongExpected     -- must MISMATCH the wrong expected
    | none => false                         -- runner failure is also a failure

/-- Index of the first format_decimal vector where the EXTRACTED Lean output
    differs from the Rust-executed expected (or `none` if all agree).
    `fdVectors` is Rust-generated (`FormatDecimalDiffVectors.lean`). -/
def firstFdMismatch : Option Nat := Id.run do
  for i in [0:fdVectors.length] do
    let (value, decimals, frac, trim, outLen, expected) := fdVectors[i]!
    match runFormatDecimal value decimals frac trim outLen with
    | some got => if got ≠ expected then return some i
    | none => return some i
  return none

end ExtractDiff

open ExtractDiff in
/-- Self-test driver. Checks the negative control (teeth) — the positive
    Rust-vector pass is added with the JSON loader. Exits non-zero on failure. -/
def driver : IO Unit := do
  IO.println "== verify-extract-diff: Charon/Aeneas extraction differential =="
  -- 1. Negative control FIRST — prove the comparison has teeth before any green.
  if negativeControlPasses then
    IO.println s!"  [OK] negative control: all {negCases.length} deliberately-wrong vectors flagged"
  else
    IO.eprintln "  [FAIL] negative control: a wrong vector was NOT flagged — gate is toothless"
    IO.Process.exit 1
  -- 2. Positive differential — extracted Lean vs Rust-executed expected.
  match firstPositiveMismatch with
  | none =>
    IO.println s!"  [OK] signed_preimage: extracted Lean == Rust on all {positiveVectors.length} vectors"
  | some i =>
    IO.eprintln s!"  [FAIL] signed_preimage: extracted Lean ≠ Rust on vector {i} — \
                   a Charon/Aeneas mistranslation (or stale vectors: regen with GEN=1)"
    IO.Process.exit 1
  -- 3. format_decimal negative control (teeth for the Option-shaped compare).
  if fdNegativeControlPasses then
    IO.println s!"  [OK] negative control: all {fdNegCases.length} deliberately-wrong format_decimal vectors flagged"
  else
    IO.eprintln "  [FAIL] negative control: a wrong format_decimal vector was NOT flagged — gate is toothless"
    IO.Process.exit 1
  -- 4. format_decimal positive differential (Track-1 M8).
  match firstFdMismatch with
  | none =>
    IO.println s!"  [OK] u256_format_decimal: extracted Lean == Rust on all {fdVectors.length} vectors"
    IO.println "  (CORPUS evidence — shrinks the Charon/Aeneas TCB on tested inputs; not a ∀)"
  | some i =>
    IO.eprintln s!"  [FAIL] u256_format_decimal: extracted Lean ≠ Rust on vector {i} — \
                   a Charon/Aeneas mistranslation (or stale vectors: regen with GEN=1)"
    IO.Process.exit 1

#eval driver
