-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS (import paths localised:
-- `Sk.*` -> `Extracted.SlotKdf.*`).
-- [pqsigner_domain]: function definitions
import Aeneas
import Extracted.SlotKdf.Types
import Extracted.SlotKdf.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pqsigner_domain

/-- [pqsigner_domain::slot_entropy]:
    Source: 'domain/src/lib.rs', lines 660:0-668:1
    Visibility: public -/
def slot_entropy
  (master_entropy : Array Std.U8 32#usize) (chain_id : Std.U64)
  (slot_index : Std.U32) :
  Result (Array Std.U8 32#usize)
  := do
  let buf := Array.repeat 56#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
      { start := 0#usize, «end» := 32#usize }
  let s1 ← lift (Array.to_slice master_entropy)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
      { start := 32#usize, «end» := 44#usize }
  let s4 ←
    lift (Array.to_slice
      (Array.make 12#usize [
        115#u8, 108#u8, 111#u8, 116#u8, 95#u8, 101#u8, 110#u8, 116#u8, 114#u8,
        111#u8, 112#u8, 121#u8
        ]))
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let buf2 := index_mut_back1 s5
  let (s6, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf2
      { start := 44#usize, «end» := 52#usize }
  let a ← lift (core.num.U64.to_be_bytes chain_id)
  let s7 ← lift (Array.to_slice a)
  let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
  let buf3 := index_mut_back2 s8
  let (s9, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf3
      { start := 52#usize, «end» := 56#usize }
  let a1 ← lift (core.num.U32.to_be_bytes slot_index)
  let s10 ← lift (Array.to_slice a1)
  let s11 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s9 s10
  let buf4 := index_mut_back3 s11
  let s12 ← lift (Array.to_slice buf4)
  sha256_bytes s12

end pqsigner_domain
