-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS (import paths localised:
-- `Sk.*` -> `Extracted.SlotKdf.*`).
-- [pqsigner_domain]: type definitions (none for the slot-KDF entry points).
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pqsigner_domain

end pqsigner_domain
