//! Generates `WORDLIST_PREFIX5_PACKED` at compile time from `src/wordlist.rs`.
//!
//! The full BIP-39 English wordlist (`WORDLIST`) costs ~18 KB of rodata
//! once expanded into the fixed-stride `WORDLIST_FLAT` + `WORDLIST_LENS`
//! tables that the constant-time scans need. The FSBL's flash ceiling can't
//! afford that — but it still needs to render the 8 BIP-39 measurement words
//! on the LCD before branching into the slot. The base-27-packed 5-char
//! prefix table here (6 KB, 3 bytes/entry) is the FSBL's whole wordlist.
//!
//! BIP-39 guarantees every English word has a unique 4-character prefix, so
//! a 5-char prefix round-trips back to a full word deterministically. Each
//! prefix (padding = 0, `a`..=`z` = 1..=26) is stored as a base-27 integer
//! (max `27^5 - 1 = 14_348_906 < 2^24`) in 3 bytes; `word_prefix_at` decodes
//! it losslessly, so the rendered display is byte-identical to the former
//! `[[u8; 5]; 2048]` table at ~40% less rodata.
//!
//! See the prefix5-roundtrip integration test in `bip39/tests/` for the
//! round-trip / uniqueness / bounds invariants this generator must uphold.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

/// Pack a 5-byte zero-padded lowercase prefix into 3 bytes via base-27
/// (padding = 0, `a`..=`z` = 1..=26; big-endian). This is the exact inverse
/// of the decode in `sphincs_tz_bip39::word_prefix_at`. It is a bijection on
/// `{0, b'a'..=b'z'}^5` (max code `27^5 - 1 = 14_348_906 < 2^24`), so it is
/// byte-lossless for every BIP-39 prefix — the rendered fingerprint is
/// identical to the former `[[u8; 5]; 2048]` table, at 6 KB instead of 10 KB.
fn pack_prefix5(p: [u8; 5]) -> [u8; 3] {
    let mut code: u32 = 0;
    for &byte in &p {
        let sym = if byte == 0 {
            0
        } else {
            u32::from(byte - b'a' + 1)
        };
        code = code * 27 + sym;
    }
    [(code >> 16) as u8, (code >> 8) as u8, code as u8]
}

fn main() {
    let src = fs::read_to_string("src/wordlist.rs").expect("read src/wordlist.rs");

    let mut words: Vec<String> = Vec::with_capacity(2048);
    for line in src.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix('"') else {
            continue;
        };
        let Some(end) = rest.find('"') else {
            continue;
        };
        let w = &rest[..end];
        if !w.is_empty() && w.bytes().all(|b| b.is_ascii_lowercase()) {
            words.push(w.to_owned());
        }
    }
    assert_eq!(
        words.len(),
        2048,
        "wordlist.rs must contain exactly 2048 string literals, got {}",
        words.len()
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("wordlist_prefix5.rs");
    let mut f = fs::File::create(&out_path).expect("create wordlist_prefix5.rs");

    writeln!(
        f,
        "// Auto-generated by bip39/build.rs from src/wordlist.rs. Do not edit by hand."
    )
    .unwrap();
    writeln!(
        f,
        "/// Base-27-packed 5-char zero-padded prefix for every BIP-39 English word."
    )
    .unwrap();
    writeln!(f, "///").unwrap();
    writeln!(
        f,
        "/// Each entry packs a 5-character prefix (padding = 0, `a`..=`z` = 1..=26) as a"
    )
    .unwrap();
    writeln!(
        f,
        "/// base-27 integer (max `27^5 - 1 = 14_348_906 < 2^24`) into 3 big-endian bytes."
    )
    .unwrap();
    writeln!(
        f,
        "/// `sphincs_tz_bip39::word_prefix_at` decodes it back to the exact 5 bytes, so the"
    )
    .unwrap();
    writeln!(
        f,
        "/// rendered fingerprint is byte-identical to the former `[[u8; 5]; 2048]` table at"
    )
    .unwrap();
    writeln!(
        f,
        "/// 6 KB instead of 10 KB. The packing is a lossless bijection on `{{0, a..=z}}^5`,"
    )
    .unwrap();
    writeln!(
        f,
        "/// so BIP-39's unique-4-char-prefix guarantee is preserved."
    )
    .unwrap();
    writeln!(f, "pub static WORDLIST_PREFIX5_PACKED: [[u8; 3]; 2048] = [").unwrap();
    for w in &words {
        let b = w.as_bytes();
        let p: [u8; 5] = [
            b.first().copied().unwrap_or(0),
            b.get(1).copied().unwrap_or(0),
            b.get(2).copied().unwrap_or(0),
            b.get(3).copied().unwrap_or(0),
            b.get(4).copied().unwrap_or(0),
        ];
        let packed = pack_prefix5(p);
        writeln!(
            f,
            "    [{}, {}, {}], // {}",
            packed[0], packed[1], packed[2], w
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();

    println!("cargo:rerun-if-changed=src/wordlist.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
