//! Generates `WORDLIST_PREFIX5` at compile time from `src/wordlist.rs`.
//!
//! The full BIP-39 English wordlist (`WORDLIST`) costs ~18 KB of rodata
//! once expanded into the fixed-stride `WORDLIST_FLAT` + `WORDLIST_LENS`
//! tables that the constant-time scans need. The FSBL's 32 KB flash
//! ceiling can't afford that — but it still needs to render the 8 BIP-39
//! measurement words on the OLED before branching into the slot. The
//! compact 5-byte prefix table here (~10 KB) is the FSBL's whole wordlist.
//!
//! BIP-39 guarantees every English word has a unique 4-character prefix,
//! so 5 bytes round-trip back to a full word deterministically. The
//! existing `secure/src/measured_boot.rs` already truncates words to ≤ 6
//! visible chars on the 16-column OLED, so a 5-char prefix is visually
//! identical to today's display.
//!
//! See the prefix5-roundtrip integration test in `bip39/tests/` for the
//! invariant this generator must uphold.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let src = fs::read_to_string("src/wordlist.rs").expect("read src/wordlist.rs");

    let mut words: Vec<String> = Vec::with_capacity(2048);
    for line in src.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix('"') else {
            continue;
        };
        let Some(end) = rest.find('"') else {
            continue;
        };
        let w = &rest[..end];
        if !w.is_empty() && w.bytes().all(|b| b.is_ascii_lowercase()) {
            words.push(w.to_owned());
        }
    }
    assert_eq!(
        words.len(),
        2048,
        "wordlist.rs must contain exactly 2048 string literals, got {}",
        words.len()
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("wordlist_prefix5.rs");
    let mut f = fs::File::create(&out_path).expect("create wordlist_prefix5.rs");

    writeln!(
        f,
        "// Auto-generated by bip39/build.rs from src/wordlist.rs. Do not edit by hand."
    )
    .unwrap();
    writeln!(
        f,
        "/// Compact 5-byte zero-padded prefix for every BIP-39 English wordlist entry."
    )
    .unwrap();
    writeln!(f, "///").unwrap();
    writeln!(
        f,
        "/// BIP-39 guarantees the first 4 chars are unique; the 5th is a sanity buffer"
    )
    .unwrap();
    writeln!(
        f,
        "/// for the firmware-measurement OLED display in the FSBL."
    )
    .unwrap();
    writeln!(
        f,
        "pub static WORDLIST_PREFIX5: [[u8; 5]; 2048] = ["
    )
    .unwrap();
    for w in &words {
        let b = w.as_bytes();
        let p: [u8; 5] = [
            b.first().copied().unwrap_or(0),
            b.get(1).copied().unwrap_or(0),
            b.get(2).copied().unwrap_or(0),
            b.get(3).copied().unwrap_or(0),
            b.get(4).copied().unwrap_or(0),
        ];
        writeln!(
            f,
            "    [{}, {}, {}, {}, {}], // {}",
            p[0], p[1], p[2], p[3], p[4], w
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();

    println!("cargo:rerun-if-changed=src/wordlist.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
