-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx]: function definitions
import Aeneas
import Extracted.TxMerkle.Types
import Extracted.TxMerkle.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pqsigner_tx

/-- Trait implementation: [core::array::equality::{impl core::cmp::PartialEq<[U; N]> for [T; N]}]
    Source: '/rustc/library/core/src/array/equality.rs', lines 5:0-7:28
    Name pattern: [core::cmp::PartialEq<[@T; @N], [@U; @N]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<[@T; @N], [@U; @N]>"]
def Array.Insts.CoreCmpPartialEqArray {T : Type} {U : Type} (N : Std.Usize)
  (cmpPartialEqInst : core.cmp.PartialEq T U) : core.cmp.PartialEq (Array T N)
  (Array U N) := {
  eq := core.array.equality.PartialEqArray.eq cmpPartialEqInst
}

/-- [pqsigner_tx::erc20::merkle::verify_proof]: loop body 0:
    Source: 'tx/src/erc20/merkle.rs', lines 51:4-69:1
    Visibility: public -/
@[rust_loop_body]
def erc20.merkle.verify_proof_loop.body
  (proof_bytes : Slice Std.U8) (expected_root : Array Std.U8 32#usize)
  (iter : core.ops.range.Range Std.Usize) (h : Array Std.U8 32#usize)
  (idx : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U8
    32#usize) × Std.Usize) Bool)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none =>
    let b ←
      core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 h
        expected_root
    ok (done b)
  | some level =>
    let sib_off ← level * 32#usize
    let i ← sib_off + 32#usize
    let s ←
      core.slice.index.Slice.index (core.slice.index.SliceIndexRangeUsizeSlice
        Std.U8) proof_bytes { start := sib_off, «end» := i }
    let r ← core.array.TryFromSharedArraySlice.try_from 32#usize s
    match r with
    | core.result.Result.Ok arr =>
      let i1 ← lift (idx &&& 1#usize)
      let h1 ←
        if i1 = 0#usize
        then erc20.merkle.node_hash h arr
        else erc20.merkle.node_hash arr h
      let idx1 ← idx >>> 1#i32
      ok (cont (iter1, h1, idx1))
    | core.result.Result.Err _ => ok (done false)

/-- [pqsigner_tx::erc20::merkle::verify_proof]: loop 0:
    Source: 'tx/src/erc20/merkle.rs', lines 51:4-69:1
    Visibility: public -/
@[rust_loop]
def erc20.merkle.verify_proof_loop
  (iter : core.ops.range.Range Std.Usize) (proof_bytes : Slice Std.U8)
  (expected_root : Array Std.U8 32#usize) (h : Array Std.U8 32#usize)
  (idx : Std.Usize) :
  Result Bool
  := do
  loop
    (fun (iter1, h1, idx1) => erc20.merkle.verify_proof_loop.body proof_bytes
      expected_root iter1 h1 idx1)
    (iter, h, idx)

/-- [pqsigner_tx::erc20::merkle::verify_proof]:
    Source: 'tx/src/erc20/merkle.rs', lines 34:0-69:1
    Visibility: public -/
def erc20.merkle.verify_proof
  (canonical : Slice Std.U8) (leaf_index : Std.Usize)
  (proof_bytes : Slice Std.U8) (proof_depth : Std.Usize)
  (expected_root : Array Std.U8 32#usize) :
  Result Bool
  := do
  let i := Slice.len proof_bytes
  let i1 ← proof_depth * 32#usize
  if i != i1
  then ok false
  else
    let h ← erc20.merkle.leaf_hash canonical
    erc20.merkle.verify_proof_loop { start := 0#usize, «end» := proof_depth }
      proof_bytes expected_root h leaf_index

end pqsigner_tx
