/- §33 — `div10_inplace` functional correctness over the committed Aeneas
   extraction (`Extracted/FormatDecimal/Funs.lean`, regenerated by
   `make extract-format-decimal`).

   THE RESULT: `div10_inplace` computes floor-division by 10 in place for ALL
   2^256 values — post-state = ⌊pre/10⌋ (as a 256-bit BE nat), returned byte =
   pre mod 10. This is the symbolic-VALUE ∀ that CBMC/Kani could NOT close
   (the byte-wise long division swamps bit-blasting at every tried bound down
   to 2^16 — see the note on `format_decimal_panic_free_over_format_shapes`
   in tx-core/src/eip1559.rs); deductive loop-induction closes it the same way
   A3.1's interpreter-refinement closed the digit-explosion.

   Proof pattern: `U256MulSpec.saturating_mul_u64_loop_value`
   (`loop.spec_decr_nat` + a beValue invariant), with an MS-first `take`
   prefix instead of U256Mul's LS-first `drop` — the invariant is the
   long-division identity
       beValue (v0.take k) = beValue (quotient.take k) * 10 + rem_k
   plus an untouched-suffix conjunct (the array is mutated in place).

   NOTE (axiom discipline): the shift-or bit step (`(rem <<< 8) ||| byte`)
   is closed manually via `UScalar.val_or` + `Nat.two_pow_add_eq_or_of_lt`.
   `bv_tac` also closes it but drags a `bv_decide` native axiom into the
   closure, which the §33 gate rejects — do not "simplify" back to it.

   First milestone of the format_decimal end-to-end WYSIWYS spec (work-todo
   FV frontier, Track 1): next are extract_digits / round_carry / trim / emit,
   composing to "the emitted string parses back to round-half-up(v/10^d, f)".
-/
import Aeneas
import Extracted.FormatDecimal.Funs
import Extracted.RlpIntSpec
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

namespace Div10Spec

open Extracted.Equiv  -- beValue and lemmas from RlpIntSpec
open pqsigner_tx_core

/-- take (n+1) as take n ++ [l[n]] — helper for the appending-Horner step. -/
theorem take_succ_getElem! (l : List Std.U8) (n : Nat) (h : n < l.length) :
    l.take (n + 1) = l.take n ++ [l[n]!] := by
  rw [getElem!_pos l n h]
  exact List.take_succ_eq_append_getElem h

set_option maxHeartbeats 4000000 in
/-- Long-division loop invariant, MS-first: after processing the prefix
    [0, start), the ORIGINAL prefix value equals (quotient prefix)·10 + rem,
    and the suffix is untouched. Ghost `v0` = the original byte list. -/
theorem div10_inplace_loop_spec
    (iter : core.ops.range.Range Std.Usize) (v0 : List Std.U8)
    (v : Std.Array Std.U8 32#usize) (rem : Std.U16)
    (hend : iter.«end».val = 32) (hle : iter.start.val ≤ 32)
    (hlen0 : v0.length = 32)
    (hrem : rem.val < 10)
    (hsuff : v.val.drop iter.start.val = v0.drop iter.start.val)
    (hinv : beValue (v0.take iter.start.val)
            = beValue (v.val.take iter.start.val) * 10 + rem.val) :
    eip1559.div10_inplace_loop iter v rem
      ⦃ p => beValue v0 = beValue p.1.val * 10 + p.2.val ∧ p.2.val < 10 ⦄ := by
  unfold eip1559.div10_inplace_loop
  apply Aeneas.Std.loop.spec_decr_nat
    (measure := fun (s : core.ops.range.Range Std.Usize ×
                      Std.Array Std.U8 32#usize × Std.U16) =>
       s.1.«end».val - s.1.start.val)
    (inv := fun (s : core.ops.range.Range Std.Usize ×
                     Std.Array Std.U8 32#usize × Std.U16) =>
       s.1.«end».val = 32 ∧ s.1.start.val ≤ 32 ∧
       s.2.2.val < 10 ∧
       s.2.1.val.drop s.1.start.val = v0.drop s.1.start.val ∧
       beValue (v0.take s.1.start.val)
         = beValue (s.2.1.val.take s.1.start.val) * 10 + s.2.2.val)
  · rintro ⟨it, arr, r⟩ ⟨hbnd, hsle, hrlt, hdrop, hval⟩
    simp only at hbnd hsle hrlt hdrop hval
    unfold eip1559.div10_inplace_loop.body
    simp only [lift]
    let* ⟨ob, iter1, hpost⟩ ← next_usize_spec it
    rcases hpost with ⟨ho, hge⟩ | ⟨i, it', heq, hi, hlt, hend', hstart'⟩
    · -- loop done: start = 32, take 32 = whole list
      subst ho
      simp only [WP.spec_ok]
      have h32 : it.start.val = 32 := by omega
      rw [h32] at hval
      have hlena : (arr : Std.Array Std.U8 32#usize).val.length = 32 := by
        have := (arr : Std.Array Std.U8 32#usize).property; simpa using this
      rw [List.take_of_length_le (by omega), List.take_of_length_le (by omega)] at hval
      exact ⟨hval, hrlt⟩
    · simp only [Prod.mk.injEq] at heq
      obtain ⟨rfl, rfl⟩ := heq
      subst hi
      have hi31 : it.start.val ≤ 31 := by omega
      have hlena : (arr : Std.Array Std.U8 32#usize).val.length = 32 := by
        have := (arr : Std.Array Std.U8 32#usize).property; simpa using this
      step* <;> first | scalar_tac | skip
      -- value facts -----------------------------------------------------
      have hb : i2.val < 256 := by
        have := i2.hBounds; simp [Std.U8.size] at this; omega
      have hcast : (UScalar.cast UScalarTy.U16 i2).val = i2.val := by scalar_tac
      have hi1v : i1.val = r.val * 256 := by
        rw [i1_post1, Nat.shiftLeft_eq]
        have hlt : r.val * 2 ^ 8 < U16.size := by scalar_tac
        rw [Nat.mod_eq_of_lt hlt]
        norm_num
      have hacc : (i1 ||| UScalar.cast UScalarTy.U16 i2).val
          = r.val * 256 + i2.val := by
        rw [UScalar.val_or, hcast, hi1v,
            show r.val * 256 = 2 ^ 8 * r.val by ring,
            ← Nat.two_pow_add_eq_or_of_lt (by omega : i2.val < 2 ^ 8)]
      have haccb : (i1 ||| UScalar.cast UScalarTy.U16 i2).val < 2560 := by omega
      have hi4 : i4.val = (r.val * 256 + i2.val) / 10 := by
        rw [i4_post, hacc]
      have hi5 : (UScalar.cast UScalarTy.U8 i4).val = i4.val := by
        rw [UScalar.cast_val_eq]
        simp only [UScalarTy.numBits]
        omega
      have hrem1 : rem1.val = (r.val * 256 + i2.val) % 10 := by
        rw [rem1_post, hacc]
      -- the byte read is the ORIGINAL byte (suffix untouched) -------------
      have hv0i : i2.val = (v0[it.start.val]!).val := by
        rw [i2_post]
        have h1 : (arr : Std.Array Std.U8 32#usize).val[it.start.val]!
            = v0[it.start.val]! := by
          have h0 : ((arr : Std.Array Std.U8 32#usize).val.drop it.start.val)[0]!
              = (v0.drop it.start.val)[0]! := by rw [hdrop]
          rwa [List.getElem!_drop, List.getElem!_drop, Nat.add_zero] at h0
        rw [← getElem!_pos _ _ (by rw [hlena]; omega), h1]
      -- structural rewrites ----------------------------------------------
      have hsetlen : ((arr : Std.Array Std.U8 32#usize).val.set it.start.val
          (UScalar.cast UScalarTy.U8 i4)).length = 32 := by
        simp [List.length_set, hlena]
      -- new suffix untouched: drop (i+1) (set i _) = drop (i+1) = v0.drop (i+1)
      have hdrop1 : (a : Std.Array Std.U8 32#usize).val.drop (it.start.val + 1)
          = v0.drop (it.start.val + 1) := by
        rw [a_post, Array.set_val_eq]
        have h1 : ((arr : Std.Array Std.U8 32#usize).val.set it.start.val
            (UScalar.cast UScalarTy.U8 i4)).drop (it.start.val + 1)
            = (arr : Std.Array Std.U8 32#usize).val.drop (it.start.val + 1) := by
          apply List.drop_set_of_lt
          omega
        rw [h1]
        have h2 := congrArg (List.drop 1) hdrop
        rwa [List.drop_drop, List.drop_drop] at h2
      -- new quotient prefix: take (i+1) (set i q) = take i ++ [q]
      have htake1 : (a : Std.Array Std.U8 32#usize).val.take (it.start.val + 1)
          = (arr : Std.Array Std.U8 32#usize).val.take it.start.val
            ++ [UScalar.cast UScalarTy.U8 i4] := by
        rw [a_post, Array.set_val_eq]
        rw [take_succ_getElem! _ _ (by rw [hsetlen]; omega)]
        congr 1
        · apply List.take_set_of_le
          omega
        · rw [List.set_getElem!_eq _ _ _ _ ⟨by rw [hlena]; omega, rfl⟩]
      -- original prefix: take (i+1) v0 = take i v0 ++ [v0[i]]
      have htake0 : v0.take (it.start.val + 1)
          = v0.take it.start.val ++ [v0[it.start.val]!] :=
        take_succ_getElem! _ _ (by omega)
      have hend1 : iter1.«end».val = 32 := by rw [hend']; exact hbnd
      refine ⟨hend1, by omega, by omega, ?_, ?_, by omega⟩
      · simp only [hstart']
        exact hdrop1
      · simp only [hstart']
        rw [htake0, htake1, beValue_append_byte, beValue_append_byte]
        rw [hi5, hi4, hrem1, ← hv0i]
        -- linear arithmetic: all multipliers/divisors are literals
        omega
  · exact ⟨hend, hle, hrem, hsuff, hinv⟩

/-- **Functional spec**: `div10_inplace` computes floor-division by 10 in
    place — the post-state array is `⌊pre/10⌋` (as a 256-bit BE nat) and the
    returned byte is `pre mod 10`. This is the symbolic-VALUE ∀ that CBMC
    could not close. -/
theorem div10_inplace_spec (v : Std.Array Std.U8 32#usize) :
    eip1559.div10_inplace v
      ⦃ p => beValue p.2.val = beValue v.val / 10 ∧
             p.1.val = beValue v.val % 10 ⦄ := by
  unfold eip1559.div10_inplace
  have hlen : v.val.length = 32 := by
    have := v.property; simpa using this
  let* ⟨p, hp1, hp2⟩ ← div10_inplace_loop_spec
        { start := 0#usize, «end» := 32#usize } v.val v 0#u16
        rfl (by simp) hlen (by simp) (by simp) (by simp [beValue])
  step*
  have hlt10 : hp1.val < 10 := by assumption
  have hiv : i.val = hp1.val % 2 ^ 8 := by
    rw [i_post, UScalar.cast_val_eq]
    simp [UScalarTy.numBits]
  refine ⟨by omega, by omega⟩

end Div10Spec
