/- §33 — format_decimal Track-1 M6b: `fmt_emit` functional correctness over
   the committed Aeneas extraction (`Extracted/FormatDecimal/Funs.lean`,
   regenerated by `make extract-format-decimal`).

   THE RESULT (`emit_spec`): under the extract/round post-state digit bounds
   (n ≤ 80, every stored byte ≤ 9 — needed so the `b'0' + d` ASCII adds
   cannot overflow) and `frac_emit ≤ 255` (its u8 provenance in
   `format_decimal`; headroom for the `need` width additions),
   `fmt_emit digits n total_decimals frac_emit out` succeeds and, with
   `need = needN n td fe` and `emitBytes` the spec-side expected byte string:

     (a) NONE case (`out.length < need`): the result is LITERALLY
         `(none, out)` — the would-not-fit path returns before any write,
         the output slice is returned unchanged (the doc-comment claim);
     (b) SOME case (`need ≤ out.length`): result = `(some w, out')` with
         `w = need`, `out'.take need = emitBytes digits n td fe`,
         `out'.drop need = out.drop need` (untouched tail), and
         `out'.length = out.length`;
     (c) M7-facing corollaries on the PURE `emitBytes` string:
         `emitBytes_length` (= needN), `emitBytes_ascii` (every byte is an
         ASCII digit or '.'), `emitBytes_dot_iff` ('.' appears exactly at
         index `intEmitN n td`, and only when `fe ≠ 0` — hence at most one),
         `emitBytes_head_digit` (the integer part is nonempty: byte 0 is a
         digit, never the '.'), `emitBytes_no_leading_zero` (when the digits
         satisfy the extract_digits/round no-leading-zero post
         `digits[n-1] ≠ 0` and `td < n`, byte 0 is not '0' — the single
         legitimate leading '0' is the `n ≤ td` "0.xxx" shape, whose integer
         part is exactly ["0"]).

   `emitBytes = intPart ++ (if fe ≠ 0 then '.' :: fracPart else [])`:
   intPart is `["0"]` when `n ≤ td`, else the MS-first ASCII of
   `digits[td..n)` (index `td + (n-td) - 1 - j = n - 1 - j`); fracPart reads
   fractional positions 1..fe through `TrimFracSpec.fracDigitVal` (REUSED —
   the same guarded `digits[td-pos]` read with structural zeros, so M7 can
   splice trim's post directly into emit's).

   `fmt_emit` writes into `&mut [u8]`, modeled as `Slice Std.U8`: loops 0/2
   (fractional writes after a "0" resp. a real integer part — bodies are
   syntactically IDENTICAL, `fmt_emit_loop0_eq_loop2` bridges them by `rfl`
   so the frac loop lemma is proven ONCE) and loop 1 (integer digits,
   MS-first). Proof pattern per sibling notes: `loop.spec_decr_nat` with a
   written-window/frame/length invariant over ghost entry state `(out0, w0)`;
   `Slice.update` steps leave the `w < len` bound as leading goals.

   NOTE (axiom discipline): no `bv_tac` (`bv_decide` would inject a
   native-computation axiom the §33 gate rejects) — closure is exactly
   [propext, Classical.choice, Quot.sound].

   Fifth milestone of the format_decimal end-to-end WYSIWYS spec (work-todo
   FV frontier, Track 1): M7 composes extract/round/trim/emit into "the
   emitted string parses back to round-half-up(v/10^d, f)". -/
import Aeneas
import Extracted.FormatDecimal.Funs
import Extracted.FormatDecimal.Div10Spec
import Extracted.FormatDecimal.TrimFracSpec
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

namespace EmitSpec

open Extracted.Equiv  -- next_usize_spec (via the Div10Spec → RlpIntSpec chain)
open pqsigner_tx_core
open TrimFracSpec     -- fracDigitVal (REUSED), saturating_sub_spec

/-! ### Spec-side expected byte string -/

/-- ASCII byte of a decimal digit value (total: mod-10 guard; every call
    site passes d ≤ 9, where `asciiByte d = 48 + d`). -/
def asciiByte (d : Nat) : Std.U8 :=
  U8.ofNatCore (48 + d % 10) (by
    have h : d % 10 < 10 := Nat.mod_lt d (by decide)
    simp only [UScalarTy.numBits]
    omega)

@[simp] theorem asciiByte_val (d : Nat) : (asciiByte d).val = 48 + d % 10 := by
  simp [asciiByte, U8.ofNatCore, UScalar.ofNatCore_val_eq]

theorem asciiByte_val_of_le {d : Nat} (h : d ≤ 9) :
    (asciiByte d).val = 48 + d := by
  rw [asciiByte_val, Nat.mod_eq_of_lt (by omega)]

/-- Emitted integer-part width: `max(int_digits, 1)` where
    `int_digits = n - td` (Nat subtraction saturates like the Rust if). -/
def intEmitN (n td : Nat) : Nat := if n ≤ td then 1 else n - td

/-- Required output width (the value `fmt_emit` returns as `Some`). -/
def needN (n td fe : Nat) : Nat :=
  intEmitN n td + (if fe = 0 then 0 else 1 + fe)

theorem intEmitN_pos (n td : Nat) : 0 < intEmitN n td := by
  simp only [intEmitN]; split <;> omega

theorem needN_pos (n td fe : Nat) : 0 < needN n td fe := by
  have := intEmitN_pos n td
  simp only [needN]; omega

/-- Integer part: "0" when the value has no integer digits, else the
    MS-first ASCII of `digits[td..n)` (`td + (n-td) - 1 - j = n - 1 - j`). -/
def intBytes (l : List Std.U8) (n td : Nat) : List Std.U8 :=
  if n ≤ td then [asciiByte 0]
  else (List.range (n - td)).map fun j => asciiByte (l[n - 1 - j]!).val

/-- Fractional part: ASCII of the guarded `fracDigitVal` reads at positions
    1..fe (MS-first from the decimal point). -/
def fracBytes (l : List Std.U8) (n td fe : Nat) : List Std.U8 :=
  (List.range fe).map fun p => asciiByte (fracDigitVal l n td (p + 1))

/-- The full expected byte string. -/
def emitBytes (l : List Std.U8) (n td fe : Nat) : List Std.U8 :=
  intBytes l n td ++ (if fe = 0 then [] else 46#u8 :: fracBytes l n td fe)

@[simp] theorem intBytes_length (l : List Std.U8) (n td : Nat) :
    (intBytes l n td).length = intEmitN n td := by
  simp only [intBytes, intEmitN]
  split <;> simp

@[simp] theorem fracBytes_length (l : List Std.U8) (n td fe : Nat) :
    (fracBytes l n td fe).length = fe := by
  simp [fracBytes]

@[simp] theorem emitBytes_length (l : List Std.U8) (n td fe : Nat) :
    (emitBytes l n td fe).length = needN n td fe := by
  simp only [emitBytes, needN, List.length_append, intBytes_length]
  split <;> simp [Nat.add_comm]

/-! ### Index characterization of `emitBytes` -/

theorem intBytes_getElem!_of_le (l : List Std.U8) (n td : Nat) (hle : n ≤ td) :
    (intBytes l n td)[0]! = asciiByte 0 := by
  simp [intBytes, hle]

theorem intBytes_getElem!_of_gt (l : List Std.U8) (n td j : Nat)
    (hgt : td < n) (hj : j < n - td) :
    (intBytes l n td)[j]! = asciiByte (l[n - 1 - j]!).val := by
  have hne : ¬ n ≤ td := by omega
  simp only [intBytes, if_neg hne]
  rw [List.getElem!_map_eq _ _ _ (by simpa using hj),
      List.getElem!_range, if_pos hj]

theorem fracBytes_getElem! (l : List Std.U8) (n td fe p : Nat) (hp : p < fe) :
    (fracBytes l n td fe)[p]! = asciiByte (fracDigitVal l n td (p + 1)) := by
  simp only [fracBytes]
  rw [List.getElem!_map_eq _ _ _ (by simp [hp]),
      List.getElem!_range, if_pos hp]

theorem emitBytes_getElem!_int (l : List Std.U8) (n td fe j : Nat)
    (hj : j < intEmitN n td) :
    (emitBytes l n td fe)[j]! = (intBytes l n td)[j]! := by
  simp only [emitBytes]
  rw [List.getElem!_append_left _ _ _ (by simp [hj])]

theorem emitBytes_getElem!_dot (l : List Std.U8) (n td fe : Nat)
    (hfe : fe ≠ 0) :
    (emitBytes l n td fe)[intEmitN n td]! = 46#u8 := by
  simp only [emitBytes, if_neg hfe]
  rw [List.getElem!_append_right _ _ _ (by simp)]
  simp

theorem emitBytes_getElem!_frac (l : List Std.U8) (n td fe p : Nat)
    (hfe : fe ≠ 0) (hp : p < fe) :
    (emitBytes l n td fe)[intEmitN n td + 1 + p]!
      = asciiByte (fracDigitVal l n td (p + 1)) := by
  simp only [emitBytes, if_neg hfe]
  rw [List.getElem!_append_right _ _ _ (by simp; omega)]
  have hidx : intEmitN n td + 1 + p - (intBytes l n td).length = p + 1 := by
    simp; omega
  rw [hidx, List.getElem!_cons_succ]
  exact fracBytes_getElem! l n td fe p hp

/-! ### M7-facing well-formedness corollaries (c) -/

/-- Every byte of `emitBytes` is an ASCII digit ('0'..'9') or the '.' — the
    rendered string is a well-formed decimal numeral. -/
theorem emitBytes_ascii (l : List Std.U8) (n td fe : Nat) (i : Nat)
    (hi : i < (emitBytes l n td fe).length) :
    (48 ≤ ((emitBytes l n td fe)[i]!).val ∧
     ((emitBytes l n td fe)[i]!).val ≤ 57) ∨
    ((emitBytes l n td fe)[i]!).val = 46 := by
  rw [emitBytes_length] at hi
  simp only [needN] at hi
  rcases Nat.lt_or_ge i (intEmitN n td) with hint | hint
  · left
    rw [emitBytes_getElem!_int l n td fe i hint]
    simp only [intEmitN] at hint
    by_cases hle : n ≤ td
    · rw [if_pos hle] at hint
      have : i = 0 := by omega
      subst this
      rw [intBytes_getElem!_of_le l n td hle, asciiByte_val]
      omega
    · rw [if_neg hle] at hint
      rw [intBytes_getElem!_of_gt l n td i (by omega) hint, asciiByte_val]
      have : (l[n - 1 - i]!).val % 10 < 10 := Nat.mod_lt _ (by decide)
      omega
  · have hfe : fe ≠ 0 := by
      intro h0; rw [if_pos h0] at hi; omega
    rw [if_neg hfe] at hi
    rcases Nat.eq_or_lt_of_le hint with heq | hlt
    · right
      rw [← heq, emitBytes_getElem!_dot l n td fe hfe]
      decide
    · left
      have hp : i - intEmitN n td - 1 < fe := by omega
      have hidx : i = intEmitN n td + 1 + (i - intEmitN n td - 1) := by omega
      rw [hidx, emitBytes_getElem!_frac l n td fe _ hfe hp, asciiByte_val]
      have : fracDigitVal l n td (i - intEmitN n td - 1 + 1) % 10 < 10 :=
        Nat.mod_lt _ (by decide)
      omega

/-- The '.' appears at index `intEmitN n td` and nowhere else (and only when
    `fe ≠ 0`) — in particular there is AT MOST ONE '.'. -/
theorem emitBytes_dot_iff (l : List Std.U8) (n td fe : Nat) (i : Nat)
    (hi : i < (emitBytes l n td fe).length) :
    ((emitBytes l n td fe)[i]!).val = 46 ↔ (fe ≠ 0 ∧ i = intEmitN n td) := by
  rw [emitBytes_length] at hi
  simp only [needN] at hi
  constructor
  · intro hdot
    rcases Nat.lt_or_ge i (intEmitN n td) with hint | hint
    · exfalso
      rw [emitBytes_getElem!_int l n td fe i hint] at hdot
      simp only [intEmitN] at hint
      by_cases hle : n ≤ td
      · rw [if_pos hle] at hint
        have : i = 0 := by omega
        subst this
        rw [intBytes_getElem!_of_le l n td hle, asciiByte_val] at hdot
        omega
      · rw [if_neg hle] at hint
        rw [intBytes_getElem!_of_gt l n td i (by omega) hint,
            asciiByte_val] at hdot
        omega
    · have hfe : fe ≠ 0 := by
        intro h0; rw [if_pos h0] at hi; omega
      refine ⟨hfe, ?_⟩
      rcases Nat.eq_or_lt_of_le hint with heq | hlt
      · omega
      · exfalso
        rw [if_neg hfe] at hi
        have hp : i - intEmitN n td - 1 < fe := by omega
        have hidx : i = intEmitN n td + 1 + (i - intEmitN n td - 1) := by omega
        rw [hidx, emitBytes_getElem!_frac l n td fe _ hfe hp,
            asciiByte_val] at hdot
        omega
  · rintro ⟨hfe, rfl⟩
    rw [emitBytes_getElem!_dot l n td fe hfe]
    decide

/-- The integer part is nonempty: byte 0 exists and is an ASCII DIGIT
    (never the '.'). -/
theorem emitBytes_head_digit (l : List Std.U8) (n td fe : Nat) :
    48 ≤ ((emitBytes l n td fe)[0]!).val ∧
    ((emitBytes l n td fe)[0]!).val ≤ 57 := by
  have h0 : (0 : Nat) < intEmitN n td := intEmitN_pos n td
  rw [emitBytes_getElem!_int l n td fe 0 h0]
  simp only [intEmitN] at h0 ⊢
  by_cases hle : n ≤ td
  · rw [intBytes_getElem!_of_le l n td hle, asciiByte_val]
    omega
  · rw [intBytes_getElem!_of_gt l n td 0 (by omega) (by rw [if_neg hle] at h0; omega),
        asciiByte_val]
    have : (l[n - 1 - 0]!).val % 10 < 10 := Nat.mod_lt _ (by decide)
    omega

/-- No spurious leading zero: when the value HAS integer digits (`td < n`)
    and the digits satisfy the extract_digits/round no-leading-zero post
    (`digits[n-1] ≠ 0`, digit values ≤ 9), the first emitted byte is not
    '0'. (The `n ≤ td` shape renders exactly "0.…" — a single legitimate
    zero, covered by `emitBytes_head_digit` + `intBytes_getElem!_of_le`.) -/
theorem emitBytes_no_leading_zero (l : List Std.U8) (n td fe : Nat)
    (hgt : td < n) (htop9 : (l[n - 1]!).val ≤ 9)
    (htop : (l[n - 1]!).val ≠ 0) :
    ((emitBytes l n td fe)[0]!).val ≠ 48 := by
  have h0 : (0 : Nat) < intEmitN n td := intEmitN_pos n td
  have h00 : n - 1 - 0 = n - 1 := by omega
  rw [emitBytes_getElem!_int l n td fe 0 h0,
      intBytes_getElem!_of_gt l n td 0 hgt (by omega), h00,
      asciiByte_val_of_le htop9]
  omega

/-! ### take/drop assembly bridges (pointwise → segment equality) -/

theorem take_eq_of_getElem! {α} [Inhabited α] {l1 l2 : List α} {k : Nat}
    (hk : k ≤ l1.length) (hl2 : l2.length = k)
    (h : ∀ i, i < k → l1[i]! = l2[i]!) : l1.take k = l2 := by
  apply List.ext_getElem (by simp [hl2]; omega)
  intro i h1 h2
  have hik : i < k := by simp at h1; omega
  rw [List.Inhabited_getElem_eq_getElem! (l1.take k) i h1,
      List.Inhabited_getElem_eq_getElem! l2 i h2,
      List.getElem!_take_of_lt _ _ _ hik]
  exact h i hik

theorem drop_eq_of_getElem! {α} [Inhabited α] {l1 l2 : List α} {k : Nat}
    (hlen : l1.length = l2.length)
    (h : ∀ i, k ≤ i → i < l1.length → l1[i]! = l2[i]!) :
    l1.drop k = l2.drop k := by
  apply List.ext_getElem (by simp [hlen])
  intro i h1 h2
  rw [List.Inhabited_getElem_eq_getElem! (l1.drop k) i h1,
      List.Inhabited_getElem_eq_getElem! (l2.drop k) i h2,
      List.getElem!_drop, List.getElem!_drop]
  exact h (k + i) (by omega) (by simp at h1; omega)

/-! ### Loop lemmas -/

/-- Loops 0 and 2 are the SAME function — Aeneas emitted the fractional
    write loop twice, once per call site (`int_digits = 0` / `≠ 0`); the
    definitions are syntactically identical, so the frac-loop lemma is
    proven once (for loop 2) and transported by `rfl`. -/
theorem fmt_emit_loop0_eq_loop2 :
    eip1559.fmt_emit_loop0 = eip1559.fmt_emit_loop2 := rfl

set_option maxHeartbeats 4000000 in
/-- Fractional-write loop (loop 2 = loop 0): with write head
    `w = w0 + iter.start`, the loop ASCII-writes the guarded fractional
    digits (positions iter.start+1..fe, MS-first) into
    `out[w0+iter.start, w0+fe)`, leaves everything outside `[w0, w0+fe)`
    untouched relative to the ghost entry state `out0`, preserves the
    length, and returns the write head at `w0 + fe`. -/
theorem emit_frac_loop_spec
    (digits : Std.Array Std.U8 80#usize) (n td fe : Std.Usize)
    (out0 : Slice Std.U8) (w0 : Std.Usize)
    (iter : core.ops.range.Range Std.Usize) (out : Slice Std.U8)
    (w : Std.Usize)
    (hn80 : n.val ≤ 80)
    (hdig : ∀ i, i < 80 → (digits.val[i]!).val ≤ 9)
    (hwin : w0.val + fe.val ≤ out0.length)
    (hend : iter.«end» = fe) (hstart : iter.start.val ≤ fe.val)
    (hw : w.val = w0.val + iter.start.val)
    (hlen : out.length = out0.length)
    (hframe : ∀ i, i < out0.length →
       (i < w0.val ∨ w0.val + iter.start.val ≤ i) →
       out.val[i]! = out0.val[i]!)
    (hwritten : ∀ p, p < iter.start.val →
       out.val[w0.val + p]!
         = asciiByte (fracDigitVal digits.val n.val td.val (p + 1))) :
    eip1559.fmt_emit_loop2 iter digits n td out w
      ⦃ r => r.2.val = w0.val + fe.val ∧
             r.1.length = out0.length ∧
             (∀ i, i < out0.length → (i < w0.val ∨ w0.val + fe.val ≤ i) →
                r.1.val[i]! = out0.val[i]!) ∧
             (∀ p, p < fe.val →
                r.1.val[w0.val + p]!
                  = asciiByte (fracDigitVal digits.val n.val td.val (p + 1))) ⦄ := by
  unfold eip1559.fmt_emit_loop2
  apply Aeneas.Std.loop.spec_decr_nat
    (measure := fun (s : core.ops.range.Range Std.Usize × (Slice Std.U8) ×
                      Std.Usize) => fe.val - s.1.start.val)
    (inv := fun (s : core.ops.range.Range Std.Usize × (Slice Std.U8) ×
                     Std.Usize) =>
       s.1.«end» = fe ∧ s.1.start.val ≤ fe.val ∧
       s.2.2.val = w0.val + s.1.start.val ∧
       s.2.1.length = out0.length ∧
       (∀ i, i < out0.length → (i < w0.val ∨ w0.val + s.1.start.val ≤ i) →
          s.2.1.val[i]! = out0.val[i]!) ∧
       (∀ p, p < s.1.start.val →
          s.2.1.val[w0.val + p]!
            = asciiByte (fracDigitVal digits.val n.val td.val (p + 1))))
  · rintro ⟨it, oo, ww⟩ ⟨hbnd, hsle, hwv, hlv, hfr, hwr⟩
    simp only at hbnd hsle hwv hlv hfr hwr
    have hlds : digits.val.length = 80 := by simp
    unfold eip1559.fmt_emit_loop2.body
    let* ⟨o, iter1, hpost⟩ ← next_usize_spec it
    rcases hpost with ⟨ho, hge⟩ | ⟨b, it', heq, hb, hlt, hend', hstart'⟩
    · -- iterator done: start = fe — the post is the invariant at the top
      subst ho
      simp only [WP.spec_ok]
      have hse : it.start.val = fe.val := by rw [hbnd] at hge; omega
      rw [hse] at hwv hfr hwr
      exact ⟨hwv, hlv, hfr, hwr⟩
    · simp only [Prod.mk.injEq] at heq
      obtain ⟨rfl, rfl⟩ := heq
      subst hb
      have hslt : it.start.val < fe.val := by rw [hbnd] at hlt; exact hlt
      have hwwlt : ww.val < oo.length := by rw [hlv]; omega
      step*
      -- stuck at the saturating_sub lift (no upstream @[step] lemma)
      let* ⟨digit_idx, hidx⟩ ← saturating_sub_spec
      split
      · -- td ≥ pos: the position is not finer than the value has decimals
        split
        · -- digit_idx < n: a real stored digit
          rename_i htdge hin
          have hdi80 : digit_idx.val < 80 := by scalar_tac
          step*
          · -- side condition: the ASCII add 48 + digit fits in u8
            have hx : x = digits.val[digit_idx.val]! := by
              rw [x_post, ← getElem!_pos _ _ (by rw [hlds]; omega)]
            have h9 : x.val ≤ 9 := by rw [hx]; exact hdig digit_idx.val hdi80
            scalar_tac
          · -- re-establish the invariant
            have hx : x = digits.val[digit_idx.val]! := by
              rw [x_post, ← getElem!_pos _ _ (by rw [hlds]; omega)]
            have h9 : x.val ≤ 9 := by rw [hx]; exact hdig digit_idx.val hdi80
            have hsval : (s : Slice Std.U8).val = oo.val.set ww.val i := by
              rw [s_post, Slice.set_val_eq]
            have hbyte : i = asciiByte
                (fracDigitVal digits.val n.val td.val (it.start.val + 1)) := by
              apply UScalar.eq_of_val_eq
              have hfv : fracDigitVal digits.val n.val td.val (it.start.val + 1)
                  = (digits.val[digit_idx.val]!).val := by
                simp only [fracDigitVal]
                rw [if_pos ⟨by scalar_tac, by scalar_tac⟩]
                have hie : td.val - (it.start.val + 1) = digit_idx.val := by
                  scalar_tac
                rw [hie]
              rw [i_post, hfv, asciiByte_val_of_le (by rw [← hx]; exact h9), hx]
            refine ⟨by rw [hend', hbnd], by omega, by omega, ?_, ?_, ?_, by omega⟩
            · rw [s_post]; simp [hlv]
            · intro i0 hi0 hcond
              rw [hsval,
                  List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega)]
              exact hfr i0 hi0 (by omega)
            · intro p hp
              rcases Nat.lt_or_ge p it.start.val with hplt | hpge
              · rw [hsval,
                    List.set_getElem!_ne _ _ _ _
                      (by simp only [Nat.not_eq]; omega)]
                exact hwr p hplt
              · have hpe : p = it.start.val := by omega
                subst hpe
                have hwidx : w0.val + it.start.val = ww.val := by omega
                rw [hsval, hwidx,
                    List.set_getElem!_eq _ _ _ _ ⟨by scalar_tac, rfl⟩]
                exact hbyte
        · -- digit_idx ≥ n: past the value's digits — structural zero
          rename_i htdge hnin
          step*
          have hsval : (s : Slice Std.U8).val = oo.val.set ww.val i := by
            rw [s_post, Slice.set_val_eq]
          have hbyte : i = asciiByte
              (fracDigitVal digits.val n.val td.val (it.start.val + 1)) := by
            apply UScalar.eq_of_val_eq
            have hfv : fracDigitVal digits.val n.val td.val (it.start.val + 1)
                = 0 := by
              simp only [fracDigitVal]
              rw [if_neg]
              intro hc
              have h1 : n.val ≤ digit_idx.val := by scalar_tac
              have h2 : digit_idx.val = td.val - (it.start.val + 1) := by
                scalar_tac
              omega
            rw [i_post, hfv]
            simp
          refine ⟨by rw [hend', hbnd], by omega, by omega, ?_, ?_, ?_, by omega⟩
          · rw [s_post]; simp [hlv]
          · intro i0 hi0 hcond
            rw [hsval,
                List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega)]
            exact hfr i0 hi0 (by omega)
          · intro p hp
            rcases Nat.lt_or_ge p it.start.val with hplt | hpge
            · rw [hsval,
                  List.set_getElem!_ne _ _ _ _
                    (by simp only [Nat.not_eq]; omega)]
              exact hwr p hplt
            · have hpe : p = it.start.val := by omega
              subst hpe
              have hwidx : w0.val + it.start.val = ww.val := by omega
              rw [hsval, hwidx,
                  List.set_getElem!_eq _ _ _ _ ⟨by scalar_tac, rfl⟩]
              exact hbyte
      · -- td < pos: finer than the value has decimals — structural zero
        rename_i htdlt
        step*
        have hsval : (s : Slice Std.U8).val = oo.val.set ww.val i := by
          rw [s_post, Slice.set_val_eq]
        have hbyte : i = asciiByte
            (fracDigitVal digits.val n.val td.val (it.start.val + 1)) := by
          apply UScalar.eq_of_val_eq
          have hfv : fracDigitVal digits.val n.val td.val (it.start.val + 1)
              = 0 := by
            simp only [fracDigitVal]
            rw [if_neg]
            intro hc
            have h1 : td.val < it.start.val + 1 := by scalar_tac
            omega
          rw [i_post, hfv]
          simp
        refine ⟨by rw [hend', hbnd], by omega, by omega, ?_, ?_, ?_, by omega⟩
        · rw [s_post]; simp [hlv]
        · intro i0 hi0 hcond
          rw [hsval,
              List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega)]
          exact hfr i0 hi0 (by omega)
        · intro p hp
          rcases Nat.lt_or_ge p it.start.val with hplt | hpge
          · rw [hsval,
                List.set_getElem!_ne _ _ _ _
                  (by simp only [Nat.not_eq]; omega)]
            exact hwr p hplt
          · have hpe : p = it.start.val := by omega
            subst hpe
            have hwidx : w0.val + it.start.val = ww.val := by omega
            rw [hsval, hwidx,
                List.set_getElem!_eq _ _ _ _ ⟨by scalar_tac, rfl⟩]
            exact hbyte
  · exact ⟨hend, hstart, hw, hlen, hframe, hwritten⟩

set_option maxHeartbeats 4000000 in
/-- Integer-digit loop (loop 1): ASCII-writes the MS-first integer digits
    `digits[n-1-j]` at `out[j]` for j ∈ [iter.start, int_digits), leaves
    indices ≥ int_digits untouched (relative to ghost entry state `out0`),
    preserves the length, and returns the write head at `int_digits`.
    (`digits[td + (int_digits-1-j)] = digits[n-1-j]` given
    `int_digits = n - td`, `td < n`.) -/
theorem emit_int_loop_spec
    (digits : Std.Array Std.U8 80#usize) (n td int_digits : Std.Usize)
    (out0 : Slice Std.U8)
    (iter : core.ops.range.Range Std.Usize) (out : Slice Std.U8)
    (w : Std.Usize)
    (hgt : td.val < n.val) (hn80 : n.val ≤ 80)
    (hid : int_digits.val = n.val - td.val)
    (hdig : ∀ i, i < 80 → (digits.val[i]!).val ≤ 9)
    (hwin : int_digits.val ≤ out0.length)
    (hend : iter.«end» = int_digits)
    (hstart : iter.start.val ≤ int_digits.val)
    (hw : w.val = iter.start.val)
    (hlen : out.length = out0.length)
    (hframe : ∀ i, i < out0.length → iter.start.val ≤ i →
       out.val[i]! = out0.val[i]!)
    (hwritten : ∀ j, j < iter.start.val →
       out.val[j]! = asciiByte (digits.val[n.val - 1 - j]!).val) :
    eip1559.fmt_emit_loop1 iter digits td out int_digits w
      ⦃ r => r.2.val = int_digits.val ∧
             r.1.length = out0.length ∧
             (∀ i, int_digits.val ≤ i → i < out0.length →
                r.1.val[i]! = out0.val[i]!) ∧
             (∀ j, j < int_digits.val →
                r.1.val[j]! = asciiByte (digits.val[n.val - 1 - j]!).val) ⦄ := by
  unfold eip1559.fmt_emit_loop1
  apply Aeneas.Std.loop.spec_decr_nat
    (measure := fun (s : core.ops.range.Range Std.Usize × (Slice Std.U8) ×
                      Std.Usize) => int_digits.val - s.1.start.val)
    (inv := fun (s : core.ops.range.Range Std.Usize × (Slice Std.U8) ×
                     Std.Usize) =>
       s.1.«end» = int_digits ∧ s.1.start.val ≤ int_digits.val ∧
       s.2.2.val = s.1.start.val ∧
       s.2.1.length = out0.length ∧
       (∀ i, i < out0.length → s.1.start.val ≤ i →
          s.2.1.val[i]! = out0.val[i]!) ∧
       (∀ j, j < s.1.start.val →
          s.2.1.val[j]! = asciiByte (digits.val[n.val - 1 - j]!).val))
  · rintro ⟨it, oo, ww⟩ ⟨hbnd, hsle, hwv, hlv, hfr, hwr⟩
    simp only at hbnd hsle hwv hlv hfr hwr
    have hlds : digits.val.length = 80 := by simp
    unfold eip1559.fmt_emit_loop1.body
    let* ⟨o, iter1, hpost⟩ ← next_usize_spec it
    rcases hpost with ⟨ho, hge⟩ | ⟨b, it', heq, hb, hlt, hend', hstart'⟩
    · -- iterator done: start = int_digits — post = the invariant at the top
      subst ho
      simp only [WP.spec_ok]
      have hse : it.start.val = int_digits.val := by rw [hbnd] at hge; omega
      rw [hse] at hwv hfr hwr
      exact ⟨hwv, hlv, fun i h1 h2 => hfr i h2 h1, hwr⟩
    · simp only [Prod.mk.injEq] at heq
      obtain ⟨rfl, rfl⟩ := heq
      subst hb
      have hslt : it.start.val < int_digits.val := by
        rw [hbnd] at hlt; exact hlt
      have hwwlt : ww.val < oo.length := by rw [hlv]; omega
      step*
      · -- side condition: the ASCII add 48 + digit fits in u8
        have hi280 : i2.val < 80 := by scalar_tac
        have hx : d = digits.val[i2.val]! := by
          rw [d_post, ← getElem!_pos _ _ (by rw [hlds]; omega)]
        have h9 : d.val ≤ 9 := by rw [hx]; exact hdig i2.val hi280
        scalar_tac
      · -- re-establish the invariant
        have hi2v : i2.val = n.val - 1 - it.start.val := by scalar_tac
        have hi280 : i2.val < 80 := by omega
        have hx : d = digits.val[i2.val]! := by
          rw [d_post, ← getElem!_pos _ _ (by rw [hlds]; omega)]
        have h9 : d.val ≤ 9 := by rw [hx]; exact hdig i2.val hi280
        have hsval : (s : Slice Std.U8).val = oo.val.set ww.val i3 := by
          rw [s_post, Slice.set_val_eq]
        have hbyte : i3
            = asciiByte (digits.val[n.val - 1 - it.start.val]!).val := by
          apply UScalar.eq_of_val_eq
          rw [i3_post, ← hi2v, ← hx,
              asciiByte_val_of_le h9]
        refine ⟨by rw [hend', hbnd], by omega, by omega, ?_, ?_, ?_, by omega⟩
        · rw [s_post]; simp [hlv]
        · intro i0 hi0 hcond
          rw [hsval,
              List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega)]
          exact hfr i0 hi0 (by omega)
        · intro j hj
          rcases Nat.lt_or_ge j it.start.val with hjlt | hjge
          · rw [hsval,
                List.set_getElem!_ne _ _ _ _
                  (by simp only [Nat.not_eq]; omega)]
            exact hwr j hjlt
          · have hje : j = it.start.val := by omega
            subst hje
            have hwidx : it.start.val = ww.val := by omega
            rw [hsval, hwidx,
                List.set_getElem!_eq _ _ _ _ ⟨hwwlt, rfl⟩]
            rw [hwidx] at hbyte
            exact hbyte
  · exact ⟨hend, hstart, hw, hlen, hframe, hwritten⟩

/-- Assembly helper: a pointwise description of the final buffer yields the
    take/drop form of the SOME-case postcondition. -/
theorem assemble_some
    (l : List Std.U8) (nv tdv fev : Nat) (res out : Slice Std.U8)
    (hlen : res.val.length = out.val.length)
    (hfit : needN nv tdv fev ≤ out.val.length)
    (hpt : ∀ i, i < needN nv tdv fev →
       res.val[i]! = (emitBytes l nv tdv fev)[i]!)
    (huntouched : ∀ i, needN nv tdv fev ≤ i → i < out.val.length →
       res.val[i]! = out.val[i]!) :
    res.val.take (needN nv tdv fev) = emitBytes l nv tdv fev ∧
    res.val.drop (needN nv tdv fev) = out.val.drop (needN nv tdv fev) := by
  constructor
  · exact take_eq_of_getElem! (by omega)
      (emitBytes_length l nv tdv fev) hpt
  · exact drop_eq_of_getElem! hlen
      (fun i h1 h2 => huntouched i h1 (by omega))

/-- `'0' = asciiByte 0` (the zero-integer-part write). -/
theorem u8_48_eq_asciiByte_zero : (48#u8 : Std.U8) = asciiByte 0 := by
  apply UScalar.eq_of_val_eq
  simp

set_option maxHeartbeats 8000000 in
/-- **Functional spec**: `fmt_emit` renders exactly `emitBytes` (int part ++
    optional '.' ++ guarded fractional digits), returning `Some need` and
    touching ONLY `out[0, need)`; when the output would not fit it returns
    `None` with `out` LITERALLY unchanged (the doc-comment claim: the None
    path returns before any write). -/
theorem emit_spec
    (digits : Std.Array Std.U8 80#usize) (n td fe : Std.Usize)
    (out : Slice Std.U8)
    (hn80 : n.val ≤ 80)
    (hdig : ∀ i, i < 80 → (digits.val[i]!).val ≤ 9)
    (hfe : fe.val ≤ 255) :
    eip1559.fmt_emit digits n td fe out
      ⦃ p =>
        (out.length < needN n.val td.val fe.val → p = (none, out)) ∧
        (needN n.val td.val fe.val ≤ out.length →
           ∃ w : Std.Usize, p.1 = some w ∧
             w.val = needN n.val td.val fe.val ∧
             p.2.length = out.length ∧
             p.2.val.take (needN n.val td.val fe.val)
               = emitBytes digits.val n.val td.val fe.val ∧
             p.2.val.drop (needN n.val td.val fe.val)
               = out.val.drop (needN n.val td.val fe.val)) ⦄ := by
  unfold eip1559.fmt_emit
  split
  · -- n > td: the integer part is real digits
    rename_i hgt
    step*
    have hidieN : (n.val - td.val) = intEmitN n.val td.val := by
      simp only [intEmitN, if_neg (show ¬ n.val ≤ td.val by scalar_tac)]
    split
    · -- (dead) int_digits = 0 contradicts n > td
      exfalso
      rename_i hid0
      scalar_tac
    · rename_i hidne
      split
      · -- frac_emit > 0: emit "<int>.<frac>"
        rename_i hfe0
        have hfene : ¬ fe.val = 0 := by scalar_tac
        let* ⟨ione, hione⟩ ← Std.Usize.add_spec
        let* ⟨need2, hneed2⟩ ← Std.Usize.add_spec
        have hneedv : need2.val = needN n.val td.val fe.val := by
          simp only [needN, ← hidieN, if_neg hfene]
          scalar_tac
        have hn2v : need2.val = int_digits.val + 1 + fe.val := by scalar_tac
        split
        · -- does not fit: literally (none, out), nothing written
          simp only [WP.spec_ok]
          rename_i hover
          constructor
          · intro _; trivial
          · intro hfits
            exfalso
            have hl := Slice.len_val out
            simp only [Slice.length] at hfits
            scalar_tac
        · rename_i hfits'
          have hfits : needN n.val td.val fe.val ≤ out.val.length := by
            have hl := Slice.len_val out
            scalar_tac
          simp only [Bool.true_or, massert_True, bind_tc_ok, if_true]
          let* ⟨out1, w, hw1, hlen1, hfr1, hwr1⟩ ← emit_int_loop_spec
            digits n td int_digits out
            { start := 0#usize, «end» := int_digits } out 0#usize
            (by scalar_tac) hn80 (by scalar_tac) hdig
            (by scalar_tac) rfl (by simp) (by simp) rfl
            (fun i _ _ => rfl) (fun j hj => absurd hj (by simp))
          step*
          have hsval : s.val = out1.val.set w.val 46#u8 := by
            rw [s_post, Slice.set_val_eq]
          have hslen : s.val.length = out.val.length := by
            rw [hsval, List.length_set]
            exact hlen1
          let* ⟨out2, w2, hw2, hlen2, hfr2, hwr2⟩ ← emit_frac_loop_spec
            digits n td fe s w1
            { start := 0#usize, «end» := fe } s w1
            hn80 hdig (by scalar_tac) rfl (by simp) (by simp) rfl
            (fun i _ _ => rfl) (fun p hp => absurd hp (by simp))
          have hmas2 : w2 = need2 := UScalar.eq_of_val_eq (by scalar_tac)
          rw [(massert_ok _).mpr hmas2]
          simp only [bind_tc_ok, WP.spec_ok]
          have hidieV : int_digits.val = intEmitN n.val td.val := by
            rw [int_digits_post1, hidieN]
          constructor
          · intro hlt
            exfalso
            simp only [Slice.length] at hlt
            omega
          · intro _
            have hpt : ∀ i, i < needN n.val td.val fe.val →
                out2.val[i]!
                  = (emitBytes digits.val n.val td.val fe.val)[i]! := by
              intro i hi
              rcases Nat.lt_or_ge i int_digits.val with hilt | hige
              · -- integer digits [0, int_digits)
                rw [emitBytes_getElem!_int _ _ _ _ _ (by omega),
                    intBytes_getElem!_of_gt _ _ _ _ (by scalar_tac) (by omega),
                    hfr2 i (by scalar_tac) (Or.inl (by omega)), hsval,
                    List.set_getElem!_ne _ _ _ _
                      (by simp only [Nat.not_eq]; omega)]
                exact hwr1 i hilt
              · rcases Nat.eq_or_lt_of_le hige with hieq | higt
                · -- the '.' at index int_digits = intEmitN
                  rw [← hieq, hidieV,
                      emitBytes_getElem!_dot _ _ _ _ hfene,
                      hfr2 _ (by scalar_tac) (Or.inl (by omega)), hsval,
                      List.set_getElem!_eq _ _ _ _ ⟨by scalar_tac, by omega⟩]
                · -- fractional digits (int_digits, needN)
                  have hplt : i - int_digits.val - 1 < fe.val := by omega
                  have hidx1 : w1.val + (i - int_digits.val - 1) = i := by omega
                  have hidx2 : intEmitN n.val td.val + 1
                      + (i - int_digits.val - 1) = i := by omega
                  have hL := hwr2 (i - int_digits.val - 1) hplt
                  rw [hidx1] at hL
                  have hR := emitBytes_getElem!_frac digits.val n.val td.val
                    fe.val (i - int_digits.val - 1) hfene hplt
                  rw [hidx2] at hR
                  rw [hL, hR]
            have huntouched : ∀ i, needN n.val td.val fe.val ≤ i →
                i < out.val.length → out2.val[i]! = out.val[i]! := by
              intro i hge hilen
              rw [hfr2 i (by scalar_tac) (Or.inr (by omega)), hsval,
                  List.set_getElem!_ne _ _ _ _
                    (by simp only [Nat.not_eq]; omega)]
              exact hfr1 i (by omega) hilen
            have hasm := assemble_some digits.val n.val td.val fe.val out2 out
              (hlen2.trans hslen) hfits hpt huntouched
            exact ⟨w2, rfl, by omega, hlen2.trans hslen, hasm.1, hasm.2⟩
      · -- frac_emit = 0: emit the bare integer part
        rename_i hfen
        have hfe0v : fe.val = 0 := by scalar_tac
        have hneedv0 : int_digits.val = needN n.val td.val fe.val := by
          simp only [needN, ← hidieN, if_pos hfe0v]
          scalar_tac
        simp only [bind_tc_ok]
        step*
        -- step* closes the does-not-fit leaf via hneedv0; the fits leaf stays
        rename_i hfits'
        have hfits : needN n.val td.val fe.val ≤ out.val.length := by
          have hl := Slice.len_val out
          scalar_tac
        let* ⟨out1, w, hw1, hlen1, hfr1, hwr1⟩ ← emit_int_loop_spec
          digits n td int_digits out
          { start := 0#usize, «end» := int_digits } out 0#usize
          (by scalar_tac) hn80 (by scalar_tac) hdig
          (by scalar_tac) rfl (by simp) (by simp) rfl
          (fun i _ _ => rfl) (fun j hj => absurd hj (by simp))
        have hmas : ((false || decide (w = int_digits)) = true) := by
          simp only [Bool.false_or, decide_eq_true_eq]
          exact UScalar.eq_of_val_eq (by omega)
        rw [(massert_ok _).mpr hmas]
        simp only [bind_tc_ok, WP.spec_ok]
        have hidieV : int_digits.val = intEmitN n.val td.val := by
          rw [int_digits_post1, hidieN]
        constructor
        · intro hlt
          exfalso
          simp only [Slice.length] at hlt
          omega
        · intro _
          have hpt : ∀ i, i < needN n.val td.val fe.val →
              out1.val[i]!
                = (emitBytes digits.val n.val td.val fe.val)[i]! := by
            intro i hi
            have hilt : i < int_digits.val := by omega
            rw [emitBytes_getElem!_int _ _ _ _ _ (by omega),
                intBytes_getElem!_of_gt _ _ _ _ (by scalar_tac) (by omega)]
            exact hwr1 i hilt
          have huntouched : ∀ i, needN n.val td.val fe.val ≤ i →
              i < out.val.length → out1.val[i]! = out.val[i]! := by
            intro i hge hilen
            exact hfr1 i (by omega) hilen
          have hasm := assemble_some digits.val n.val td.val fe.val out1 out
            hlen1 hfits hpt huntouched
          exact ⟨w, rfl, by omega, hlen1, hasm.1, hasm.2⟩
  · -- n ≤ td: the integer part is the single "0"
    rename_i hle
    step*
    have hidieN0 : intEmitN n.val td.val = 1 := by
      simp only [intEmitN, if_pos (show n.val ≤ td.val by scalar_tac)]
    simp only [if_true, bind_tc_ok]
    split
    · -- frac_emit > 0: emit "0.<frac>"
      rename_i hfe0
      have hfene : ¬ fe.val = 0 := by scalar_tac
      let* ⟨ione, hione⟩ ← Std.Usize.add_spec
      let* ⟨need2, hneed2⟩ ← Std.Usize.add_spec
      have hneedv : need2.val = needN n.val td.val fe.val := by
        simp only [needN, hidieN0, if_neg hfene]
        scalar_tac
      have hn2v : need2.val = 2 + fe.val := by scalar_tac
      split
      · -- does not fit: literally (none, out), nothing written
        simp only [WP.spec_ok]
        rename_i hover
        constructor
        · intro _; trivial
        · intro hfits
          exfalso
          have hl := Slice.len_val out
          simp only [Slice.length] at hfits
          scalar_tac
      · rename_i hfits'
        have hfits : needN n.val td.val fe.val ≤ out.val.length := by
          have hl := Slice.len_val out
          scalar_tac
        simp only [Bool.true_or, massert_True, bind_tc_ok, if_true]
        step*
        · -- side condition: the '.'-write index is in bounds
          rw [__post2]
          scalar_tac
        have hwv1 : w.val = 1 := by scalar_tac
        have h0v : (0#usize : Std.Usize).val = 0 := by scalar_tac
        have houtlen2 : 2 + fe.val ≤ out.val.length := by
          have hl := Slice.len_val out
          scalar_tac
        have hsval : s.val = (out.val.set 0 48#u8).set 1 46#u8 := by
          rw [s_post, __post2, Slice.set_val_eq, Slice.set_val_eq, hwv1, h0v]
        have hslen : s.val.length = out.val.length := by
          rw [hsval]
          simp
        have hset0len : (out.val.set 0 48#u8).length = out.val.length := by
          simp
        rw [fmt_emit_loop0_eq_loop2]
        let* ⟨out2, w2, hw2, hlen2, hfr2, hwr2⟩ ← emit_frac_loop_spec
          digits n td fe s w1
          { start := 0#usize, «end» := fe } s w1
          hn80 hdig (by scalar_tac) rfl (by simp) (by simp) rfl
          (fun i _ _ => rfl) (fun p hp => absurd hp (by simp))
        have hmas2 : w2 = need2 := UScalar.eq_of_val_eq (by scalar_tac)
        rw [(massert_ok _).mpr hmas2]
        simp only [bind_tc_ok, WP.spec_ok]
        constructor
        · intro hlt
          exfalso
          simp only [Slice.length] at hlt
          omega
        · intro _
          have hpt : ∀ i, i < needN n.val td.val fe.val →
              out2.val[i]!
                = (emitBytes digits.val n.val td.val fe.val)[i]! := by
            intro i hi
            rcases Nat.lt_or_ge i 1 with hi0 | hi1
            · -- i = 0: the "0" integer part
              have hie : i = 0 := by omega
              subst hie
              rw [emitBytes_getElem!_int _ _ _ _ _ (by omega),
                  intBytes_getElem!_of_le _ _ _ (by scalar_tac),
                  hfr2 0 (by scalar_tac) (Or.inl (by omega)), hsval,
                  List.set_getElem!_ne _ _ _ _
                    (by simp only [Nat.not_eq]; omega),
                  List.set_getElem!_eq _ _ _ _ ⟨by omega, rfl⟩,
                  u8_48_eq_asciiByte_zero]
            · rcases Nat.eq_or_lt_of_le hi1 with hieq | higt
              · -- i = 1: the '.'
                rw [← hieq, hidieN0.symm,
                    emitBytes_getElem!_dot _ _ _ _ hfene,
                    hfr2 _ (by scalar_tac) (Or.inl (by omega)), hsval,
                    List.set_getElem!_eq _ _ _ _
                      ⟨by rw [hset0len]; omega, by omega⟩]
              · -- 2 ≤ i: fractional digits
                have hplt : i - 2 < fe.val := by omega
                have hidx1 : w1.val + (i - 2) = i := by omega
                have hidx2 : intEmitN n.val td.val + 1 + (i - 2) = i := by
                  omega
                have hL := hwr2 (i - 2) hplt
                rw [hidx1] at hL
                have hR := emitBytes_getElem!_frac digits.val n.val td.val
                  fe.val (i - 2) hfene hplt
                rw [hidx2] at hR
                rw [hL, hR]
          have huntouched : ∀ i, needN n.val td.val fe.val ≤ i →
              i < out.val.length → out2.val[i]! = out.val[i]! := by
            intro i hge hilen
            rw [hfr2 i (by scalar_tac) (Or.inr (by omega)), hsval,
                List.set_getElem!_ne _ _ _ _
                  (by simp only [Nat.not_eq]; omega),
                List.set_getElem!_ne _ _ _ _
                  (by simp only [Nat.not_eq]; omega)]
          have hasm := assemble_some digits.val n.val td.val fe.val out2 out
            (hlen2.trans hslen) hfits hpt huntouched
          exact ⟨w2, rfl, by omega, hlen2.trans hslen, hasm.1, hasm.2⟩
    · -- frac_emit = 0: emit the bare "0"
      rename_i hfen
      have hfe0v : fe.val = 0 := by scalar_tac
      have hneedv0 : needN n.val td.val fe.val = 1 := by
        simp only [needN, hidieN0, if_pos hfe0v]
      step*
      have hfits : needN n.val td.val fe.val ≤ out.val.length := by
        have hl := Slice.len_val out
        scalar_tac
      have h0v : (0#usize : Std.Usize).val = 0 := by scalar_tac
      have hovalset : (index_mut_back 48#u8).val = out.val.set 0 48#u8 := by
        rw [__post2, Slice.set_val_eq, h0v]
      have hlenr : (index_mut_back 48#u8).val.length = out.val.length := by
        rw [hovalset]
        simp
      constructor
      · intro hlt
        exfalso
        simp only [Slice.length] at hlt
        omega
      · intro _
        have hpt : ∀ i, i < needN n.val td.val fe.val →
            (index_mut_back 48#u8).val[i]!
              = (emitBytes digits.val n.val td.val fe.val)[i]! := by
          intro i hi
          have hie : i = 0 := by omega
          subst hie
          rw [emitBytes_getElem!_int _ _ _ _ _ (by omega),
              intBytes_getElem!_of_le _ _ _ (by scalar_tac), hovalset,
              List.set_getElem!_eq _ _ _ _ ⟨by omega, rfl⟩,
              u8_48_eq_asciiByte_zero]
        have huntouched : ∀ i, needN n.val td.val fe.val ≤ i →
            i < out.val.length →
            (index_mut_back 48#u8).val[i]! = out.val[i]! := by
          intro i hge hilen
          rw [hovalset,
              List.set_getElem!_ne _ _ _ _
                (by simp only [Nat.not_eq]; omega)]
        have hasm := assemble_some digits.val n.val td.val fe.val
          (index_mut_back 48#u8) out hlenr hfits hpt huntouched
        exact ⟨w, rfl, by omega, hlenr, hasm.1, hasm.2⟩

end EmitSpec
