/- §33 — format_decimal Track-1 M4: `fmt_extract_digits` functional
   correctness over the committed Aeneas extraction
   (`Extracted/FormatDecimal/Funs.lean`, regenerated by
   `make extract-format-decimal`).

   THE RESULT (`extract_digits_spec`): for EVERY 32-byte value and EVERY
   initial 80-byte digits buffer, `fmt_extract_digits value digits` succeeds
   (no panic — in particular the unguarded `digits[n]` write is in bounds)
   and returns `(n, ds)` with

     (a) decValue (ds.take n) = beValue value   — the extracted decimal
         digits ARE the 256-bit value (LS-first base-10 Horner);
     (b) 1 ≤ n ≤ 78                             — the digit count is bounded
         by beValue value < 256^32 = 2^256 < 10^78 (this bound IS the
         panic-freedom argument for the `digits[n]` write);
     (c) every stored digit is a real digit (≤ 9, raw value from `% 10`);
     (d) normalization: value = 0 → n = 1, and value ≠ 0 → ds[n-1] ≠ 0
         (no leading-zero digit);
     (e) frame: ds[i] = digits[i] for all n ≤ i < 80 (untouched tail —
         feeds the round/trim/emit milestones, which index past n).

   Proof pattern: `Aeneas.Std.loop.spec_decr_nat` with measure = beValue v
   (strictly decreasing: `Div10Spec.div10_inplace_spec` gives v' = v/10 and
   the `is_zero` guard gives v ≠ 0, so v/10 < v). Invariant = the Euclidean
   split of the original value V at 10^k:
       beValue v_k = V / 10^k  ∧  decValue (ds_k.take k) = V % 10^k
   plus digit bounds, the untouched-`drop` suffix, and a last-written-digit
   witness for the no-leading-zero conjunct. `is_zero` gets its own loop
   spec (`is_zero_spec`: returned bool ⟺ beValue = 0, via
   `beValue_eq_zero_iff`).

   NOTE (axiom discipline): all bit/arith goals closed manually or by
   omega/norm_num — no `bv_tac` (same TRAP as Div10Spec: `bv_decide` would
   inject a native-computation axiom the §33 gate rejects).

   Second milestone of the format_decimal end-to-end WYSIWYS spec (work-todo
   FV frontier, Track 1): next are round_carry / trim / emit, composing to
   "the emitted string parses back to round-half-up(v/10^d, f)". -/
import Aeneas
import Extracted.FormatDecimal.Funs
import Extracted.FormatDecimal.Div10Spec
import Extracted.U256MulSpec
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

namespace ExtractDigitsSpec

open Extracted.Equiv  -- beValue, beValue_cons, beValue_lt from RlpIntSpec/U256MulSpec
open pqsigner_tx_core
open Div10Spec        -- div10_inplace_spec, take_succ_getElem!

/-- LS-first base-10 value of a digit list: `decValue l = Σ l[i]·10^i`
    (index 0 is the LEAST significant digit — the order `fmt_extract_digits`
    stores them in). Foldr-Horner mirror of `beValue` (BE base-256 foldl). -/
def decValue (l : List Std.U8) : Nat :=
  l.foldr (fun b acc => acc * 10 + b.val) 0

@[simp] theorem decValue_nil : decValue [] = 0 := rfl

theorem decValue_cons (b : Std.U8) (l : List Std.U8) :
    decValue (b :: l) = decValue l * 10 + b.val := rfl

/-- Appending one more (most-significant) digit adds it at weight `10^len`. -/
theorem decValue_append_digit (l : List Std.U8) (b : Std.U8) :
    decValue (l ++ [b]) = decValue l + b.val * 10 ^ l.length := by
  induction l with
  | nil => simp [decValue]
  | cons a tl ih =>
    rw [List.cons_append, decValue_cons, decValue_cons, ih, List.length_cons,
        pow_succ]
    ring

/-- `beValue l = 0` iff every byte is zero — the `is_zero` byte scan is a
    faithful zero test for the 256-bit value. -/
theorem beValue_eq_zero_iff (l : List Std.U8) :
    beValue l = 0 ↔ ∀ i, i < l.length → (l[i]!).val = 0 := by
  induction l with
  | nil => simp [beValue]
  | cons b tl ih =>
    rw [beValue_cons]
    have hpow : (0:Nat) < 256 ^ tl.length := Nat.pow_pos (by norm_num)
    constructor
    · intro h i hi
      have hsplit : b.val * 256 ^ tl.length = 0 ∧ beValue tl = 0 := by omega
      have hbv : b.val = 0 := by
        rcases Nat.mul_eq_zero.mp hsplit.1 with h' | h'
        · exact h'
        · omega
      cases i with
      | zero => simpa using hbv
      | succ j =>
        rw [List.getElem!_cons_succ]
        exact ih.mp hsplit.2 j (by simpa using hi)
    · intro h
      have hbv : b.val = 0 := by simpa using h 0 (by simp)
      have htl : beValue tl = 0 := ih.mpr (fun j hj => by
        have := h (j + 1) (by simpa using Nat.succ_lt_succ hj)
        simpa using this)
      simp [hbv, htl]

/-- Pointwise consequence of a `drop`-suffix equality (frame conversion). -/
theorem getElem!_eq_of_drop_eq {l1 l2 : List Std.U8} {k : Nat}
    (h : l1.drop k = l2.drop k) (i : Nat) (hki : k ≤ i) :
    l1[i]! = l2[i]! := by
  have h1 : (l1.drop k)[i - k]! = (l2.drop k)[i - k]! := by rw [h]
  rwa [List.getElem!_drop, List.getElem!_drop,
       show k + (i - k) = i from by omega] at h1

set_option maxHeartbeats 4000000 in
/-- `is_zero` byte-scan loop: with an all-zero prefix below `i0`, the
    returned bool decides `beValue v = 0`. -/
theorem is_zero_loop_spec (v : Std.Array Std.U8 32#usize) (i0 : Std.Usize)
    (hi0 : i0.val ≤ 32)
    (hpre : ∀ j, j < i0.val → (v.val[j]!).val = 0) :
    eip1559.is_zero_loop v i0
      ⦃ b => (b = true) ↔ beValue v.val = 0 ⦄ := by
  have hlen : v.val.length = 32 := by simp
  unfold eip1559.is_zero_loop
  apply Aeneas.Std.loop.spec_decr_nat
    (measure := fun (i : Std.Usize) => 32 - i.val)
    (inv := fun (i : Std.Usize) =>
       i.val ≤ 32 ∧ ∀ j, j < i.val → (v.val[j]!).val = 0)
  · rintro i ⟨hile, hz⟩
    unfold eip1559.is_zero_loop.body
    split
    · rename_i hlt
      have hlt' : i.val < 32 := by scalar_tac
      step*
      · -- found a non-zero byte: done false, value ≠ 0
        have hne : (i1 != 0#u8) = true := by assumption
        have hi1 : i1 = v.val[i.val]! := by
          rw [i1_post, ← getElem!_pos _ _ (by rw [hlen]; omega)]
        have hne' : i1 ≠ 0#u8 := by simpa using hne
        constructor
        · intro h; exact absurd h (by simp)
        · intro h0
          exfalso
          apply hne'
          have hzz : (v.val[i.val]!).val = 0 :=
            (beValue_eq_zero_iff v.val).mp h0 i.val (by rw [hlen]; omega)
          rw [hi1]
          apply UScalar.eq_of_val_eq
          simpa using hzz
      · -- byte is zero: continue with the extended all-zero prefix
        have hzz : ¬(i1 != 0#u8) = true := by assumption
        have hi1 : i1 = v.val[i.val]! := by
          rw [i1_post, ← getElem!_pos _ _ (by rw [hlen]; omega)]
        have hi1z : i1 = 0#u8 := by
          have h0 : i1.val = 0 := by simpa using hzz
          apply UScalar.eq_of_val_eq
          simpa using h0
        refine ⟨by scalar_tac, ?_, by scalar_tac⟩
        intro j hj
        have hj' : j < i.val + 1 := by scalar_tac
        rcases Nat.lt_or_ge j i.val with hji | hji
        · exact hz j hji
        · have hjeq : j = i.val := by omega
          subst hjeq
          rw [← hi1, hi1z]
          simp
    · -- scanned all 32 bytes without a hit: done true, value = 0
      rename_i hge
      simp only [WP.spec_ok]
      constructor
      · intro _
        apply (beValue_eq_zero_iff v.val).mpr
        intro j hjl
        rw [hlen] at hjl
        exact hz j (by scalar_tac)
      · intro _; trivial
  · exact ⟨hi0, hpre⟩

/-- `is_zero` decides `beValue v = 0` (for the full array). -/
theorem is_zero_spec (v : Std.Array Std.U8 32#usize) :
    eip1559.is_zero v ⦃ b => (b = true) ↔ beValue v.val = 0 ⦄ := by
  unfold eip1559.is_zero
  exact is_zero_loop_spec v 0#usize (by simp) (by intro j hj; scalar_tac)

set_option maxHeartbeats 4000000 in
/-- Digit-extraction loop invariant: with the original value `V` split at
    `10^k` (quotient still in `v`, remainder already stored as the digit
    prefix), the loop finishes the job. Ghost `d0` = the original digits
    bytes (frame). -/
theorem extract_digits_loop_spec
    (digits : Std.Array Std.U8 80#usize) (v : Std.Array Std.U8 32#usize)
    (n : Std.Usize) (V : Nat) (d0 : List Std.U8)
    (hVne : V ≠ 0) (hVlt : V < 10 ^ 78)
    (hn : n.val ≤ 78)
    (hquot : beValue v.val = V / 10 ^ n.val)
    (hdec : decValue (digits.val.take n.val) = V % 10 ^ n.val)
    (hdig : ∀ i, i < n.val → (digits.val[i]!).val ≤ 9)
    (hdrop : digits.val.drop n.val = d0.drop n.val)
    (hlast : 1 ≤ n.val → 10 ^ (n.val - 1) ≤ V ∧
             (digits.val[n.val - 1]!).val = (V / 10 ^ (n.val - 1)) % 10) :
    eip1559.fmt_extract_digits_loop digits v n
      ⦃ p => decValue (p.2.val.take p.1.val) = V ∧
             1 ≤ p.1.val ∧ p.1.val ≤ 78 ∧
             (∀ i, i < p.1.val → (p.2.val[i]!).val ≤ 9) ∧
             (p.2.val[p.1.val - 1]!).val ≠ 0 ∧
             (∀ i, p.1.val ≤ i → i < 80 → p.2.val[i]! = d0[i]!) ⦄ := by
  unfold eip1559.fmt_extract_digits_loop
  apply Aeneas.Std.loop.spec_decr_nat
    (measure := fun (s : Std.Array Std.U8 80#usize ×
                      Std.Array Std.U8 32#usize × Std.Usize) =>
       beValue s.2.1.val)
    (inv := fun (s : Std.Array Std.U8 80#usize ×
                     Std.Array Std.U8 32#usize × Std.Usize) =>
       s.2.2.val ≤ 78 ∧
       beValue s.2.1.val = V / 10 ^ s.2.2.val ∧
       decValue (s.1.val.take s.2.2.val) = V % 10 ^ s.2.2.val ∧
       (∀ i, i < s.2.2.val → (s.1.val[i]!).val ≤ 9) ∧
       s.1.val.drop s.2.2.val = d0.drop s.2.2.val ∧
       (1 ≤ s.2.2.val → 10 ^ (s.2.2.val - 1) ≤ V ∧
        (s.1.val[s.2.2.val - 1]!).val = (V / 10 ^ (s.2.2.val - 1)) % 10))
  · rintro ⟨ds, vv, k⟩ ⟨hk78, hq, hdc, hdg, hdr, hlst⟩
    simp only at hk78 hq hdc hdg hdr hlst
    have hlds : ds.val.length = 80 := by simp
    unfold eip1559.fmt_extract_digits_loop.body
    let* ⟨b, hb⟩ ← is_zero_spec vv
    split
    · -- v = 0: done (k, ds) — the digit prefix IS the value
      rename_i hbt
      simp only [WP.spec_ok]
      have h0 : V / 10 ^ k.val = 0 := by rw [← hq]; exact hb.mp hbt
      have hVlt10k : V < 10 ^ k.val := by
        rcases Nat.div_eq_zero_iff.mp h0 with h | h
        · exact absurd h (by positivity)
        · exact h
      have hk1 : 1 ≤ k.val := by
        by_contra hk0
        have hkz : k.val = 0 := by omega
        rw [hkz, pow_zero, Nat.div_one] at h0
        exact hVne h0
      obtain ⟨hple, hdeq⟩ := hlst hk1
      refine ⟨?_, hk1, hk78, hdg, ?_, ?_⟩
      · rw [hdc, Nat.mod_eq_of_lt hVlt10k]
      · -- last digit ≠ 0: V/10^(k-1) ∈ [1, 10) so its mod-10 is itself, ≥ 1
        have hdivlt : V / 10 ^ (k.val - 1) < 10 := by
          apply (Nat.div_lt_iff_lt_mul (Nat.pow_pos (by norm_num))).mpr
          have hkk : 10 * 10 ^ (k.val - 1) = 10 ^ k.val := by
            rw [← pow_succ']
            congr 1
            omega
          omega
        have hdivge : 1 ≤ V / 10 ^ (k.val - 1) :=
          (Nat.one_le_div_iff (Nat.pow_pos (by norm_num))).mpr hple
        rw [hdeq, Nat.mod_eq_of_lt hdivlt]
        omega
      · intro i hki hi80
        exact getElem!_eq_of_drop_eq hdr i hki
    · -- v ≠ 0: divide by 10, store the remainder digit at index k
      rename_i hbf
      have hvne : beValue vv.val ≠ 0 := fun h0 => hbf (hb.mpr h0)
      have hpk : 10 ^ k.val ≤ V := by
        rw [hq] at hvne
        have hiff := Nat.one_le_div_iff (a := V) (b := 10 ^ k.val)
          (Nat.pow_pos (by norm_num))
        omega
      have hklt : k.val < 78 := by
        have h1 : (10:Nat) ^ k.val < 10 ^ 78 := Nat.lt_of_le_of_lt hpk hVlt
        exact (Nat.pow_lt_pow_iff_right (by norm_num)).mp h1
      let* ⟨r, v1, hrq, hrr⟩ ← div10_inplace_spec vv
      step*
      -- value facts ------------------------------------------------------
      have hvpos : 0 < beValue vv.val := Nat.pos_of_ne_zero hvne
      have hq1 : beValue v1.val = V / 10 ^ (k.val + 1) := by
        rw [hrq, hq, Nat.div_div_eq_div_mul, pow_succ]
      have hrv : r.val = (V / 10 ^ k.val) % 10 := by rw [hrr, hq]
      have hr9 : r.val ≤ 9 := by
        have hlt : r.val < 10 := by rw [hrv]; exact Nat.mod_lt _ (by norm_num)
        omega
      -- structural rewrites ----------------------------------------------
      have haval : (a : Std.Array Std.U8 80#usize).val = ds.val.set k.val r := by
        rw [a_post, Array.set_val_eq]
      have hsetlen : (ds.val.set k.val r).length = 80 := by
        simp [List.length_set, hlds]
      have hsetk : (ds.val.set k.val r)[k.val]! = r :=
        List.set_getElem!_eq _ _ _ _ ⟨by rw [hlds]; omega, rfl⟩
      have htake1 : (ds.val.set k.val r).take (k.val + 1)
          = ds.val.take k.val ++ [r] := by
        rw [take_succ_getElem! _ _ (by rw [hsetlen]; omega)]
        congr 1
        · exact List.take_set_of_le (Nat.le_refl _)
        · rw [hsetk]
      have hdec1 : decValue ((ds.val.set k.val r).take (k.val + 1))
          = V % 10 ^ (k.val + 1) := by
        rw [htake1, decValue_append_digit, hdc, List.length_take,
            Nat.min_eq_left (by rw [hlds]; omega), hrv, pow_succ, Nat.mod_mul]
        ring
      have hdrop1 : (ds.val.set k.val r).drop (k.val + 1)
          = d0.drop (k.val + 1) := by
        rw [List.drop_set_of_lt (by omega)]
        have h2 := congrArg (List.drop 1) hdr
        rwa [List.drop_drop, List.drop_drop] at h2
      -- invariant + measure ----------------------------------------------
      refine ⟨by omega, ?_, ?_, ?_, ?_, ?_, ?_⟩
      · rw [n_digits1_post, hq1]
      · rw [n_digits1_post, haval]
        exact hdec1
      · intro i hi
        rw [n_digits1_post] at hi
        rw [haval]
        rcases Nat.lt_or_ge i k.val with hik | hik
        · rw [List.set_getElem!_ne _ _ _ _ (by omega)]
          exact hdg i hik
        · have hieq : i = k.val := by omega
          subst hieq
          rw [hsetk]
          exact hr9
      · rw [n_digits1_post, haval]
        exact hdrop1
      · intro h1
        rw [n_digits1_post, haval]
        simp only [Nat.add_sub_cancel]
        exact ⟨hpk, by rw [hsetk, hrv]⟩
      · rw [hrq]
        exact Nat.div_lt_self hvpos (by norm_num)
  · exact ⟨hn, hquot, hdec, hdig, hdrop, hlast⟩

/-- **Functional spec**: `fmt_extract_digits` writes the LS-first decimal
    digits of the 256-bit BE value and returns their count `n`, with
    1 ≤ n ≤ 78, every digit ≤ 9, exact normalization (`n = 1` for zero, no
    leading-zero top digit otherwise), and the tail `digits[n..80]`
    untouched. Total on ALL inputs — the `n ≤ 78 < 80` bound is the
    panic-freedom argument for the unguarded `digits[n]` write. -/
theorem extract_digits_spec
    (value : Std.Array Std.U8 32#usize) (digits : Std.Array Std.U8 80#usize) :
    eip1559.fmt_extract_digits value digits
      ⦃ p => decValue (p.2.val.take p.1.val) = beValue value.val ∧
             1 ≤ p.1.val ∧ p.1.val ≤ 78 ∧
             (∀ i, i < p.1.val → (p.2.val[i]!).val ≤ 9) ∧
             (beValue value.val = 0 → p.1.val = 1) ∧
             (beValue value.val ≠ 0 → (p.2.val[p.1.val - 1]!).val ≠ 0) ∧
             (∀ i, p.1.val ≤ i → i < 80 → p.2.val[i]! = digits.val[i]!) ⦄ := by
  have hVlt : beValue value.val < 10 ^ 78 := by
    have h := beValue_lt value.val
    have hlen : value.val.length = 32 := by simp
    rw [hlen] at h
    calc beValue value.val < 256 ^ 32 := h
      _ < 10 ^ 78 := by norm_num
  have hlds : digits.val.length = 80 := by simp
  unfold eip1559.fmt_extract_digits
  let* ⟨b, hb⟩ ← is_zero_spec value
  split
  · -- zero value: digits[0] := 0, n = 1
    rename_i hbt
    have hV0 : beValue value.val = 0 := hb.mp hbt
    step*
    have hd1 : (digits1 : Std.Array Std.U8 80#usize).val
        = digits.val.set 0 0#u8 := by
      rw [digits1_post, Array.set_val_eq]
      simp
    have hget0 : (digits.val.set 0 0#u8)[0]! = 0#u8 :=
      List.set_getElem!_eq _ _ _ _ ⟨by rw [hlds]; omega, rfl⟩
    have htake : (digits.val.set 0 0#u8).take 1 = [0#u8] := by
      rw [take_succ_getElem! _ _ (by simp [List.length_set, hlds]), hget0]
      simp
    refine ⟨?_, by simp, by simp, ?_, by simp, ?_, ?_⟩
    · rw [hd1]
      simp only [UScalar.ofNatCore_val_eq]
      rw [htake, hV0]
      simp [decValue]
    · intro i hi
      simp only [UScalar.ofNatCore_val_eq] at hi
      have hi0 : i = 0 := by omega
      subst hi0
      rw [hd1, hget0]
      simp
    · intro hne
      exact absurd hV0 hne
    · intro i h1i hi80
      simp only [UScalar.ofNatCore_val_eq] at h1i
      rw [hd1, List.set_getElem!_ne _ _ _ _ (by omega)]
  · -- non-zero value: the extraction loop from k = 0
    rename_i hbf
    have hVne : beValue value.val ≠ 0 := fun h0 => hbf (hb.mpr h0)
    apply Aeneas.Std.WP.spec_mono
      (extract_digits_loop_spec digits value 0#usize (beValue value.val)
        digits.val hVne hVlt
        (by simp)
        (by simp)
        (by simp [decValue, Nat.mod_one])
        (by intro i hi; scalar_tac)
        rfl
        (by intro h1; exact absurd h1 (by simp)))
    rintro p ⟨ha, hb1, hb78, hc, hd, he⟩
    exact ⟨ha, hb1, hb78, hc, fun h0 => absurd h0 hVne, fun _ => hd, he⟩

end ExtractDigitsSpec
