-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx_core]: function definitions
import Aeneas
import Extracted.U256Mul.Types -- canonical eip1559.U256 home (dedup: both extractions define it)
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pqsigner_tx_core

/-- [pqsigner_tx_core::eip1559::fmt_emit]: loop body 0:
    Source: 'tx-core/src/eip1559.rs', lines 311:8-321:9 -/
@[rust_loop_body]
def eip1559.fmt_emit_loop0.body
  (digits : Array Std.U8 80#usize) (n_digits : Std.Usize)
  (total_decimals : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (out : Slice Std.U8) (w : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Slice Std.U8) ×
    Std.Usize) ((Slice Std.U8) × Std.Usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (out, w))
  | some p =>
    let pos ← p + 1#usize
    let digit_idx ← lift (core.num.Usize.saturating_sub total_decimals pos)
    let (iter2, d) ←
      if total_decimals >= pos
      then
        do
        let i ←
          if digit_idx < n_digits
          then Array.index_usize digits digit_idx
          else ok 0#u8
        ok (iter1, i)
      else ok (iter1, 0#u8)
    let i ← 48#u8 + d
    let s ← Slice.update out w i
    let w1 ← w + 1#usize
    ok (cont (iter2, s, w1))

/-- [pqsigner_tx_core::eip1559::fmt_emit]: loop 0:
    Source: 'tx-core/src/eip1559.rs', lines 311:8-321:9 -/
@[rust_loop]
def eip1559.fmt_emit_loop0
  (iter : core.ops.range.Range Std.Usize) (digits : Array Std.U8 80#usize)
  (n_digits : Std.Usize) (total_decimals : Std.Usize) (out : Slice Std.U8)
  (w : Std.Usize) :
  Result ((Slice Std.U8) × Std.Usize)
  := do
  loop
    (fun (iter1, out1, w1) => eip1559.fmt_emit_loop0.body digits n_digits
      total_decimals iter1 out1 w1)
    (iter, out, w)

/-- [pqsigner_tx_core::eip1559::fmt_emit]: loop body 1:
    Source: 'tx-core/src/eip1559.rs', lines 299:8-304:9 -/
@[rust_loop_body]
def eip1559.fmt_emit_loop1.body
  (digits : Array Std.U8 80#usize) (total_decimals : Std.Usize)
  (int_digits : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (out : Slice Std.U8) (w : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Slice Std.U8) ×
    Std.Usize) ((Slice Std.U8) × Std.Usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (out, w))
  | some j =>
    let i ← int_digits - 1#usize
    let i1 ← i - j
    let i2 ← total_decimals + i1
    let d ← Array.index_usize digits i2
    let i3 ← 48#u8 + d
    let s ← Slice.update out w i3
    let w1 ← w + 1#usize
    ok (cont (iter1, s, w1))

/-- [pqsigner_tx_core::eip1559::fmt_emit]: loop 1:
    Source: 'tx-core/src/eip1559.rs', lines 299:8-304:9 -/
@[rust_loop]
def eip1559.fmt_emit_loop1
  (iter : core.ops.range.Range Std.Usize) (digits : Array Std.U8 80#usize)
  (total_decimals : Std.Usize) (out : Slice Std.U8) (int_digits : Std.Usize)
  (w : Std.Usize) :
  Result ((Slice Std.U8) × Std.Usize)
  := do
  loop
    (fun (iter1, out1, w1) => eip1559.fmt_emit_loop1.body digits total_decimals
      int_digits iter1 out1 w1)
    (iter, out, w)

/-- [pqsigner_tx_core::eip1559::fmt_emit]: loop body 2:
    Source: 'tx-core/src/eip1559.rs', lines 311:8-321:9 -/
@[rust_loop_body]
def eip1559.fmt_emit_loop2.body
  (digits : Array Std.U8 80#usize) (n_digits : Std.Usize)
  (total_decimals : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (out : Slice Std.U8) (w : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Slice Std.U8) ×
    Std.Usize) ((Slice Std.U8) × Std.Usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (out, w))
  | some p =>
    let pos ← p + 1#usize
    let digit_idx ← lift (core.num.Usize.saturating_sub total_decimals pos)
    let (iter2, d) ←
      if total_decimals >= pos
      then
        do
        let i ←
          if digit_idx < n_digits
          then Array.index_usize digits digit_idx
          else ok 0#u8
        ok (iter1, i)
      else ok (iter1, 0#u8)
    let i ← 48#u8 + d
    let s ← Slice.update out w i
    let w1 ← w + 1#usize
    ok (cont (iter2, s, w1))

/-- [pqsigner_tx_core::eip1559::fmt_emit]: loop 2:
    Source: 'tx-core/src/eip1559.rs', lines 311:8-321:9 -/
@[rust_loop]
def eip1559.fmt_emit_loop2
  (iter : core.ops.range.Range Std.Usize) (digits : Array Std.U8 80#usize)
  (n_digits : Std.Usize) (total_decimals : Std.Usize) (out : Slice Std.U8)
  (w : Std.Usize) :
  Result ((Slice Std.U8) × Std.Usize)
  := do
  loop
    (fun (iter1, out1, w1) => eip1559.fmt_emit_loop2.body digits n_digits
      total_decimals iter1 out1 w1)
    (iter, out, w)

/-- [pqsigner_tx_core::eip1559::fmt_emit]:
    Source: 'tx-core/src/eip1559.rs', lines 264:0-325:1 -/
def eip1559.fmt_emit
  (digits : Array Std.U8 80#usize) (n_digits : Std.Usize)
  (total_decimals : Std.Usize) (frac_emit : Std.Usize) (out : Slice Std.U8) :
  Result ((Option Std.Usize) × (Slice Std.U8))
  := do
  let int_digits ←
    if n_digits > total_decimals
    then n_digits - total_decimals
    else ok 0#usize
  let need ← if int_digits = 0#usize
               then ok 1#usize
               else ok int_digits
  let (need1, emit_point) ←
    if frac_emit > 0#usize
    then
      do
      let i ← 1#usize + frac_emit
      let need2 ← need + i
      ok (need2, true)
    else ok (need, false)
  let i := Slice.len out
  if need1 > i
  then ok (none, out)
  else
    if int_digits = 0#usize
    then
      let (_, index_mut_back) ← Slice.index_mut_usize out 0#usize
      let w ← 0#usize + 1#usize
      massert (emit_point || (w = need1))
      if emit_point
      then
        let out1 := index_mut_back 48#u8
        let s ← Slice.update out1 w 46#u8
        let w1 ← w + 1#usize
        let (out2, w2) ←
          eip1559.fmt_emit_loop0 { start := 0#usize, «end» := frac_emit }
            digits n_digits total_decimals s w1
        massert (w2 = need1)
        ok (some w2, out2)
      else let out1 := index_mut_back 48#u8
           ok (some w, out1)
    else
      let (out1, w) ←
        eip1559.fmt_emit_loop1 { start := 0#usize, «end» := int_digits }
          digits total_decimals out int_digits 0#usize
      massert (emit_point || (w = need1))
      if emit_point
      then
        let s ← Slice.update out1 w 46#u8
        let w1 ← w + 1#usize
        let (out2, w2) ←
          eip1559.fmt_emit_loop2 { start := 0#usize, «end» := frac_emit }
            digits n_digits total_decimals s w1
        massert (w2 = need1)
        ok (some w2, out2)
      else ok (some w, out1)

/-- [pqsigner_tx_core::eip1559::fmt_trim_frac]: loop body 0:
    Source: 'tx-core/src/eip1559.rs', lines 246:4-258:5 -/
@[rust_loop_body]
def eip1559.fmt_trim_frac_loop.body
  (digits : Array Std.U8 80#usize) (n_digits : Std.Usize)
  (total_decimals : Std.Usize) (frac_emit : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if frac_emit > 0#usize
  then
    let digit_idx ←
      lift (core.num.Usize.saturating_sub total_decimals frac_emit)
    let d ←
      if total_decimals >= frac_emit
      then
        if digit_idx < n_digits
        then Array.index_usize digits digit_idx
        else ok 0#u8
      else ok 0#u8
    if d != 0#u8
    then ok (done frac_emit)
    else let frac_emit1 ← frac_emit - 1#usize
         ok (cont frac_emit1)
  else ok (done frac_emit)

/-- [pqsigner_tx_core::eip1559::fmt_trim_frac]: loop 0:
    Source: 'tx-core/src/eip1559.rs', lines 246:4-258:5 -/
@[rust_loop]
def eip1559.fmt_trim_frac_loop
  (digits : Array Std.U8 80#usize) (n_digits : Std.Usize)
  (total_decimals : Std.Usize) (frac_emit : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun frac_emit1 => eip1559.fmt_trim_frac_loop.body digits n_digits
      total_decimals frac_emit1)
    frac_emit

/-- [pqsigner_tx_core::eip1559::fmt_trim_frac]:
    Source: 'tx-core/src/eip1559.rs', lines 239:0-260:1 -/
@[reducible]
def eip1559.fmt_trim_frac
  (digits : Array Std.U8 80#usize) (n_digits : Std.Usize)
  (total_decimals : Std.Usize) (frac : Std.Usize) :
  Result Std.Usize
  := do
  eip1559.fmt_trim_frac_loop digits n_digits total_decimals frac

/-- [pqsigner_tx_core::eip1559::fmt_round_half_up]: loop body 0:
    Source: 'tx-core/src/eip1559.rs', lines 222:12-230:13 -/
@[rust_loop_body]
def eip1559.fmt_round_half_up_loop.body
  (digits : Array Std.U8 80#usize) (n : Std.Usize) (carry : Std.U8)
  (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 80#usize) × Std.Usize × Std.U8 ×
    Std.Usize) (Std.Usize × (Array Std.U8 80#usize)))
  := do
  if carry > 0#u8
  then
    let s ← lift (Array.to_slice digits)
    let i1 := Slice.len s
    if i < i1
    then
      let i2 ← Array.index_usize digits i
      let sum ← i2 + carry
      let (_, index_mut_back) ← Array.index_mut_usize digits i
      let i3 ← sum % 10#u8
      let carry1 ← sum / 10#u8
      if i >= n
      then
        let digits1 := index_mut_back i3
        let i4 ← Array.index_usize digits1 i
        let n1 ← if i4 != 0#u8
                   then i + 1#usize
                   else ok n
        let i5 ← i + 1#usize
        ok (cont (digits1, n1, carry1, i5))
      else
        let i4 ← i + 1#usize
        let a := index_mut_back i3
        ok (cont (a, n, carry1, i4))
    else ok (done (n, digits))
  else ok (done (n, digits))

/-- [pqsigner_tx_core::eip1559::fmt_round_half_up]: loop 0:
    Source: 'tx-core/src/eip1559.rs', lines 222:12-230:13 -/
@[rust_loop]
def eip1559.fmt_round_half_up_loop
  (digits : Array Std.U8 80#usize) (n : Std.Usize) (carry : Std.U8)
  (i : Std.Usize) :
  Result (Std.Usize × (Array Std.U8 80#usize))
  := do
  loop
    (fun (digits1, n1, carry1, i1) => eip1559.fmt_round_half_up_loop.body
      digits1 n1 carry1 i1)
    (digits, n, carry, i)

/-- [pqsigner_tx_core::eip1559::fmt_round_half_up]:
    Source: 'tx-core/src/eip1559.rs', lines 207:0-234:1 -/
def eip1559.fmt_round_half_up
  (digits : Array Std.U8 80#usize) (n_digits : Std.Usize)
  (total_decimals : Std.Usize) (frac : Std.Usize) :
  Result (Std.Usize × (Array Std.U8 80#usize))
  := do
  if total_decimals > frac
  then
    let round_idx ← total_decimals - frac
    let i ← round_idx - 1#usize
    let drop_digit ←
      if i < n_digits
      then Array.index_usize digits i
      else ok 0#u8
    if drop_digit >= 5#u8
    then eip1559.fmt_round_half_up_loop digits n_digits 1#u8 round_idx
    else ok (n_digits, digits)
  else ok (n_digits, digits)

/-- [pqsigner_tx_core::eip1559::is_zero]: loop body 0:
    Source: 'tx-core/src/eip1559.rs', lines 370:4-377:1 -/
@[rust_loop_body]
def eip1559.is_zero_loop.body
  (v : Array Std.U8 32#usize) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if i < 32#usize
  then
    let i1 ← Array.index_usize v i
    if i1 != 0#u8
    then ok (done false)
    else let i2 ← i + 1#usize
         ok (cont i2)
  else ok (done true)

/-- [pqsigner_tx_core::eip1559::is_zero]: loop 0:
    Source: 'tx-core/src/eip1559.rs', lines 370:4-377:1 -/
@[rust_loop]
def eip1559.is_zero_loop
  (v : Array Std.U8 32#usize) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => eip1559.is_zero_loop.body v i1)
    i

/-- [pqsigner_tx_core::eip1559::is_zero]:
    Source: 'tx-core/src/eip1559.rs', lines 368:0-377:1 -/
@[reducible]
def eip1559.is_zero (v : Array Std.U8 32#usize) : Result Bool := do
  eip1559.is_zero_loop v 0#usize

/-- [pqsigner_tx_core::eip1559::div10_inplace]: loop body 0:
    Source: 'tx-core/src/eip1559.rs', lines 358:4-362:5 -/
@[rust_loop_body]
def eip1559.div10_inplace_loop.body
  (iter : core.ops.range.Range Std.Usize) (v : Array Std.U8 32#usize)
  (rem : Std.U16) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U8
    32#usize) × Std.U16) ((Array Std.U8 32#usize) × Std.U16))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (v, rem))
  | some i =>
    let i1 ← rem <<< 8#i32
    let i2 ← Array.index_usize v i
    let i3 ← lift (UScalar.cast .U16 i2)
    let acc ← lift (i1 ||| i3)
    let i4 ← acc / 10#u16
    let i5 ← lift (UScalar.cast .U8 i4)
    let a ← Array.update v i i5
    let rem1 ← acc % 10#u16
    ok (cont (iter1, a, rem1))

/-- [pqsigner_tx_core::eip1559::div10_inplace]: loop 0:
    Source: 'tx-core/src/eip1559.rs', lines 358:4-362:5 -/
@[rust_loop]
def eip1559.div10_inplace_loop
  (iter : core.ops.range.Range Std.Usize) (v : Array Std.U8 32#usize)
  (rem : Std.U16) :
  Result ((Array Std.U8 32#usize) × Std.U16)
  := do
  loop
    (fun (iter1, v1, rem1) => eip1559.div10_inplace_loop.body iter1 v1 rem1)
    (iter, v, rem)

/-- [pqsigner_tx_core::eip1559::div10_inplace]:
    Source: 'tx-core/src/eip1559.rs', lines 356:0-364:1 -/
def eip1559.div10_inplace
  (v : Array Std.U8 32#usize) :
  Result (Std.U8 × (Array Std.U8 32#usize))
  := do
  let (v1, rem) ←
    eip1559.div10_inplace_loop { start := 0#usize, «end» := 32#usize } v
      0#u16
  let i ← lift (UScalar.cast .U8 rem)
  ok (i, v1)

/-- [pqsigner_tx_core::eip1559::fmt_extract_digits]: loop body 0:
    Source: 'tx-core/src/eip1559.rs', lines 185:4-189:5 -/
@[rust_loop_body]
def eip1559.fmt_extract_digits_loop.body
  (digits : Array Std.U8 80#usize) (v : Array Std.U8 32#usize)
  (n_digits : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 80#usize) × (Array Std.U8 32#usize) ×
    Std.Usize) (Std.Usize × (Array Std.U8 80#usize)))
  := do
  let b ← eip1559.is_zero v
  if b
  then ok (done (n_digits, digits))
  else
    let (r, v1) ← eip1559.div10_inplace v
    let a ← Array.update digits n_digits r
    let n_digits1 ← n_digits + 1#usize
    ok (cont (a, v1, n_digits1))

/-- [pqsigner_tx_core::eip1559::fmt_extract_digits]: loop 0:
    Source: 'tx-core/src/eip1559.rs', lines 185:4-189:5 -/
@[rust_loop]
def eip1559.fmt_extract_digits_loop
  (digits : Array Std.U8 80#usize) (v : Array Std.U8 32#usize)
  (n_digits : Std.Usize) :
  Result (Std.Usize × (Array Std.U8 80#usize))
  := do
  loop
    (fun (digits1, v1, n_digits1) => eip1559.fmt_extract_digits_loop.body
      digits1 v1 n_digits1)
    (digits, v, n_digits)

/-- [pqsigner_tx_core::eip1559::fmt_extract_digits]:
    Source: 'tx-core/src/eip1559.rs', lines 178:0-191:1 -/
def eip1559.fmt_extract_digits
  (value : Array Std.U8 32#usize) (digits : Array Std.U8 80#usize) :
  Result (Std.Usize × (Array Std.U8 80#usize))
  := do
  let b ← eip1559.is_zero value
  if b
  then let digits1 ← Array.update digits 0#usize 0#u8
       ok (1#usize, digits1)
  else eip1559.fmt_extract_digits_loop digits value 0#usize

/-- [pqsigner_tx_core::eip1559::{pqsigner_tx_core::eip1559::U256}::format_decimal]:
    Source: 'tx-core/src/eip1559.rs', lines 134:4-166:5
    Visibility: public -/
def eip1559.U256.format_decimal
  (self : eip1559.U256) (decimals : Std.U32) (frac_digits : Std.U32)
  (trim_trailing_zeros : Bool) (out : Slice Std.U8) :
  Result ((Option Std.Usize) × (Slice Std.U8))
  := do
  let digits := Array.repeat 80#usize 0#u8
  let (n_digits, digits1) ← eip1559.fmt_extract_digits self digits
  let total_decimals ← lift (UScalar.cast .Usize decimals)
  let frac ← lift (UScalar.cast .Usize frac_digits)
  let (n_digits1, digits2) ←
    eip1559.fmt_round_half_up digits1 n_digits total_decimals frac
  let frac_emit ←
    if trim_trailing_zeros
    then eip1559.fmt_trim_frac digits2 n_digits1 total_decimals frac
    else ok frac
  eip1559.fmt_emit digits2 n_digits1 total_decimals frac_emit out

/-- [pqsigner_tx_core::eip1559::u256_format_decimal]:
    Source: 'tx-core/src/eip1559.rs', lines 341:0-349:1
    Visibility: public -/
def eip1559.u256_format_decimal
  (v : eip1559.U256) (decimals : Std.U32) (frac_digits : Std.U32)
  (trim_trailing_zeros : Bool) (out : Slice Std.U8) :
  Result ((Option Std.Usize) × (Slice Std.U8))
  := do
  eip1559.U256.format_decimal v decimals frac_digits trim_trailing_zeros out

end pqsigner_tx_core
