/- §33 — format_decimal Track-1 M5: `fmt_round_half_up` functional
   correctness over the committed Aeneas extraction
   (`Extracted/FormatDecimal/Funs.lean`, regenerated by
   `make extract-format-decimal`).

   THE RESULT (`round_carry_spec`): under the extract_digits post-state
   (1 ≤ n ≤ 78, digits below n are real digits ≤ 9, positions n..79 still
   zero — format_decimal calls extract_digits into a FRESH [0u8;80], so the
   zero tail is the M4 frame + zero-init; the M7 composition discharges it),
   `fmt_round_half_up digits n total_decimals frac` succeeds (no panic) and

   • rounding case (total_decimals > frac AND the first dropped digit
     `digits[round_idx-1]` — 0 when read past n — is ≥ 5), with
     rid = total_decimals - frac (`carryPost`):
       (a) decValue ds' = decValue digits + 10^rid   — the carry
           propagation is value-exact: +1 ulp at the first KEPT digit;
       (b) ∀ i < rid, ds'[i] = digits[i]             — dropped prefix untouched;
       (c) ∀ i < 80, ds'[i] ≤ 9                      — still real digits;
       (d) n ≤ n' ≤ n+1, positions ≥ n' are zero, and
           n' = n ∨ ds'[n'-1] ≠ 0                    — the count grows only
           when the carry writes a fresh top digit (0.9999996 → 1.000000).
   • no-round case: (n', ds') = (n, digits) — bit-for-bit identity.

   Overflow safety (the in-code comment's claim) falls out of the loop
   invariant: while the carry is live every processed digit was a 9 rewritten
   to 0, so the live-carry index never passes n ≤ 78 — the loop always
   terminates by carry-death at index ≤ n, never at the i = 80 boundary.

   Proof pattern: `Aeneas.Std.loop.spec_decr_nat` (measure 80 - i) with a
   two-phase invariant:
     phase A (carry = 1): i ≤ n, n unchanged, and the value ledger
         decValue ds + 10^i = decValue digits + 10^rid
       (the +1 ulp is "parked" at the current index while 9s collapse to 0s);
     phase B (carry = 0): the postcondition `carryPost` already holds — the
       next loop head exits immediately.
   Single-write value accounting via `decValue_set` (subtraction-free
   additive form) and its two instances `decValue_set_incr` (carry death:
   digit d ≤ 8 becomes d+1) / `decValue_set_carry` (carry survival: a 9
   collapses to 0 and the ulp re-parks one position up).

   NOTE (axiom discipline): all arithmetic closed manually / omega /
   norm_num — no `bv_tac` (same TRAP as Div10Spec: `bv_decide` would inject
   a native-computation axiom the §33 gate rejects).

   Third milestone of the format_decimal end-to-end WYSIWYS spec (work-todo
   FV frontier, Track 1): next are trim (M6) / emit, composing to "the
   emitted string parses back to round-half-up(v/10^d, f)". -/
import Aeneas
import Extracted.FormatDecimal.Funs
import Extracted.FormatDecimal.Div10Spec
import Extracted.FormatDecimal.ExtractDigitsSpec
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

namespace RoundCarrySpec

open pqsigner_tx_core
open Div10Spec          -- take_succ_getElem! (Div10Spec bookkeeping kit)
open ExtractDigitsSpec  -- decValue (REUSED, not redefined) + lemmas

/-- Value change of a single digit write, subtraction-free additive form:
    writing `b` over `l[i]` trades `l[i]·10^i` for `b·10^i`. -/
theorem decValue_set (l : List Std.U8) (i : Nat) (b : Std.U8)
    (h : i < l.length) :
    decValue (l.set i b) + (l[i]!).val * 10 ^ i
      = decValue l + b.val * 10 ^ i := by
  induction l generalizing i with
  | nil => simp at h
  | cons a tl ih =>
    cases i with
    | zero =>
      simp only [List.set_cons_zero, decValue_cons, List.getElem!_cons_zero,
                 pow_zero]
      ring
    | succ j =>
      have hj : j < tl.length := by simpa using h
      calc decValue ((a :: tl).set (j + 1) b)
              + ((a :: tl)[j + 1]!).val * 10 ^ (j + 1)
          = (decValue (tl.set j b) + (tl[j]!).val * 10 ^ j) * 10 + a.val := by
            rw [List.set_cons_succ, decValue_cons, List.getElem!_cons_succ,
                pow_succ]
            ring
        _ = (decValue tl + b.val * 10 ^ j) * 10 + a.val := by rw [ih j hj]
        _ = decValue (a :: tl) + b.val * 10 ^ (j + 1) := by
            rw [decValue_cons, pow_succ]
            ring

/-- Carry-death write: digit d ≤ 8 becomes d+1 — the value gains exactly
    one ulp at position `i`. -/
theorem decValue_set_incr (l : List Std.U8) (i : Nat) (b : Std.U8)
    (h : i < l.length) (hb : b.val = (l[i]!).val + 1) :
    decValue (l.set i b) = decValue l + 10 ^ i := by
  have hs := decValue_set l i b h
  rw [hb, Nat.add_mul, one_mul] at hs
  omega

/-- Carry-propagation write: a 9 collapses to 0 — the value drops 9·10^i
    (and the loop re-parks the ulp at 10^(i+1)). -/
theorem decValue_set_carry (l : List Std.U8) (i : Nat) (b : Std.U8)
    (h : i < l.length) (h9 : (l[i]!).val = 9) (hb : b.val = 0) :
    decValue (l.set i b) + 9 * 10 ^ i = decValue l := by
  have hs := decValue_set l i b h
  rw [h9, hb] at hs
  omega

/-- Spec-level mirror of the guarded drop-digit read `digits[round_idx-1]`
    (0 when the index is at/past the digit count `n`). -/
def dropDigitVal (l : List Std.U8) (n rid : Nat) : Nat :=
  if rid - 1 < n then (l[rid - 1]!).val else 0

/-- Post-state contract of the carry loop — and of `fmt_round_half_up` in
    the rounding case. `d0`/`n` = pre-state digits/count, `rid` = index of
    the first KEPT digit, `(n', ds')` = returned count/digits. -/
def carryPost (d0 : List Std.U8) (n rid : Nat)
    (n' : Std.Usize) (ds' : Std.Array Std.U8 80#usize) : Prop :=
  decValue ds'.val = decValue d0 + 10 ^ rid ∧
  (∀ j, j < rid → ds'.val[j]! = d0[j]!) ∧
  (∀ j, j < 80 → (ds'.val[j]!).val ≤ 9) ∧
  n ≤ n'.val ∧ n'.val ≤ n + 1 ∧
  (∀ j, n'.val ≤ j → j < 80 → ds'.val[j]! = 0#u8) ∧
  (n'.val = n ∨ (ds'.val[n'.val - 1]!).val ≠ 0)

set_option maxHeartbeats 4000000 in
/-- Carry-propagation loop: starting with carry 1 parked at `ridx ≤ n`
    over a digit buffer whose tail (≥ n) is zero, the loop terminates by
    carry-death at index ≤ n (never at the 80 boundary) and realises
    `carryPost` — the value grows by exactly 10^ridx. -/
theorem round_carry_loop_spec
    (digits : Std.Array Std.U8 80#usize) (n ridx : Std.Usize)
    (hn78 : n.val ≤ 78) (hridn : ridx.val ≤ n.val)
    (hdig : ∀ j, j < 80 → (digits.val[j]!).val ≤ 9)
    (hzero : ∀ j, n.val ≤ j → j < 80 → digits.val[j]! = 0#u8) :
    eip1559.fmt_round_half_up_loop digits n 1#u8 ridx
      ⦃ p => carryPost digits.val n.val ridx.val p.1 p.2 ⦄ := by
  have hlds : digits.val.length = 80 := by simp
  unfold eip1559.fmt_round_half_up_loop
  apply Aeneas.Std.loop.spec_decr_nat
    (measure := fun (s : Std.Array Std.U8 80#usize × Std.Usize × Std.U8 ×
                      Std.Usize) => 80 - s.2.2.2.val)
    (inv := fun (s : Std.Array Std.U8 80#usize × Std.Usize × Std.U8 ×
                     Std.Usize) =>
       (s.2.2.1.val = 1 ∧ s.2.1 = n ∧
        ridx.val ≤ s.2.2.2.val ∧ s.2.2.2.val ≤ n.val ∧
        decValue s.1.val + 10 ^ s.2.2.2.val
          = decValue digits.val + 10 ^ ridx.val ∧
        (∀ j, j < ridx.val → s.1.val[j]! = digits.val[j]!) ∧
        (∀ j, j < 80 → (s.1.val[j]!).val ≤ 9) ∧
        (∀ j, s.2.2.2.val ≤ j → j < 80 → s.1.val[j]! = digits.val[j]!))
       ∨
       (s.2.2.1.val = 0 ∧ carryPost digits.val n.val ridx.val s.2.1 s.1))
  · rintro ⟨ds, nn, cc, ii⟩ hinv
    simp only at hinv
    have hlds' : ds.val.length = 80 := by simp
    unfold eip1559.fmt_round_half_up_loop.body
    rcases hinv with ⟨hc1, hnn, hril, hiln, hval, hpre, hd9, hsuf⟩ |
                     ⟨hc0, hpost⟩
    · -- phase A: carry = 1, live index ≤ n
      subst hnn
      have hii80 : ii.val < 80 := by omega
      step*
      · -- side condition: digit + carry fits in a u8 (digit ≤ 9, carry = 1)
        have hi2b : i2.val ≤ 9 := by
          rw [i2_post, ← getElem!_pos _ _ (by rw [hlds']; omega)]
          exact hd9 ii.val hii80
        scalar_tac
      · -- ii ≥ n: the carry crossed the top digit — write 1, grow n, die
        have hieq : ii.val = nn.val := by scalar_tac
        have hds0 : ds.val[ii.val]! = 0#u8 := by
          rw [hsuf ii.val (Nat.le_refl _) hii80]
          exact hzero ii.val (by omega) hii80
        have hds0v : (ds.val[ii.val]!).val = 0 := by rw [hds0]; simp
        have hi2! : i2 = ds.val[ii.val]! := by
          rw [i2_post, ← getElem!_pos _ _ (by rw [hlds']; omega)]
        have hi2v : i2.val = 0 := by rw [hi2!]; exact hds0v
        have hsumv : sum.val = 1 := by omega
        have hi3v : i3.val = 1 := by omega
        have hcarry0 : carry1.val = 0 := by omega
        have hset : (index_mut_back i3).val = ds.val.set ii.val i3 := by
          rw [__post2, Array.set_val_eq]
        have hlen1 : (index_mut_back i3).val.length = 80 := by simp
        have hseti3 : (ds.val.set ii.val i3)[ii.val]! = i3 :=
          List.set_getElem!_eq _ _ _ _ ⟨by rw [hlds']; omega, rfl⟩
        have hi4i3 : i4 = i3 := by
          rw [i4_post, ← getElem!_pos _ _ (by rw [hlen1]; omega), hset]
          exact hseti3
        split
        · -- written digit 1 ≠ 0: n grows to ii + 1, carry is dead
          step*
          refine ⟨Or.inr ⟨hcarry0, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩, by omega⟩
          · rw [hset, decValue_set_incr ds.val ii.val i3
                  (by rw [hlds']; omega) (by omega)]
            exact hval
          · intro j hj
            rw [hset,
                List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega)]
            exact hpre j hj
          · intro j hj
            rw [hset]
            rcases eq_or_ne j ii.val with hje | hjn
            · subst hje
              rw [hseti3]
              omega
            · rw [List.set_getElem!_ne _ _ _ _
                    (by simp only [Nat.not_eq]; omega)]
              exact hd9 j hj
          · omega
          · omega
          · intro j hjn1 hj80
            rw [hset,
                List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega),
                hsuf j (by omega) hj80]
            exact hzero j (by omega) hj80
          · right
            have hn1i : n1.val - 1 = ii.val := by omega
            rw [hset, hn1i, hseti3]
            omega
        · -- (unreachable) the written digit was 0
          exfalso
          have hne : ¬(i4 != 0#u8) = true := by assumption
          have h0 : i4.val = 0 := by simpa using hne
          have h1 : i4.val = i3.val := by rw [hi4i3]
          omega
      · -- ii < n: interior write — carry survives on a 9, dies otherwise
        have hilt : ii.val < nn.val := by scalar_tac
        have hi2! : i2 = ds.val[ii.val]! := by
          rw [i2_post, ← getElem!_pos _ _ (by rw [hlds']; omega)]
        have hi2ds : i2.val = (ds.val[ii.val]!).val := by rw [hi2!]
        have hi2v9 : i2.val ≤ 9 := by rw [hi2ds]; exact hd9 ii.val hii80
        have hsumv : sum.val = i2.val + 1 := by omega
        have hset : (index_mut_back i3).val = ds.val.set ii.val i3 := by
          rw [__post2, Array.set_val_eq]
        have hseti3 : (ds.val.set ii.val i3)[ii.val]! = i3 :=
          List.set_getElem!_eq _ _ _ _ ⟨by rw [hlds']; omega, rfl⟩
        rcases Nat.lt_or_ge i2.val 9 with h8 | h9
        · -- digit ≤ 8: carry dies here — bank the postcondition (phase B)
          have hi3v : i3.val = i2.val + 1 := by
            rw [i3_post, hsumv, Nat.mod_eq_of_lt (by omega)]
          have hcarry0 : carry1.val = 0 := by
            rw [carry1_post, hsumv, Nat.div_eq_of_lt (by omega)]
          refine ⟨Or.inr ⟨hcarry0, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩, by omega⟩
          · rw [hset, decValue_set_incr ds.val ii.val i3
                  (by rw [hlds']; omega) (by omega)]
            exact hval
          · intro j hj
            rw [hset,
                List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega)]
            exact hpre j hj
          · intro j hj
            rw [hset]
            rcases eq_or_ne j ii.val with hje | hjn
            · subst hje
              rw [hseti3]
              omega
            · rw [List.set_getElem!_ne _ _ _ _
                    (by simp only [Nat.not_eq]; omega)]
              exact hd9 j hj
          · exact Nat.le_refl _
          · omega
          · intro j hjn hj80
            rw [hset,
                List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega),
                hsuf j (by omega) hj80]
            exact hzero j hjn hj80
          · exact Or.inl rfl
        · -- digit = 9: rolls to 0, the ulp re-parks at ii + 1 (stay phase A)
          have h9e : i2.val = 9 := by omega
          have hi3v : i3.val = 0 := by rw [i3_post]; omega
          have hcarry1 : carry1.val = 1 := by rw [carry1_post]; omega
          refine ⟨Or.inl ⟨hcarry1, by omega, by omega, ?_, ?_, ?_, ?_⟩,
                  by omega⟩
          · rw [hset]
            have hcar := decValue_set_carry ds.val ii.val i3
              (by rw [hlds']; omega) (by omega) hi3v
            have hpow : (10 : ℕ) ^ (ii.val + 1) = 10 ^ ii.val * 10 :=
              pow_succ 10 ii.val
            rw [i4_post, hpow]
            omega
          · intro j hj
            rw [hset,
                List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega)]
            exact hpre j hj
          · intro j hj
            rw [hset]
            rcases eq_or_ne j ii.val with hje | hjn
            · subst hje
              rw [hseti3]
              omega
            · rw [List.set_getElem!_ne _ _ _ _
                    (by simp only [Nat.not_eq]; omega)]
              exact hd9 j hj
          · intro j hji hj80
            rw [hset,
                List.set_getElem!_ne _ _ _ _ (by simp only [Nat.not_eq]; omega)]
            exact hsuf j (by omega) hj80
    · -- phase B: carry = 0 — the loop head exits with the banked post
      step*
  · -- entry state: phase A with the ulp parked at ridx
    refine Or.inl ⟨?_, rfl, Nat.le_refl _, hridn, rfl, fun j _ => rfl, hdig,
                   fun j _ _ => rfl⟩
    simp

/-- **Functional spec**: `fmt_round_half_up` is exact round-half-up at the
    display precision. In the rounding case (there IS a dropped position and
    its top dropped digit is ≥ 5) the digit value grows by exactly one ulp
    of the first kept position (`carryPost`); otherwise digits and count are
    returned untouched. Preconditions = the `extract_digits` post-state on a
    fresh zeroed buffer. -/
theorem round_carry_spec
    (digits : Std.Array Std.U8 80#usize) (n total_decimals frac : Std.Usize)
    (hn1 : 1 ≤ n.val) (hn78 : n.val ≤ 78)
    (hdig : ∀ i, i < n.val → (digits.val[i]!).val ≤ 9)
    (hzero : ∀ i, n.val ≤ i → i < 80 → digits.val[i]! = 0#u8) :
    eip1559.fmt_round_half_up digits n total_decimals frac
      ⦃ p =>
        (frac.val < total_decimals.val ∧
           5 ≤ dropDigitVal digits.val n.val (total_decimals.val - frac.val) →
           carryPost digits.val n.val (total_decimals.val - frac.val) p.1 p.2) ∧
        (¬(frac.val < total_decimals.val ∧
           5 ≤ dropDigitVal digits.val n.val (total_decimals.val - frac.val)) →
           p.1 = n ∧ p.2 = digits) ⦄ := by
  have hlds : digits.val.length = 80 := by simp
  have hdig80 : ∀ j, j < 80 → (digits.val[j]!).val ≤ 9 := by
    intro j hj
    rcases Nat.lt_or_ge j n.val with hjn | hjn
    · exact hdig j hjn
    · rw [hzero j hjn hj]; simp
  unfold eip1559.fmt_round_half_up
  split
  · -- total_decimals > frac: the drop-digit read is live
    rename_i hgt
    step*
    split
    · -- round_idx - 1 < n: the drop digit is a real stored digit
      step*
      · -- drop digit ≥ 5: dispatch to the carry loop
        have hi_lt : i.val < n.val := by scalar_tac
        have hge5 : 5 ≤ drop_digit.val := by scalar_tac
        have hridn : round_idx.val ≤ n.val := by omega
        have hdd : drop_digit = digits.val[i.val]! := by
          rw [drop_digit_post, ← getElem!_pos _ _ (by rw [hlds]; omega)]
        apply Aeneas.Std.WP.spec_mono
          (round_carry_loop_spec digits n round_idx hn78 hridn hdig80 hzero)
        intro p hp
        constructor
        · intro _
          rw [← round_idx_post1]
          exact hp
        · intro hncond
          exfalso
          apply hncond
          refine ⟨by scalar_tac, ?_⟩
          simp only [dropDigitVal]
          rw [if_pos (by omega)]
          have hidx : total_decimals.val - frac.val - 1 = i.val := by omega
          rw [hidx, ← hdd]
          exact hge5
      · -- drop digit < 5: identity
        have hi_lt : i.val < n.val := by scalar_tac
        have hlt5 : drop_digit.val < 5 := by scalar_tac
        have hdd : drop_digit = digits.val[i.val]! := by
          rw [drop_digit_post, ← getElem!_pos _ _ (by rw [hlds]; omega)]
        refine ⟨fun hcond => ?_, by intros; trivial⟩
        exfalso
        rcases hcond with ⟨-, h5⟩
        simp only [dropDigitVal] at h5
        rw [if_pos (by omega)] at h5
        have hidx : total_decimals.val - frac.val - 1 = i.val := by omega
        rw [hidx, ← hdd] at h5
        omega
    · -- drop-digit read past n: structural zero, identity
      have hge : n.val ≤ i.val := by scalar_tac
      step*
      refine ⟨fun hcond => ?_, by intros; trivial⟩
      exfalso
      rcases hcond with ⟨-, h5⟩
      simp only [dropDigitVal] at h5
      rw [if_neg (by omega)] at h5
      omega
  · -- total_decimals ≤ frac: structural no-round
    rename_i hle
    simp only [WP.spec_ok]
    exact ⟨fun hcond => absurd hcond.1 (by scalar_tac),
           fun _ => ⟨trivial, trivial⟩⟩

end RoundCarrySpec
