/- §33 — format_decimal Track-1 M6: `fmt_trim_frac` functional correctness
   over the committed Aeneas extraction
   (`Extracted/FormatDecimal/Funs.lean`, regenerated by
   `make extract-format-decimal`).

   THE RESULT (`trim_frac_spec`): with n ≤ 80 (any post-round digit count),
   `fmt_trim_frac digits n total_decimals frac` succeeds and returns the
   emitted-fraction count f' with
     (a) f' ≤ frac;
     (b) f' ≠ 0 → the digit displayed at fractional position f' is nonzero;
     (c) every fractional position in (f', frac] displays a zero —
   i.e. f' is exactly the largest position ≤ frac whose displayed digit is
   nonzero (0 when the whole displayed fraction is zeros). "Displayed digit
   at position pos" is `fracDigitVal`: digits[total_decimals - pos] when
   that index is a stored digit (pos ≤ total_decimals ∧ index < n), else
   the structural zero — the spec-level mirror of the guarded read in the
   Rust source (positions past the value's digits, and positions finer than
   the value has decimals, are structural zeros).

   Proof pattern: `Aeneas.Std.loop.spec_decr_nat`, measure = frac_emit
   (strictly decreasing backward scan), invariant = "everything strictly
   above the cursor displays zero". The `saturating_sub` digit-index is
   characterised by `usize_saturating_sub_val` (Nat subtraction is already
   saturating; the BitVec.ofNat round-trips below 2^numBits).

   NOTE (axiom discipline): no `bv_tac` (`bv_decide` would inject a
   native-computation axiom the §33 gate rejects) — the closure is exactly
   [propext, Classical.choice, Quot.sound].

   Fourth milestone of the format_decimal end-to-end WYSIWYS spec (work-todo
   FV frontier, Track 1): M7 composes extract/round/trim with `fmt_emit`
   into "the emitted string parses back to round-half-up(v/10^d, f)". -/
import Aeneas
import Extracted.FormatDecimal.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

namespace TrimFracSpec

open pqsigner_tx_core

/-- `Usize.saturating_sub` is Nat subtraction (which already saturates). -/
theorem usize_saturating_sub_val (x y : Std.Usize) :
    (core.num.Usize.saturating_sub x y).val = x.val - y.val := by
  have hx : x.val < 2 ^ UScalarTy.Usize.numBits := x.hBounds
  simp only [core.num.Usize.saturating_sub, UScalar.saturating_sub,
             UScalar.val, BitVec.toNat_ofNat, Nat.zero_max]
  exact Nat.mod_eq_of_lt (by omega)

/-- Step spec for the `lift`ed `saturating_sub` (no `@[step]` lemma
    upstream for the saturating ops). -/
theorem saturating_sub_spec (x y : Std.Usize) :
    (lift (core.num.Usize.saturating_sub x y) : Result Std.Usize)
      ⦃ z => z.val = x.val - y.val ⦄ := by
  simp only [lift, WP.spec_ok]
  exact usize_saturating_sub_val x y

/-- The digit DISPLAYED at fractional position `pos` (1-based, counted from
    the decimal point): `digits[total_decimals - pos]` when that is a stored
    digit, else the structural zero. -/
def fracDigitVal (l : List Std.U8) (n td pos : Nat) : Nat :=
  if pos ≤ td ∧ td - pos < n then (l[td - pos]!).val else 0

set_option maxHeartbeats 4000000 in
/-- Backward-scan loop: starting at cursor `fe ≤ frac` with everything
    strictly above `fe` already known to display zero, the loop returns the
    largest position ≤ fe whose displayed digit is nonzero (0 if none). -/
theorem trim_frac_loop_spec
    (digits : Std.Array Std.U8 80#usize) (n total_decimals frac : Std.Usize)
    (hn80 : n.val ≤ 80)
    (fe : Std.Usize) (hfe : fe.val ≤ frac.val)
    (habove : ∀ pos, fe.val < pos → pos ≤ frac.val →
       fracDigitVal digits.val n.val total_decimals.val pos = 0) :
    eip1559.fmt_trim_frac_loop digits n total_decimals fe
      ⦃ f => f.val ≤ frac.val ∧
             (f.val ≠ 0 →
                fracDigitVal digits.val n.val total_decimals.val f.val ≠ 0) ∧
             (∀ pos, f.val < pos → pos ≤ frac.val →
                fracDigitVal digits.val n.val total_decimals.val pos = 0) ⦄ := by
  have hlds : digits.val.length = 80 := by simp
  unfold eip1559.fmt_trim_frac_loop
  apply Aeneas.Std.loop.spec_decr_nat
    (measure := fun (fe1 : Std.Usize) => fe1.val)
    (inv := fun (fe1 : Std.Usize) =>
       fe1.val ≤ frac.val ∧
       ∀ pos, fe1.val < pos → pos ≤ frac.val →
         fracDigitVal digits.val n.val total_decimals.val pos = 0)
  · rintro fe1 ⟨hfe1, hab⟩
    unfold eip1559.fmt_trim_frac_loop.body
    step*
    -- the fe1 = 0 exit and the 0 ≠ 0 dead branches are closed by `step*`;
    -- one goal remains: fe1 > 0, stuck at the saturating_sub lift
    have hfepos : 1 ≤ fe1.val := by scalar_tac
    let* ⟨digit_idx, hidx⟩ ← saturating_sub_spec
    split
    · -- total_decimals ≥ fe1: the position is not finer than the value
      have htd : fe1.val ≤ total_decimals.val := by scalar_tac
      split
      · -- digit_idx < n: a real stored digit
        have hidxn : digit_idx.val < n.val := by scalar_tac
        step*
        · -- d ≠ 0: stop here — this position must be emitted
          have hdv : d = digits.val[digit_idx.val]! := by
            rw [d_post, ← getElem!_pos _ _ (by rw [hlds]; omega)]
          have hne : (d != 0#u8) = true := by assumption
          have hdne : d.val ≠ 0 := by simpa using hne
          refine ⟨hfe1, fun _ => ?_, hab⟩
          simp only [fracDigitVal]
          rw [if_pos ⟨htd, by omega⟩, ← hidx, ← hdv]
          exact hdne
        · -- d = 0: this position trims away — move the cursor down
          have hdv : d = digits.val[digit_idx.val]! := by
            rw [d_post, ← getElem!_pos _ _ (by rw [hlds]; omega)]
          have hz : ¬(d != 0#u8) = true := by assumption
          have hd0 : d.val = 0 := by simpa using hz
          refine ⟨by omega, ?_, by omega⟩
          intro pos hlt hle
          rcases eq_or_ne pos fe1.val with hpe | hpn
          · subst hpe
            simp only [fracDigitVal]
            rw [if_pos ⟨htd, by omega⟩, ← hidx, ← hdv]
            exact hd0
          · exact hab pos (by omega) hle
      · -- digit_idx ≥ n: past the value's digits — structural zero, trim
        have hidxn : n.val ≤ digit_idx.val := by scalar_tac
        step*
        refine ⟨by omega, ?_, by omega⟩
        intro pos hlt hle
        rcases eq_or_ne pos fe1.val with hpe | hpn
        · subst hpe
          simp only [fracDigitVal]
          rw [if_neg (by intro hc; omega)]
        · exact hab pos (by omega) hle
    · -- total_decimals < fe1: finer than the value has decimals — trim
      have htd : total_decimals.val < fe1.val := by scalar_tac
      step*
      refine ⟨by omega, ?_, by omega⟩
      intro pos hlt hle
      rcases eq_or_ne pos fe1.val with hpe | hpn
      · subst hpe
        simp only [fracDigitVal]
        rw [if_neg (by intro hc; omega)]
      · exact hab pos (by omega) hle
  · exact ⟨hfe, habove⟩

/-- **Functional spec**: `fmt_trim_frac` returns the largest fractional
    position f' ≤ frac whose DISPLAYED digit (`fracDigitVal` — the guarded
    `digits[total_decimals - pos]` read, structural zero past the value) is
    nonzero, and 0 when the displayed fraction is all zeros; every position
    in (f', frac] displays a zero, so trimming them is value-preserving. -/
theorem trim_frac_spec
    (digits : Std.Array Std.U8 80#usize) (n total_decimals frac : Std.Usize)
    (hn80 : n.val ≤ 80) :
    eip1559.fmt_trim_frac digits n total_decimals frac
      ⦃ f => f.val ≤ frac.val ∧
             (f.val ≠ 0 →
                fracDigitVal digits.val n.val total_decimals.val f.val ≠ 0) ∧
             (∀ pos, f.val < pos → pos ≤ frac.val →
                fracDigitVal digits.val n.val total_decimals.val pos = 0) ⦄ := by
  unfold eip1559.fmt_trim_frac
  exact trim_frac_loop_spec digits n total_decimals frac hn80 frac
    (Nat.le_refl _) (fun pos h1 h2 => absurd h2 (by omega))

end TrimFracSpec
