-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Extracted.Decode.Types
import Extracted.Rlp.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open pqsigner_tx_core

/- The template axiomatized four total core stdlib helpers (ok_or, Try.branch,
   FromResidual.from_residual, Slice.first). Following the `into_iter` pattern
   in Extracted/Rlp/FunsExternal.lean we give each a DEF so the decode_item
   proof carries no content axioms.

   History: the original Rust used `acc.checked_shl(8)`, whose REAL rustc
   semantics (None only when rhs >= BITS; bits shifted out the top silently
   DISCARDED) make `decode_length_be` wrap on a 32-bit usize for
   len_of_len >= 5 — a parse-desync bug on thumbv8m found while proving the
   rank-8 spec (the spec was only provable against a deliberately-stricter
   model). The Rust was fixed 2026-06-12 to `acc.checked_mul(256)`, which
   Aeneas maps to the stdlib `Usize.checked_mul` — no hand model needed. -/

/-- [core::option::{core::option::Option<T>}::ok_or]:
    Source: '/rustc/library/core/src/option.rs', lines 1334:4-1334:73
    Name pattern: [core::option::{core::option::Option<@T>}::ok_or]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::ok_or"]
def core.option.Option.ok_or
    {T : Type} {E : Type} (o : Option T) (e : E) :
    Result (core.result.Result T E) :=
  match o with
  | some x => ok (core.result.Result.Ok x)
  | none => ok (core.result.Result.Err e)

/-- [core::result::{impl core::ops::try_trait::Try for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2177:4-2177:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>>}::branch"]
def core.result.Result.Insts.CoreOpsTry_traitTry.branch
    {T : Type} {E : Type} (r : core.result.Result T E) :
    Result (core.ops.control_flow.ControlFlow
      (core.result.Result core.convert.Infallible E) T) :=
  match r with
  | core.result.Result.Ok x =>
    ok (core.ops.control_flow.ControlFlow.Continue x)
  | core.result.Result.Err e =>
    ok (core.ops.control_flow.ControlFlow.Break (core.result.Result.Err e))

/-- [core::result::{impl core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2192:4-2192:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
def
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
    (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E)
    (r : core.result.Result core.convert.Infallible E) :
    Result (core.result.Result T F) :=
  match r with
  | core.result.Result.Ok x => nomatch x
  | core.result.Result.Err e => do
    let f ← convertFromInst.from_ e
    ok (core.result.Result.Err f)



/-- [core::slice::{[T]}::first]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 155:4-155:43
    Name pattern: [core::slice::{[@T]}::first]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::first"]
def core.slice.Slice.first {T : Type} (s : Slice T) : Result (Option T) :=
  ok s.val.head?
