-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx_core]: function definitions
import Aeneas
import Extracted.Decode.Types
import Extracted.Decode.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pqsigner_tx_core

/-- [pqsigner_tx_core::rlp::decode_length_be]: loop body 0:
    Source: 'tx-core/src/rlp.rs', lines 112:4-122:1 -/
@[rust_loop_body]
def rlp.decode_length_be_loop.body
  (iter : core.slice.iter.Iter Std.U8) (acc : Std.Usize) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U8) × Std.Usize)
    (core.result.Result Std.Usize rlp.RlpError))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done (core.result.Result.Ok acc))
  | some b =>
    let o1 ← lift (Usize.checked_mul acc 256#usize)
    let r ← core.option.Option.ok_or o1 rlp.RlpError.LengthOverflow
    let cf ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let i ← lift (UScalar.cast .Usize b)
      let o2 ← lift (Usize.checked_add val i)
      let r1 ← core.option.Option.ok_or o2 rlp.RlpError.LengthOverflow
      let cf1 ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        ok (cont (iter1, val1))
      | core.ops.control_flow.ControlFlow.Break residual =>
        let r2 ←
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            Std.Usize (core.convert.FromSame rlp.RlpError) residual
        ok (done r2)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          Std.Usize (core.convert.FromSame rlp.RlpError) residual
      ok (done r1)

/-- [pqsigner_tx_core::rlp::decode_length_be]: loop 0:
    Source: 'tx-core/src/rlp.rs', lines 112:4-122:1 -/
@[rust_loop]
def rlp.decode_length_be_loop
  (iter : core.slice.iter.Iter Std.U8) (acc : Std.Usize) :
  Result (core.result.Result Std.Usize rlp.RlpError)
  := do
  loop
    (fun (iter1, acc1) => rlp.decode_length_be_loop.body iter1 acc1)
    (iter, acc)

/-- [pqsigner_tx_core::rlp::decode_length_be]:
    Source: 'tx-core/src/rlp.rs', lines 104:0-122:1 -/
def rlp.decode_length_be
  (bytes : Slice Std.U8) :
  Result (core.result.Result Std.Usize rlp.RlpError)
  := do
  let b ← core.slice.Slice.is_empty bytes
  if b
  then ok (core.result.Result.Err rlp.RlpError.NonCanonical)
  else
    let i ← Slice.index_usize bytes 0#usize
    if i = 0#u8
    then ok (core.result.Result.Err rlp.RlpError.LeadingZero)
    else
      let iter ←
        SharedASlice.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
          bytes
      rlp.decode_length_be_loop iter 0#usize

/-- [pqsigner_tx_core::rlp::decode_item]:
    Source: 'tx-core/src/rlp.rs', lines 35:0-102:1
    Visibility: public -/
def rlp.decode_item
  (input : Slice Std.U8) :
  Result (core.result.Result (rlp.Item × Std.Usize) rlp.RlpError)
  := do
  let o ← core.slice.Slice.first input
  let r ← core.option.Option.ok_or o rlp.RlpError.Truncated
  let cf ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    if val <= 127#u8
    then
      let s ←
        core.slice.index.Slice.index
          (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8) input
          { «end» := 1#usize }
      ok (core.result.Result.Ok (rlp.Item.Bytes s, 1#usize))
    else
      if val <= 183#u8
      then
        let i ← val - 128#u8
        let len ← lift (UScalar.cast .Usize i)
        let total ← 1#usize + len
        let i1 := Slice.len input
        if i1 < total
        then ok (core.result.Result.Err rlp.RlpError.Truncated)
        else
          if len = 1#usize
          then
            let i2 ← Slice.index_usize input 1#usize
            if i2 <= 127#u8
            then ok (core.result.Result.Err rlp.RlpError.NonCanonical)
            else
              let s ←
                core.slice.index.Slice.index
                  (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                  { start := 1#usize, «end» := total }
              ok (core.result.Result.Ok (rlp.Item.Bytes s, total))
          else
            let s ←
              core.slice.index.Slice.index
                (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                { start := 1#usize, «end» := total }
            ok (core.result.Result.Ok (rlp.Item.Bytes s, total))
      else
        if val <= 191#u8
        then
          let i ← val - 183#u8
          let len_of_len ← lift (UScalar.cast .Usize i)
          if len_of_len = 0#usize
          then ok (core.result.Result.Err rlp.RlpError.NonCanonical)
          else
            if len_of_len > 8#usize
            then ok (core.result.Result.Err rlp.RlpError.NonCanonical)
            else
              let i1 := Slice.len input
              let i2 ← 1#usize + len_of_len
              if i1 < i2
              then ok (core.result.Result.Err rlp.RlpError.Truncated)
              else
                let s ←
                  core.slice.index.Slice.index
                    (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                    { start := 1#usize, «end» := i2 }
                let r1 ← rlp.decode_length_be s
                let cf1 ←
                  core.result.Result.Insts.CoreOpsTry_traitTry.branch r1
                match cf1 with
                | core.ops.control_flow.ControlFlow.Continue val1 =>
                  if val1 <= 55#usize
                  then ok (core.result.Result.Err rlp.RlpError.NonCanonical)
                  else
                    let o1 ← lift (Usize.checked_add i2 val1)
                    let r2 ←
                      core.option.Option.ok_or o1 rlp.RlpError.LengthOverflow
                    let cf2 ←
                      core.result.Result.Insts.CoreOpsTry_traitTry.branch r2
                    match cf2 with
                    | core.ops.control_flow.ControlFlow.Continue val2 =>
                      let i3 := Slice.len input
                      if i3 < val2
                      then
                        ok (core.result.Result.Err rlp.RlpError.LengthOverflow)
                      else
                        let s1 ←
                          core.slice.index.Slice.index
                            (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)
                            input { start := i2, «end» := val2 }
                        ok (core.result.Result.Ok (rlp.Item.Bytes s1, val2))
                    | core.ops.control_flow.ControlFlow.Break residual =>
                      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                        (rlp.Item × Std.Usize) (core.convert.FromSame
                        rlp.RlpError) residual
                | core.ops.control_flow.ControlFlow.Break residual =>
                  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                    (rlp.Item × Std.Usize) (core.convert.FromSame
                    rlp.RlpError) residual
        else
          if val <= 247#u8
          then
            let i ← val - 192#u8
            let len ← lift (UScalar.cast .Usize i)
            let total ← 1#usize + len
            let i1 := Slice.len input
            if i1 < total
            then ok (core.result.Result.Err rlp.RlpError.Truncated)
            else
              let s ←
                core.slice.index.Slice.index
                  (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                  { start := 1#usize, «end» := total }
              ok (core.result.Result.Ok (rlp.Item.List s, total))
          else
            let i ← val - 247#u8
            let len_of_len ← lift (UScalar.cast .Usize i)
            if len_of_len = 0#usize
            then ok (core.result.Result.Err rlp.RlpError.NonCanonical)
            else
              if len_of_len > 8#usize
              then ok (core.result.Result.Err rlp.RlpError.NonCanonical)
              else
                let i1 := Slice.len input
                let i2 ← 1#usize + len_of_len
                if i1 < i2
                then ok (core.result.Result.Err rlp.RlpError.Truncated)
                else
                  let s ←
                    core.slice.index.Slice.index
                      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                      { start := 1#usize, «end» := i2 }
                  let r1 ← rlp.decode_length_be s
                  let cf1 ←
                    core.result.Result.Insts.CoreOpsTry_traitTry.branch r1
                  match cf1 with
                  | core.ops.control_flow.ControlFlow.Continue val1 =>
                    if val1 <= 55#usize
                    then ok (core.result.Result.Err rlp.RlpError.NonCanonical)
                    else
                      let o1 ← lift (Usize.checked_add i2 val1)
                      let r2 ←
                        core.option.Option.ok_or o1 rlp.RlpError.LengthOverflow
                      let cf2 ←
                        core.result.Result.Insts.CoreOpsTry_traitTry.branch r2
                      match cf2 with
                      | core.ops.control_flow.ControlFlow.Continue val2 =>
                        let i3 := Slice.len input
                        if i3 < val2
                        then
                          ok (core.result.Result.Err
                            rlp.RlpError.LengthOverflow)
                        else
                          let s1 ←
                            core.slice.index.Slice.index
                              (core.slice.index.SliceIndexRangeUsizeSlice
                              Std.U8) input { start := i2, «end» := val2 }
                          ok (core.result.Result.Ok (rlp.Item.List s1, val2))
                      | core.ops.control_flow.ControlFlow.Break residual =>
                        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                          (rlp.Item × Std.Usize) (core.convert.FromSame
                          rlp.RlpError) residual
                  | core.ops.control_flow.ControlFlow.Break residual =>
                    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
                      (rlp.Item × Std.Usize) (core.convert.FromSame
                      rlp.RlpError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      (rlp.Item × Std.Usize) (core.convert.FromSame rlp.RlpError) residual

end pqsigner_tx_core
