-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx_core]: type definitions
import Aeneas
import Extracted.Rlp.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pqsigner_tx_core

/-- [pqsigner_tx_core::rlp::Item]
    Source: 'tx-core/src/rlp.rs', lines 28:0-31:1
    Visibility: public -/
@[discriminant isize]
inductive rlp.Item where
| Bytes : Slice Std.U8 → rlp.Item
| List : Slice Std.U8 → rlp.Item

end pqsigner_tx_core
