//! Firmware-pinned membership filter for known contract-call shapes.
//!
//! A descriptor Merkle root authenticates a descriptor when the companion
//! supplies its proof, but a root alone cannot tell the secure world that the
//! companion omitted a proof for a call that *does* have a descriptor.  This
//! Bloom filter closes that downgrade: `dbgen` inserts every parsable
//! `(chain_id, contract, selector)` tuple declared by the vendored registry,
//! including formats the strict renderer refuses to compile. The firmware
//! queries the generated filter before it may fall through to a lower rung.
//!
//! False positives are safe (an unknown call is refused instead of blind-
//! signed); false negatives for generated entries are forbidden and covered by
//! the dbgen round-trip check.  The filter is not an authentication primitive:
//! it is compiled into the same secure image as `ERC7730_DESCRIPTORS_ROOT`.

use sha2::{Digest, Sha256};

/// 128 Ki-bit filter.  At the current catalogue size this keeps the false-
/// positive probability well below one in ten thousand while costing 16 KiB
/// of flash and no mutable RAM.
pub const BLOOM_BYTES: usize = 16 * 1024;
const BLOOM_BITS: u64 = (BLOOM_BYTES * 8) as u64;
/// Number of double-hashed bit positions per known call.
pub const BLOOM_HASHES: u64 = 7;

const DOMAIN: &[u8] = b"pqsigner/erc7730-known-call-v1";

/// Insert one known contract-call tuple. Host-side generator primitive; kept
/// `no_std` so the exact same hashing/indexing code is used by generation and
/// firmware lookup.
pub fn insert(
    bloom: &mut [u8; BLOOM_BYTES],
    chain_id: u64,
    contract: &[u8; 20],
    selector: &[u8; 4],
) {
    for bit in positions(chain_id, contract, selector) {
        let byte = bit / 8;
        let mask = 1u8 << (bit & 7);
        bloom[byte] |= mask;
    }
}

/// Return true when the tuple may be a registry-declared known call. `false` is a
/// definitive non-membership result for a filter generated by [`insert`].
#[must_use]
pub fn may_contain(
    bloom: &[u8; BLOOM_BYTES],
    chain_id: u64,
    contract: &[u8; 20],
    selector: &[u8; 4],
) -> bool {
    positions(chain_id, contract, selector).all(|bit| {
        let byte = bit / 8;
        let mask = 1u8 << (bit & 7);
        bloom[byte] & mask != 0
    })
}

fn positions(
    chain_id: u64,
    contract: &[u8; 20],
    selector: &[u8; 4],
) -> impl Iterator<Item = usize> {
    let mut h = Sha256::new();
    h.update(DOMAIN);
    h.update(chain_id.to_be_bytes());
    h.update(contract);
    h.update(selector);
    let digest = h.finalize();

    let h1 = u64::from_be_bytes(digest[0..8].try_into().expect("fixed SHA-256 slice"));
    // An odd step prevents a degenerate zero/even cycle over the power-of-two
    // bit count. This is a public membership filter, not keyed hashing.
    let h2 = u64::from_be_bytes(digest[8..16].try_into().expect("fixed SHA-256 slice")) | 1;

    (0..BLOOM_HASHES).map(move |i| {
        h1.wrapping_add(i.wrapping_mul(h2))
            .wrapping_rem(BLOOM_BITS) as usize
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inserted_tuple_is_never_a_false_negative() {
        let mut bloom = [0u8; BLOOM_BYTES];
        let contract = [0xabu8; 20];
        let selector = [0x12, 0x34, 0x56, 0x78];
        insert(&mut bloom, 1, &contract, &selector);
        assert!(may_contain(&bloom, 1, &contract, &selector));
    }

    #[test]
    fn tuple_components_are_domain_separating_inputs() {
        let mut bloom = [0u8; BLOOM_BYTES];
        let contract = [0xabu8; 20];
        let selector = [0x12, 0x34, 0x56, 0x78];
        insert(&mut bloom, 1, &contract, &selector);

        let mut other_contract = contract;
        other_contract[19] ^= 1;
        let mut other_selector = selector;
        other_selector[3] ^= 1;
        assert!(!may_contain(&bloom, 2, &contract, &selector));
        assert!(!may_contain(&bloom, 1, &other_contract, &selector));
        assert!(!may_contain(&bloom, 1, &contract, &other_selector));
    }
}
