-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx_core]: function definitions
import Aeneas
import Extracted.Rlp.Types
import Extracted.Rlp.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pqsigner_tx_core

/-- [pqsigner_tx_core::rlp::bytes_to_u64]: loop body 0:
    Source: 'tx-core/src/rlp.rs', lines 171:4-173:5
    Visibility: public -/
@[rust_loop_body]
def rlp.bytes_to_u64_loop0.body
  (iter : core.slice.iter.Iter Std.U8) (acc : Std.U64) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U8) × Std.U64) Std.U64)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done acc)
  | some b =>
    let i ← acc <<< 8#i32
    let i1 ← lift (UScalar.cast .U64 b)
    let acc1 ← lift (i ||| i1)
    ok (cont (iter1, acc1))

/-- [pqsigner_tx_core::rlp::bytes_to_u64]: loop 0:
    Source: 'tx-core/src/rlp.rs', lines 171:4-173:5
    Visibility: public -/
@[rust_loop]
def rlp.bytes_to_u64_loop0
  (iter : core.slice.iter.Iter Std.U8) (acc : Std.U64) : Result Std.U64 := do
  loop
    (fun (iter1, acc1) => rlp.bytes_to_u64_loop0.body iter1 acc1)
    (iter, acc)

/-- [pqsigner_tx_core::rlp::bytes_to_u64]: loop body 1:
    Source: 'tx-core/src/rlp.rs', lines 171:4-173:5
    Visibility: public -/
@[rust_loop_body]
def rlp.bytes_to_u64_loop1.body
  (iter : core.slice.iter.Iter Std.U8) (acc : Std.U64) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U8) × Std.U64) Std.U64)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done acc)
  | some b =>
    let i ← acc <<< 8#i32
    let i1 ← lift (UScalar.cast .U64 b)
    let acc1 ← lift (i ||| i1)
    ok (cont (iter1, acc1))

/-- [pqsigner_tx_core::rlp::bytes_to_u64]: loop 1:
    Source: 'tx-core/src/rlp.rs', lines 171:4-173:5
    Visibility: public -/
@[rust_loop]
def rlp.bytes_to_u64_loop1
  (iter : core.slice.iter.Iter Std.U8) (acc : Std.U64) : Result Std.U64 := do
  loop
    (fun (iter1, acc1) => rlp.bytes_to_u64_loop1.body iter1 acc1)
    (iter, acc)

/-- [pqsigner_tx_core::rlp::bytes_to_u64]:
    Source: 'tx-core/src/rlp.rs', lines 163:0-175:1
    Visibility: public -/
def rlp.bytes_to_u64
  (bytes : Slice Std.U8) :
  Result (core.result.Result Std.U64 rlp.RlpError)
  := do
  let i := Slice.len bytes
  if i > 8#usize
  then ok (core.result.Result.Err rlp.RlpError.IntTooLarge)
  else
    let b ← core.slice.Slice.is_empty bytes
    if b
    then
      let iter ←
        SharedASlice.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
          bytes
      let acc ← rlp.bytes_to_u64_loop0 iter 0#u64
      ok (core.result.Result.Ok acc)
    else
      let i1 ← Slice.index_usize bytes 0#usize
      if i1 = 0#u8
      then ok (core.result.Result.Err rlp.RlpError.LeadingZero)
      else
        let iter ←
          SharedASlice.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
            bytes
        let acc ← rlp.bytes_to_u64_loop1 iter 0#u64
        ok (core.result.Result.Ok acc)

/-- [pqsigner_tx_core::rlp::bytes_to_u256]:
    Source: 'tx-core/src/rlp.rs', lines 179:0-190:1
    Visibility: public -/
def rlp.bytes_to_u256
  (bytes : Slice Std.U8) :
  Result (core.result.Result (Array Std.U8 32#usize) rlp.RlpError)
  := do
  let i := Slice.len bytes
  if i > 32#usize
  then ok (core.result.Result.Err rlp.RlpError.IntTooLarge)
  else
    let b ← core.slice.Slice.is_empty bytes
    if b
    then
      let out := Array.repeat 32#usize 0#u8
      let i1 := Slice.len bytes
      let off ← 32#usize - i1
      let (s, index_mut_back) ←
        core.array.Array.index_mut (core.ops.index.IndexMutSlice
          (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) out
          { start := off }
      let s1 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s bytes
      let out1 := index_mut_back s1
      ok (core.result.Result.Ok out1)
    else
      let i1 ← Slice.index_usize bytes 0#usize
      if i1 = 0#u8
      then ok (core.result.Result.Err rlp.RlpError.LeadingZero)
      else
        let out := Array.repeat 32#usize 0#u8
        let i2 := Slice.len bytes
        let off ← 32#usize - i2
        let (s, index_mut_back) ←
          core.array.Array.index_mut (core.ops.index.IndexMutSlice
            (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) out
            { start := off }
        let s1 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s bytes
        let out1 := index_mut_back s1
        ok (core.result.Result.Ok out1)

end pqsigner_tx_core
