-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx_core]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Extracted.Rlp.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open pqsigner_tx_core

/-- [core::slice::iter::{impl core::iter::traits::collect::IntoIterator<&'a T, core::slice::iter::Iter<'a, T>> for &'a [T]}::into_iter]:
    Source: '/rustc/library/core/src/slice/iter.rs', lines 23:4-23:37
    Name pattern: [core::slice::iter::{core::iter::traits::collect::IntoIterator<&'a [@T], &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter]
    Visibility: public -/
@[rust_fun
  "core::slice::iter::{core::iter::traits::collect::IntoIterator<&'a [@T], &'a @T, core::slice::iter::Iter<'a, @T>>}::into_iter"]
-- `&[T]::into_iter()` is not modeled in Aeneas Std (only the Vec variant is),
-- so the template axiomatized it. It is semantically `Slice.iter` — wrap the
-- slice into an `Iter` at index 0 — so we give it that DEF (no content axiom),
-- matching core.slice.iter.Slice.iter in Std/SliceIter.lean.
def
  SharedASlice.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
  {T : Type} (s : Slice T) : Result (core.slice.iter.Iter T) := ok ⟨ s, 0 ⟩

