-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pqsigner_tx_core

/-- [pqsigner_tx_core::rlp::RlpError]
    Source: 'tx-core/src/rlp.rs', lines 8:0-23:1
    Visibility: public -/
@[discriminant isize]
inductive rlp.RlpError where
| Truncated : rlp.RlpError
| NonCanonical : rlp.RlpError
| LengthOverflow : rlp.RlpError
| UnexpectedType : rlp.RlpError
| LeadingZero : rlp.RlpError
| IntTooLarge : rlp.RlpError

end pqsigner_tx_core
