#!/usr/bin/env python3
"""verify-kani-census — a source-generated Kani harness census (F11, 2026-07-16).

THE GAP (FV review finding F11). The published Kani numbers ("148 harnesses /
25 files", "140 in 19 mutation-enrolled files, 8 in 6 outside") were a
hand-maintained prose count (docs + a stale `gate_enforcement.json` note said
"93 harnesses across 17 files"). `kani_mutations.json` is a MUTATION manifest —
it deliberately lists only the load-bearing harnesses that carry an anti-vacuity
mutation, so it can never encode the full 148/25 census. Nothing regenerated the
census from source, so it silently drifted and could not tell you when a new
security-bearing harness landed with no mutation coverage.

THIS GATE regenerates the census from the git-tracked sources (counting
`#[kani::proof]` attributes — robust to `#[kani::unwind(N)]`/comment lines
between the attribute and `fn`), derives the mutation-enrolled vs outside split
from `kani_mutations.json`, cross-checks the manifest for rot (every mutation's
file + harness must still exist), and diffs it all against a committed lockfile
(`scripts/kani_census.lock.json`). Pure Python — NO `cargo kani` — so it runs on
every PR as the fast standing census, while the slow `verify-kani-mutation`
(which actually runs Kani) stays nightly.

Usage:
  kani_census.py --check     regenerate + diff vs the lock; FAIL on drift (CI default)
  kani_census.py --write     regenerate + write the lock (after a conscious change)
  kani_census.py --list      print the human census tables
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
MANIFEST = SCRIPT_DIR / "kani_mutations.json"
LOCK = SCRIPT_DIR / "kani_census.lock.json"

PROOF_ATTR = re.compile(r"#\[kani::proof")
FN_DECL = re.compile(r"\bfn\s+([A-Za-z_][A-Za-z0-9_]*)")


def git_tracked_rs() -> list[str]:
    out = subprocess.run(["git", "ls-files", "*.rs"], cwd=str(REPO_ROOT),
                         capture_output=True, text=True, check=True).stdout
    return sorted(l for l in out.splitlines() if l.strip())


def harnesses_in(text: str) -> list[str]:
    """Harness fn names in a file: each `#[kani::proof]` binds to the NEXT `fn
    NAME`, scanning past `#[kani::unwind(...)]`/comment/blank lines between them."""
    names: list[str] = []
    pending = False
    for line in text.splitlines():
        if PROOF_ATTR.search(line):
            pending = True
            continue
        if pending:
            m = FN_DECL.search(line)
            if m:
                names.append(m.group(1))
                pending = False
    return names


def generate() -> dict:
    files: dict[str, int] = {}
    file_harnesses: dict[str, list[str]] = {}
    for rel in git_tracked_rs():
        p = REPO_ROOT / rel
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        n = len(PROOF_ATTR.findall(text))
        if n:
            files[rel] = n
            file_harnesses[rel] = harnesses_in(text)

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    muts = manifest.get("mutations", [])
    enrolled_files = sorted({m["file"] for m in muts})
    enrolled_harnesses = sorted({f'{m["crate"]}::{m["harness"]}' for m in muts})
    tiers: dict[str, int] = {}
    for m in muts:
        tiers[m.get("tier", "?")] = tiers.get(m.get("tier", "?"), 0) + 1

    total_harnesses = sum(files.values())
    harnesses_in_enrolled = sum(c for f, c in files.items() if f in set(enrolled_files))
    outside_files = sorted(f for f in files if f not in set(enrolled_files))
    harnesses_outside = sum(files[f] for f in outside_files)

    return {
        "schema": "fv-kani-census/v1",
        "note": "F11 (2026-07-16). Generated by scripts/kani_census.py --write from git-tracked "
                "sources (count of #[kani::proof]). kani_mutations.json is the MUTATION manifest "
                "(load-bearing harnesses only); this lock is the FULL census + the enrolled/outside "
                "split. Run `make verify-kani-census` (--check) on every PR; regenerate with --write.",
        "files": files,
        "totals": {
            "total_files": len(files),
            "total_harnesses": total_harnesses,
            "mutation_enrolled_files": len(enrolled_files),
            "harnesses_in_enrolled_files": harnesses_in_enrolled,
            "files_outside_mutation": len(outside_files),
            "harnesses_outside_mutation": harnesses_outside,
            "mutation_groups_total": len(muts),
            "mutation_groups_by_tier": tiers,
            "distinct_enrolled_harnesses": len(enrolled_harnesses),
        },
        "files_outside_mutation": outside_files,
        "_file_harnesses": file_harnesses,
    }


def manifest_rot(census: dict) -> list[str]:
    """Static analogue of check_kani_mutations.py's runtime materiality guard:
    every mutation entry's file must exist and contain a #[kani::proof] fn <harness>."""
    fails = []
    fh = census["_file_harnesses"]
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    for m in manifest.get("mutations", []):
        f, h = m["file"], m["harness"]
        if not (REPO_ROOT / f).exists():
            fails.append(f"manifest `{m['id']}`: file {f} does not exist (deleted/renamed).")
        elif h not in fh.get(f, []):
            fails.append(f"manifest `{m['id']}`: no `#[kani::proof] fn {h}` in {f} "
                         f"(renamed/deleted harness — the mutation would misfire before Kani runs).")
    return fails


def _canonical(c: dict) -> dict:
    """The comparable subset (drop the bulky _file_harnesses helper index)."""
    return {k: v for k, v in c.items() if k != "_file_harnesses"}


def do_check() -> int:
    census = generate()
    rot = manifest_rot(census)
    if rot:
        print(f"FAIL: kani_mutations.json references {len(rot)} missing file/harness:", file=sys.stderr)
        for r in rot:
            print(f"  - {r}", file=sys.stderr)
        return 2
    if not LOCK.exists():
        print(f"FAIL: {LOCK} missing — run `kani_census.py --write` to create the census lock.", file=sys.stderr)
        return 1
    lock = json.loads(LOCK.read_text(encoding="utf-8"))
    live = _canonical(census)
    if _canonical(lock) != live:
        print("FAIL: Kani census DRIFTED from the committed lock:", file=sys.stderr)
        lf, cf = lock.get("files", {}), live["files"]
        for f in sorted(set(lf) | set(cf)):
            if lf.get(f) != cf.get(f):
                print(f"  - {f}: lock={lf.get(f)} live={cf.get(f)}", file=sys.stderr)
        if lock.get("totals") != live["totals"]:
            print(f"  - totals: lock={lock.get('totals')}\n           live={live['totals']}", file=sys.stderr)
        print("\nA harness was added/removed/renamed, or the mutation-enrolled split changed. "
              "If intentional, run `kani_census.py --write` and update the census prose in docs/STATUS.md "
              "+ FV_SURFACE_MAP.md.", file=sys.stderr)
        return 1
    t = live["totals"]
    print(f"OK: Kani census matches the lock — {t['total_harnesses']} harnesses / {t['total_files']} files; "
          f"{t['harnesses_in_enrolled_files']} in {t['mutation_enrolled_files']} mutation-enrolled files, "
          f"{t['harnesses_outside_mutation']} in {t['files_outside_mutation']} outside; "
          f"{t['mutation_groups_total']} mutation groups {t['mutation_groups_by_tier']}. Manifest consistent.")
    return 0


def do_write() -> int:
    census = generate()
    rot = manifest_rot(census)
    if rot:
        print(f"REFUSING to write lock — manifest rot ({len(rot)}):", file=sys.stderr)
        for r in rot:
            print(f"  - {r}", file=sys.stderr)
        return 2
    LOCK.write_text(json.dumps(_canonical(census), indent=2) + "\n", encoding="utf-8")
    t = census["totals"]
    print(f"wrote {LOCK}: {t['total_harnesses']} harnesses / {t['total_files']} files "
          f"({t['harnesses_outside_mutation']} in {t['files_outside_mutation']} files outside mutation).")
    return 0


def do_list() -> int:
    census = generate()
    enrolled = {m["file"] for m in json.loads(MANIFEST.read_text(encoding="utf-8"))["mutations"]}
    print("=== Kani harness census (from git-tracked sources) ===")
    for f, c in sorted(census["files"].items()):
        mark = "" if f in enrolled else "  (no mutation coverage)"
        print(f"  {c:3d}  {f}{mark}")
    t = census["totals"]
    print(f"\n  TOTAL: {t['total_files']} files, {t['total_harnesses']} harnesses")
    print(f"  mutation-enrolled: {t['harnesses_in_enrolled_files']} harnesses in {t['mutation_enrolled_files']} files")
    print(f"  outside mutation:  {t['harnesses_outside_mutation']} harnesses in {t['files_outside_mutation']} files")
    print(f"  outside files: {census['files_outside_mutation']}")
    return 0


def main() -> int:
    args = sys.argv[1:]
    if "--write" in args or "--update" in args:
        return do_write()
    if "--list" in args:
        return do_list()
    return do_check()


if __name__ == "__main__":
    sys.exit(main())
