//! 5×8 ASCII glyph table for the FSBL OLED fingerprint renderer.
//!
//! Vendored from the same `secure/assets/font_5x8.raw` the secure-world
//! uses so the FSBL row and `measured_boot::run`'s row are visually
//! identical. ~480 bytes of rodata.
//!
//! Column-byte format: bit `r` of byte `c` = pixel at column `c`,
//! row `r` (0 = top). Matches SSD1306 page layout so a single
//! 5-column blit ORs column-bytes straight into the framebuffer.
//!
//! Generated by `fsbl/build.rs::generate_font_flat`.

// `FONT_GLYPH_H` is part of the generated table but the FSBL renderer
// only needs `FONT_GLYPH_W` + the column-byte format directly.
#[allow(dead_code)]
mod table {
    include!(concat!(env!("OUT_DIR"), "/glyphs_5x8.rs"));
}
pub use table::{FONT_FIRST_CHAR, FONT_FLAT_5X8, FONT_GLYPH_W, FONT_LAST_CHAR};

/// Look up one column-byte of an ASCII glyph. Returns 0 (blank column)
/// for non-printable input.
#[inline]
pub fn glyph_col(ch: u8, col: usize) -> u8 {
    if ch < FONT_FIRST_CHAR || ch > FONT_LAST_CHAR || col >= FONT_GLYPH_W {
        return 0;
    }
    FONT_FLAT_5X8[(ch - FONT_FIRST_CHAR) as usize][col]
}
