-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx_core]: function definitions
import Aeneas
import Extracted.U256Mul.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pqsigner_tx_core

/-- [pqsigner_tx_core::eip1559::{pqsigner_tx_core::eip1559::U256}::saturating_mul_u64]: loop body 0:
    Source: 'tx-core/src/eip1559.rs', lines 94:8-99:9
    Visibility: public -/
@[rust_loop_body]
def eip1559.U256.saturating_mul_u64_loop.body
  (rhs : Std.U64) (iter : core.ops.range.Range Std.Usize) (self : eip1559.U256)
  (out : Array Std.U8 32#usize) (carry : Std.U128) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × eip1559.U256 ×
    (Array Std.U8 32#usize) × Std.U128) ((Array Std.U8 32#usize) × Std.U128))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (out, carry))
  | some j =>
    let i ← 31#usize - j
    let i1 ← Array.index_usize self i
    let i2 ← lift (UScalar.cast .U128 i1)
    let i3 ← lift (UScalar.cast .U128 rhs)
    let i4 ← i2 * i3
    let prod ← i4 + carry
    let i5 ← lift (UScalar.cast .U8 prod)
    let a ← Array.update out i i5
    let carry1 ← prod >>> 8#i32
    ok (cont (iter1, self, a, carry1))

/-- [pqsigner_tx_core::eip1559::{pqsigner_tx_core::eip1559::U256}::saturating_mul_u64]: loop 0:
    Source: 'tx-core/src/eip1559.rs', lines 94:8-99:9
    Visibility: public -/
@[rust_loop]
def eip1559.U256.saturating_mul_u64_loop
  (iter : core.ops.range.Range Std.Usize) (self : eip1559.U256) (rhs : Std.U64)
  (out : Array Std.U8 32#usize) (carry : Std.U128) :
  Result ((Array Std.U8 32#usize) × Std.U128)
  := do
  loop
    (fun (iter1, self1, out1, carry1) =>
      eip1559.U256.saturating_mul_u64_loop.body rhs iter1 self1 out1 carry1)
    (iter, self, out, carry)

/-- [pqsigner_tx_core::eip1559::{pqsigner_tx_core::eip1559::U256}::saturating_mul_u64]:
    Source: 'tx-core/src/eip1559.rs', lines 88:4-106:5
    Visibility: public -/
def eip1559.U256.saturating_mul_u64
  (self : eip1559.U256) (rhs : Std.U64) : Result (eip1559.U256 × Bool) := do
  let out := Array.repeat 32#usize 0#u8
  let (out1, carry) ←
    eip1559.U256.saturating_mul_u64_loop
      { start := 0#usize, «end» := 32#usize } self rhs out 0#u128
  if carry != 0#u128
  then let a := Array.repeat 32#usize 255#u8
       ok (a, true)
  else ok (out1, false)

/-- [pqsigner_tx_core::eip1559::u256_saturating_mul_u64]:
    Source: 'tx-core/src/eip1559.rs', lines 332:0-334:1
    Visibility: public -/
def eip1559.u256_saturating_mul_u64
  (v : eip1559.U256) (rhs : Std.U64) : Result (eip1559.U256 × Bool) := do
  eip1559.U256.saturating_mul_u64 v rhs

end pqsigner_tx_core
