-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_tx_core]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pqsigner_tx_core

/-- [pqsigner_tx_core::eip1559::U256]
    Source: 'tx-core/src/eip1559.rs', lines 71:0-71:30
    Visibility: public -/
@[reducible]
def eip1559.U256 := Array Std.U8 32#usize

end pqsigner_tx_core
