#!/usr/bin/env python3
"""Pinned ERC-7730 semantic and PQ1-render conformance gate.

For two representative production descriptors, the lock-pinned official
``erc7730`` resolver independently expands includes/constants and derives
selectors.  This script compares its resolved intent, field format, label,
ordering, deployment identity, and simple canonical paths with dbgen's
device-decoded review artifact.  It then executes PQ1's existing upstream
fixture suite through the real Merkle verification and renderer.

This is a parity test, not catalogue provenance or signing authority.
"""

from __future__ import annotations

import hashlib
import importlib.metadata
import json
import re
import subprocess
import sys
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

from eth_hash.auto import keccak


OFFICIAL_TOOL_VERSION = "1.0.9"
ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "secure/data/erc7730-registry"
REVIEW = ROOT / "secure/data/erc7730.review.txt"
ROOTS_SOURCE = ROOT / "secure/src/db_roots.rs"
CURATION_MANIFEST = ROOT / "secure/data/erc7730/curations/manifest.json"
DESCRIPTORS = (
    "registry/lido/calldata-stETH.json",
    "registry/lido/calldata-wstETH.json",
)

GENERATED_HEADER = (
    "# ERC-7730 descriptor catalogue",
    "# Generated by `cargo run -p dbgen`. DO NOT EDIT BY HAND.",
)
ROOT_HEADER_PREFIX = "# Root: "
CURATION_HEADER_PREFIX = "# Curation manifest SHA-256: "
SKIPS_RE = re.compile(r"^## skips \((?P<count>\d+) total\)$")
PRODUCTION_ROOT_RE = re.compile(
    r'#\[cfg\(not\(feature = "e2e-test"\)\)\]\s*'
    r"pub static ERC7730_DESCRIPTORS_ROOT: \[u8; 32\] = \["
    r"(?P<body>.*?)\];",
    re.DOTALL,
)
PRODUCTION_COUNT_RE = re.compile(
    r'#\[cfg\(not\(feature = "e2e-test"\)\)\]\s*'
    r"pub const ERC7730_DESCRIPTOR_COUNT: usize = (?P<count>\d+);"
)

ENTRY_RE = re.compile(
    r"^\[(?P<index>\d{4})\] ctx=(?P<context>\S+) chain_id=(?P<chain>\d+) "
    r"contract=(?P<address>0x[0-9a-f]{40}) "
    r"primary_type=0x[0-9a-f]{64} descriptor_hash=0x[0-9a-f]{64} "
    r"erc8176_hash=0x[0-9a-f]{64} ir_len=\d+ fields=(?P<fields>\d+) "
    r"degraded=(?P<degraded>\d+) source=(?P<source>\S+)$"
)
FORMAT_RE = re.compile(
    r'^\s+· format \[(?P<selector>0x[0-9a-f]{8})\] '
    r'intent="(?P<intent>(?:[^"\\]|\\.)*)" intent_raw=0x[0-9a-f]* '
    r"static_head_words=\d+ nested_descent_count=\d+ string_preimage_count=\d+$"
)
FIELD_RE = re.compile(
    r'^\s+·\s+field\[(?P<index>\d+)\] op=(?P<op>\S+)\s+'
    r'label="(?P<label>(?:[^"\\]|\\.)*)" path=(?P<path>0x[0-9a-f]*) '
    r"params_tlv=0x[0-9a-f]* params=\{(?P<params>.*)\}$"
)

ADDRESS_TYPE_BITS = {
    "wallet": 0x01,
    "eoa": 0x02,
    "contract": 0x04,
    "nft_collection": 0x08,
    "nftCollection": 0x08,
    "token": 0x10,
    "collection": 0x20,
}
ADDRESS_SOURCE_BITS = {
    "local": 0x01,
    "ens": 0x02,
    "etherscan": 0x04,
    "registry": 0x08,
}
DATE_ENCODINGS = {"timestamp": 0, "blockheight": 1}
VISIBILITIES = {"always", "never", "optional", "ifNotIn", "mustMatch"}
TERMINAL_KIND_CODES = {
    "unsigned": 0x01,
    "signed": 0x02,
    "address": 0x03,
    "bool": 0x04,
    "fixedBytes": 0x05,
    "dynamicString": 0x06,
    "dynamicBytes": 0x07,
    "constantText": 0x08,
    "nestedStruct": 0x09,
    "eip712StringHashWord": 0x0A,
}
APPROVE_SELECTOR = "0x095ea7b3"
INTERPOLATED_INTENT_VERSION = 1
MAX_INTERPOLATED_INTENT_LEN = 32


@dataclass(frozen=True)
class InterpolatedIntent:
    version: int
    literals: tuple[str, ...]
    ordinals: tuple[int, ...]


@dataclass(frozen=True)
class FieldParameters:
    token: str | None = None
    threshold: str | None = None
    message: str | None = None
    address_types: int | None = None
    address_sources: int | None = None
    date_encoding: int | None = None
    interpolated_intent: InterpolatedIntent | None = None
    visibility: str | None = None
    terminal_kind: str | None = None
    integer_width_bytes: int | None = None


@dataclass(frozen=True)
class ReviewField:
    op: str
    label: str
    path: str
    params: FieldParameters


@dataclass(frozen=True)
class AbiParameter:
    index: int
    abi_type: str


@dataclass
class ReviewFormat:
    intent: str
    fields: list[ReviewField]


@dataclass
class ReviewEntry:
    index: int
    context: str
    chain_id: int
    address: str
    declared_fields: int
    degraded: int
    source: str
    formats: dict[str, ReviewFormat]


def installed_tool_version() -> str:
    try:
        return importlib.metadata.version("erc7730")
    except importlib.metadata.PackageNotFoundError as error:
        raise RuntimeError(
            "lock-pinned erc7730 environment is missing; run via "
            "`make erc7730-cross-parity`"
        ) from error


def _unescape_review_string(value: str) -> str:
    return json.loads(f'"{value}"')


def _split_top_level(value: str) -> list[str]:
    """Split a canonical review value on commas outside strings/containers."""

    if not value:
        return []
    parts: list[str] = []
    start = 0
    stack: list[str] = []
    quoted = False
    escaped = False
    pairs = {")": "(", "]": "[", "}": "{"}
    for index, character in enumerate(value):
        if quoted:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                quoted = False
            continue
        if character == '"':
            quoted = True
        elif character in "([{":
            stack.append(character)
        elif character in pairs:
            if not stack or stack.pop() != pairs[character]:
                raise ValueError("review parameter has mismatched containers")
        elif character == "," and not stack:
            part = value[start:index]
            if not part:
                raise ValueError("review parameter list contains an empty item")
            parts.append(part)
            start = index + 1
    if quoted or escaped:
        raise ValueError("review parameter contains an unterminated string")
    if stack:
        raise ValueError("review parameter contains an unterminated container")
    part = value[start:]
    if not part:
        raise ValueError("review parameter list contains an empty item")
    parts.append(part)
    return parts


def _parse_review_param_map(value: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for item in _split_top_level(value):
        key, separator, raw = item.partition("=")
        if (
            not separator
            or not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", key)
            or not raw
        ):
            raise ValueError(f"malformed review parameter item: {item!r}")
        if key in result:
            raise ValueError(f"duplicate review parameter: {key}")
        result[key] = raw
    return result


def _parse_review_string_value(value: str, label: str) -> str:
    if len(value) < 2 or value[0] != '"' or value[-1] != '"':
        raise ValueError(f"review {label} is not a quoted string")
    try:
        decoded = json.loads(value)
    except json.JSONDecodeError as error:
        raise ValueError(f"review {label} is not a canonical string") from error
    if not isinstance(decoded, str):
        raise ValueError(f"review {label} is not a string")
    return decoded


def _parse_review_list(value: str, label: str) -> list[str]:
    if len(value) < 2 or value[0] != "[" or value[-1] != "]":
        raise ValueError(f"review {label} is not a list")
    return _split_top_level(value[1:-1])


def _parse_review_interpolation(value: str) -> InterpolatedIntent:
    if len(value) < 2 or value[0] != "{" or value[-1] != "}":
        raise ValueError("review interpolatedIntent is not an object")
    members = _parse_review_param_map(value[1:-1])
    if set(members) != {"version", "count", "literals", "ordinals"}:
        raise ValueError("review interpolatedIntent has missing or unknown members")
    if not re.fullmatch(r"\d+", members["version"]):
        raise ValueError("review interpolatedIntent version is not an integer")
    version = int(members["version"])
    if version != INTERPOLATED_INTENT_VERSION:
        raise ValueError(f"review interpolatedIntent version {version} is unsupported")
    if not re.fullmatch(r"\d+", members["count"]):
        raise ValueError("review interpolatedIntent count is not an integer")
    count = int(members["count"])
    literal_items = _parse_review_list(members["literals"], "interpolation literals")
    literals = tuple(
        _parse_review_string_value(item, "interpolation literal") for item in literal_items
    )
    ordinal_items = _parse_review_list(members["ordinals"], "interpolation ordinals")
    if any(not re.fullmatch(r"\d+", item) for item in ordinal_items):
        raise ValueError("review interpolation ordinal is not an integer")
    ordinals = tuple(int(item) for item in ordinal_items)
    if (
        count == 0
        or len(ordinals) != count
        or len(literals) != count + 1
        or len(set(ordinals)) != count
        or any(ordinal > 0xFF for ordinal in ordinals)
    ):
        raise ValueError("review interpolatedIntent count/ordinal shape is invalid")
    return InterpolatedIntent(version=version, literals=literals, ordinals=ordinals)


def _optional_review_hex(
    params: dict[str, str], key: str, byte_length: int
) -> str | None:
    value = params.get(key)
    if value is None:
        return None
    if not re.fullmatch(rf"0x[0-9a-f]{{{byte_length * 2}}}", value):
        raise ValueError(f"review {key} is not canonical {byte_length}-byte hex")
    return value


def _optional_review_byte(params: dict[str, str], key: str) -> int | None:
    value = params.get(key)
    if value is None:
        return None
    if not re.fullmatch(r"0x[0-9a-f]{2}", value):
        raise ValueError(f"review {key} is not canonical byte hex")
    return int(value, 16)


def parse_review_field_parameters(value: str) -> FieldParameters:
    """Decode every official field parameter projected by this parity lane."""

    params = _parse_review_param_map(value)
    message = params.get("message")
    date_encoding = params.get("dateEncoding")
    if date_encoding is not None and not re.fullmatch(r"\d+", date_encoding):
        raise ValueError("review dateEncoding is not an integer")
    interpolation = params.get("interpolatedIntent")
    visibility = params.get("visibility")
    if visibility not in VISIBILITIES:
        raise ValueError(f"review visibility is missing or unsupported: {visibility!r}")
    terminal = params.get("terminalKind")
    terminal_match = (
        re.fullmatch(r"([A-Za-z][A-Za-z0-9]*)\(0x([0-9a-f]{2})\)", terminal)
        if terminal is not None
        else None
    )
    if terminal_match is None:
        raise ValueError("review terminalKind is missing or malformed")
    terminal_kind = terminal_match.group(1)
    terminal_code = TERMINAL_KIND_CODES.get(terminal_kind)
    if terminal_code is None or terminal_code != int(terminal_match.group(2), 16):
        raise ValueError("review terminalKind name/code pair is inconsistent")
    width = params.get("integerWidthBytes")
    if width is not None and (
        re.fullmatch(r"\d+", width) is None or not 1 <= int(width) <= 32
    ):
        raise ValueError("review integerWidthBytes is malformed or out of range")
    return FieldParameters(
        token=_optional_review_hex(params, "token", 20),
        threshold=_optional_review_hex(params, "threshold", 32),
        message=(
            _parse_review_string_value(message, "message")
            if message is not None
            else None
        ),
        address_types=_optional_review_byte(params, "addressTypes"),
        address_sources=_optional_review_byte(params, "addressSources"),
        date_encoding=int(date_encoding) if date_encoding is not None else None,
        interpolated_intent=(
            _parse_review_interpolation(interpolation)
            if interpolation is not None
            else None
        ),
        visibility=visibility,
        terminal_kind=terminal_kind,
        integer_width_bytes=int(width) if width is not None else None,
    )


def parse_production_descriptor_receipt(text: str) -> tuple[str, int]:
    """Read the production, never-E2E ERC-7730 root and leaf count."""

    root_matches = list(PRODUCTION_ROOT_RE.finditer(text))
    count_matches = list(PRODUCTION_COUNT_RE.finditer(text))
    if len(root_matches) != 1:
        raise ValueError(
            "db_roots.rs must contain exactly one cfg(not(feature=\"e2e-test\")) "
            "ERC7730_DESCRIPTORS_ROOT"
        )
    if len(count_matches) != 1:
        raise ValueError(
            "db_roots.rs must contain exactly one cfg(not(feature=\"e2e-test\")) "
            "ERC7730_DESCRIPTOR_COUNT"
        )

    root_body = root_matches[0]["body"]
    byte_tokens = re.findall(r"0x[0-9a-fA-F]{2}", root_body)
    residual = re.sub(r"0x[0-9a-fA-F]{2}|[\s,]", "", root_body)
    if residual or len(byte_tokens) != 32:
        raise ValueError("production ERC7730_DESCRIPTORS_ROOT is not exactly 32 bytes")
    root = "0x" + bytes(int(token, 16) for token in byte_tokens).hex()
    count = int(count_matches[0]["count"])
    if count <= 0 or count > 10_000:
        raise ValueError(f"production ERC7730_DESCRIPTOR_COUNT is out of range: {count}")
    return root, count


def _require_bound_header(lines: list[str], prefix: str, expected: str) -> int:
    matches = [(index, line) for index, line in enumerate(lines) if line.startswith(prefix)]
    if len(matches) != 1:
        raise ValueError(f"review must contain exactly one {prefix.rstrip()} header")
    index, line = matches[0]
    if line != prefix + expected:
        raise ValueError(f"review {prefix.rstrip()} header does not match bound input")
    return index


def parse_review(
    text: str,
    *,
    expected_root: str,
    expected_count: int,
    expected_curation_sha256: str,
) -> list[ReviewEntry]:
    if not re.fullmatch(r"0x[0-9a-f]{64}", expected_root):
        raise ValueError("expected production root is not canonical lowercase hex")
    if expected_count <= 0 or expected_count > 10_000:
        raise ValueError("expected production descriptor count is out of range")
    if not re.fullmatch(r"[0-9a-f]{64}", expected_curation_sha256):
        raise ValueError("expected curation-manifest SHA-256 is not canonical lowercase hex")

    lines = text.splitlines()
    if tuple(lines[: len(GENERATED_HEADER)]) != GENERATED_HEADER:
        raise ValueError("review generated header is missing or changed")
    root_header_index = _require_bound_header(lines, ROOT_HEADER_PREFIX, expected_root)
    curation_header_index = _require_bound_header(
        lines, CURATION_HEADER_PREFIX, expected_curation_sha256
    )

    skip_like = [(index, line) for index, line in enumerate(lines) if line.startswith("## skips")]
    if len(skip_like) != 1 or SKIPS_RE.fullmatch(skip_like[0][1]) is None:
        raise ValueError("review must contain exactly one canonical ## skips (<count> total) marker")
    skips_index = skip_like[0][0]

    entries: list[ReviewEntry] = []
    current: ReviewEntry | None = None
    current_format: ReviewFormat | None = None
    expected_field_index = 0

    for line_number, line in enumerate(lines[:skips_index], start=1):
        entry_match = ENTRY_RE.match(line)
        if entry_match:
            index = int(entry_match["index"])
            if index != len(entries):
                raise ValueError(
                    f"review line {line_number}: entry index {index:04d}, "
                    f"expected {len(entries):04d}"
                )
            current = ReviewEntry(
                index=index,
                context=entry_match["context"],
                chain_id=int(entry_match["chain"]),
                address=entry_match["address"],
                declared_fields=int(entry_match["fields"]),
                degraded=int(entry_match["degraded"]),
                source=entry_match["source"],
                formats={},
            )
            entries.append(current)
            current_format = None
            continue

        format_match = FORMAT_RE.match(line)
        if format_match:
            if current is None:
                raise ValueError(f"review line {line_number}: format without entry")
            selector = format_match["selector"]
            if selector in current.formats:
                raise ValueError(f"review line {line_number}: duplicate selector {selector}")
            current_format = ReviewFormat(
                intent=_unescape_review_string(format_match["intent"]), fields=[]
            )
            current.formats[selector] = current_format
            expected_field_index = 0
            continue

        field_match = FIELD_RE.match(line)
        if field_match:
            if current_format is None:
                raise ValueError(f"review line {line_number}: field without format")
            index = int(field_match["index"])
            if index != expected_field_index:
                raise ValueError(
                    f"review line {line_number}: field order {index}, expected {expected_field_index}"
                )
            current_format.fields.append(
                ReviewField(
                    op=field_match["op"],
                    label=_unescape_review_string(field_match["label"]),
                    path=field_match["path"],
                    params=parse_review_field_parameters(field_match["params"]),
                )
            )
            expected_field_index += 1
            continue

        if current is None:
            if (
                line.startswith("[")
                or "· format" in line
                or ("·" in line and "field[" in line)
            ):
                raise ValueError(f"review line {line_number}: malformed entry body line")
            continue
        if line:
            raise ValueError(f"review line {line_number}: unrecognized entry body line")

    if len(entries) != expected_count:
        raise ValueError(
            f"review contains {len(entries)} entries, expected production count {expected_count}"
        )
    if not entries or skips_index <= root_header_index or skips_index <= curation_header_index:
        raise ValueError("review binding headers and terminal skips marker are out of order")
    for line_number, line in enumerate(lines[skips_index + 1 :], start=skips_index + 2):
        if (
            line.startswith("[")
            or "· format" in line
            or ("·" in line and "field[" in line)
        ):
            raise ValueError(
                f"review line {line_number}: entry body appears after terminal skips marker"
            )

    for entry in entries:
        actual_fields = sum(len(fmt.fields) for fmt in entry.formats.values())
        if actual_fields != entry.declared_fields:
            raise ValueError(
                f"{entry.source}@{entry.address}: header says {entry.declared_fields} fields, "
                f"parsed {actual_fields}"
            )
    return entries


def run_exact_descriptor_roundtrip() -> None:
    """Rebuild and byte-compare every coupled ERC-7730 catalogue artifact."""

    subprocess.run(
        [
            "cargo",
            "run",
            "--locked",
            "-q",
            "-p",
            "pqsigner-xtask",
            "--features",
            "nested-calldata-test-fixture",
            "--",
            "gen-erc7730-descriptors",
            "--check",
        ],
        cwd=ROOT,
        check=True,
    )


def validate_generated_review(
    receipt_bytes: bytes,
    *,
    expected_root: str,
    expected_count: int,
    expected_curation_sha256: str,
) -> list[ReviewEntry]:
    """Strictly parse the receipt, then bind all its bytes to fresh codegen."""

    try:
        text = receipt_bytes.decode("utf-8")
    except UnicodeDecodeError as error:
        raise ValueError(f"ERC-7730 review receipt is not UTF-8: {error}") from error
    entries = parse_review(
        text,
        expected_root=expected_root,
        expected_count=expected_count,
        expected_curation_sha256=expected_curation_sha256,
    )
    # The parser protects the fields consumed below. The generator check is
    # additionally load-bearing: it compares the entire review receipt and
    # every coupled generated artifact, including entries outside the two
    # representative descriptors examined by the official resolver.
    run_exact_descriptor_roundtrip()
    if REVIEW.read_bytes() != receipt_bytes:
        raise ValueError(
            "ERC-7730 review receipt changed or differs during exact generator round-trip"
        )
    return entries


def _split_simple_parameters(parameters: str) -> list[tuple[str, str]]:
    if not parameters.strip():
        return []
    result: list[tuple[str, str]] = []
    for parameter in parameters.split(","):
        words = parameter.strip().split()
        if len(words) != 2 or any(character in words[0] for character in "()"):
            raise ValueError(f"parity fixture uses a non-simple ABI parameter: {parameter!r}")
        result.append((words[0], words[1]))
    return result


def signature_metadata(
    descriptor: dict[str, Any],
) -> dict[str, dict[str, AbiParameter]]:
    formats = descriptor.get("display", {}).get("formats")
    if not isinstance(formats, dict):
        raise ValueError("descriptor display.formats is not an object")
    result: dict[str, dict[str, AbiParameter]] = {}
    for signature in formats:
        match = re.fullmatch(r"([A-Za-z_][A-Za-z0-9_]*)\((.*)\)", signature)
        if match is None:
            raise ValueError(f"non-signature format key in parity fixture: {signature!r}")
        parameters = _split_simple_parameters(match.group(2))
        canonical = f"{match.group(1)}({','.join(kind for kind, _ in parameters)})"
        selector = "0x" + keccak(canonical.encode())[:4].hex()
        if selector in result:
            raise ValueError(f"selector collision in parity fixture: {selector}")
        result[selector] = {
            name: AbiParameter(index=index, abi_type=kind)
            for index, (kind, name) in enumerate(parameters)
        }
    return result


def expected_simple_path(path: str, parameters: dict[str, AbiParameter]) -> str:
    if path.startswith("#.") and path.count(".") == 1:
        name = path[2:]
        if name not in parameters:
            raise ValueError(f"unknown ABI parameter in path {path!r}")
        return "0x1020" + parameters[name].index.to_bytes(2, "big").hex()
    if path.startswith("@.") and path.count(".") == 1:
        name = path[2:]
        return "0x1120" + keccak(name.encode())[:2].hex()
    raise ValueError(f"parity fixture path is not simple and cannot be compared: {path!r}")


def _official_param_object(field: dict[str, Any], label: str) -> dict[str, Any]:
    value = field.get("params")
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise ValueError(f"{label}: params is not an object")
    return value


def _official_address_bitset(
    value: Any, label: str, mapping: dict[str, int]
) -> int:
    if not isinstance(value, list):
        raise ValueError(f"{label} is not a list")
    result = 0
    seen: set[str] = set()
    for member in value:
        if not isinstance(member, str) or member not in mapping:
            raise ValueError(f"{label} contains an unsupported member: {member!r}")
        if member in seen:
            raise ValueError(f"{label} contains duplicate member {member!r}")
        seen.add(member)
        result |= mapping[member]
    return result


def _official_token_constant(value: Any, label: str) -> str:
    if not isinstance(value, dict) or set(value) != {
        "type",
        "type_family",
        "type_size",
        "value",
        "raw",
    }:
        raise ValueError(f"{label}: resolved token is not the canonical constant object")
    raw = value["raw"]
    display = value["value"]
    if (
        value["type"] != "constant"
        or value["type_family"] != "address"
        or type(value["type_size"]) is not int
        or value["type_size"] != 20
        or not isinstance(raw, str)
        or not re.fullmatch(r"0x[0-9a-f]{40}", raw)
        or not isinstance(display, str)
        or display.lower() != raw
    ):
        raise ValueError(f"{label}: resolved token constant is malformed or inconsistent")
    return raw


def _official_terminal_semantics(
    field: dict[str, Any], parameters: dict[str, AbiParameter], label: str
) -> tuple[str, int | None]:
    path = field.get("path")
    if path == "@.value":
        return "unsigned", 32
    if not isinstance(path, str) or not path.startswith("#.") or path.count(".") != 1:
        raise ValueError(f"{label}: terminal ABI type cannot be derived from path {path!r}")
    parameter = parameters.get(path[2:])
    if parameter is None:
        raise ValueError(f"{label}: path does not name an ABI parameter")
    abi_type = parameter.abi_type
    if abi_type == "address":
        return "address", None
    integer = re.fullmatch(r"uint(\d*)", abi_type)
    if integer is not None:
        bits = int(integer.group(1) or "256")
        if not 8 <= bits <= 256 or bits % 8 != 0:
            raise ValueError(f"{label}: invalid unsigned integer ABI width {bits}")
        return "unsigned", bits // 8
    fixed_bytes = re.fullmatch(r"bytes(\d+)", abi_type)
    if fixed_bytes is not None and 1 <= int(fixed_bytes.group(1)) <= 32:
        return "fixedBytes", None
    raise ValueError(f"{label}: unsupported selected-fixture ABI type {abi_type!r}")


def official_field_parameters(
    field: dict[str, Any], parameters: dict[str, AbiParameter], label: str
) -> FieldParameters:
    """Project all official field semantics encoded by PQ1 for these fixtures."""

    op = str(field.get("format", "raw"))
    params = _official_param_object(field, label)
    allowed = {
        "tokenAmount": {"token", "threshold", "message"},
        "addressName": {"types", "sources"},
        "date": {"encoding"},
    }.get(op, set())
    unknown = set(params) - allowed
    if unknown:
        raise ValueError(f"{label}: unsupported official params: {sorted(unknown)}")

    token = None
    threshold = None
    message = None
    address_types = None
    address_sources = None
    date_encoding = None
    visibility = field.get("visible", "always")
    if not isinstance(visibility, str) or visibility not in VISIBILITIES:
        raise ValueError(f"{label}: unsupported visibility {visibility!r}")
    terminal_kind, integer_width_bytes = _official_terminal_semantics(
        field, parameters, label
    )
    if op == "tokenAmount":
        if "token" in params:
            token = _official_token_constant(params["token"], label)
        if "threshold" in params:
            threshold_value = params["threshold"]
            if not isinstance(threshold_value, str) or not re.fullmatch(
                r"0x[0-9a-f]{64}", threshold_value
            ):
                raise ValueError(f"{label}: threshold is not canonical uint256 hex")
            threshold = threshold_value
        if "message" in params:
            message_value = params["message"]
            if (
                not isinstance(message_value, str)
                or not message_value
                or len(message_value.encode("ascii", errors="ignore")) != len(message_value)
                or not all(0x20 <= ord(character) < 0x7F for character in message_value)
                or len(message_value) > 254
            ):
                raise ValueError(f"{label}: message is not canonical bounded ASCII")
            message = message_value
    elif op == "addressName":
        if "types" in params:
            address_types = _official_address_bitset(
                params["types"], f"{label}.types", ADDRESS_TYPE_BITS
            )
        if "sources" in params:
            address_sources = _official_address_bitset(
                params["sources"], f"{label}.sources", ADDRESS_SOURCE_BITS
            )
    elif op == "date" and "encoding" in params:
        encoding = params["encoding"]
        if not isinstance(encoding, str) or encoding not in DATE_ENCODINGS:
            raise ValueError(f"{label}: unsupported date encoding {encoding!r}")
        date_encoding = DATE_ENCODINGS[encoding]

    return FieldParameters(
        token=token,
        threshold=threshold,
        message=message,
        address_types=address_types,
        address_sources=address_sources,
        date_encoding=date_encoding,
        visibility=visibility,
        terminal_kind=terminal_kind,
        integer_width_bytes=integer_width_bytes,
    )


def _parse_official_interpolation(value: str, label: str) -> tuple[list[str], list[str]]:
    literals: list[str] = []
    placeholders: list[str] = []
    literal_start = 0
    cursor = 0
    while cursor < len(value):
        if value[cursor] == "}":
            raise ValueError(f"{label}: interpolatedIntent has unmatched closing brace")
        if value[cursor] != "{":
            cursor += 1
            continue
        literals.append(value[literal_start:cursor])
        close = value.find("}", cursor + 1)
        if close < 0:
            raise ValueError(f"{label}: interpolatedIntent has unmatched opening brace")
        placeholder = value[cursor + 1 : close]
        if (
            not placeholder
            or placeholder != placeholder.strip()
            or "{" in placeholder
            or "}" in placeholder
        ):
            raise ValueError(f"{label}: interpolatedIntent placeholder is malformed")
        placeholders.append(placeholder)
        cursor = close + 1
        literal_start = cursor
    literals.append(value[literal_start:])
    return literals, placeholders


def _interpolation_paths_match(path: str, placeholder: str) -> bool:
    return (
        path == placeholder
        or path.removeprefix("#.") == placeholder
        or placeholder.removeprefix("#.") == path
    )


def expected_interpolated_intent(
    official_format: dict[str, Any],
    selector: str,
    parameters: dict[str, AbiParameter],
    projected_fields: list[FieldParameters],
    label: str,
) -> InterpolatedIntent | None:
    """Derive PQ1 v1 enrollment or the required static-intent fallback."""

    value = official_format.get("interpolatedIntent")
    if value is None or selector == APPROVE_SELECTOR:
        return None
    if not isinstance(value, str):
        raise ValueError(f"{label}: interpolatedIntent is not a string")
    if (
        not value
        or len(value) > 254
        or value != value.strip()
        or not all(0x20 <= ord(character) < 0x7F for character in value)
    ):
        raise ValueError(f"{label}: interpolatedIntent is not canonical bounded ASCII")
    fields = official_format.get("fields")
    if not isinstance(fields, list) or len(fields) != len(projected_fields):
        raise ValueError(f"{label}: fields are unavailable for interpolation")
    literals, placeholders = _parse_official_interpolation(value, label)
    ordinals: list[int] = []
    for placeholder in placeholders:
        matches = [
            (index, field)
            for index, field in enumerate(fields)
            if isinstance(field, dict)
            and isinstance(field.get("path"), str)
            and _interpolation_paths_match(field["path"], placeholder)
        ]
        if not matches:
            return None
        if len(matches) != 1:
            raise ValueError(f"{label}: interpolatedIntent placeholder is ambiguous")
        ordinal, field = matches[0]
        if ordinal in ordinals:
            raise ValueError(f"{label}: interpolatedIntent repeats a field")
        if field.get("visible", "always") != "always":
            raise ValueError(f"{label}: interpolatedIntent field is not always visible")
        op = str(field.get("format", "raw"))
        if op not in {"amount", "tokenAmount"}:
            return None
        projected = projected_fields[ordinal]
        if projected.threshold is not None or projected.message is not None:
            return None
        if op == "tokenAmount" and projected.token is None:
            return None
        path = str(field["path"])
        if path.startswith(("@", "$")):
            return None
        if not path.startswith("#.") or path.count(".") != 1:
            return None
        parameter = parameters.get(path[2:])
        if parameter is None or re.fullmatch(r"uint(?:\d+)?", parameter.abi_type) is None:
            return None
        ordinals.append(ordinal)

    if len(ordinals) != 1 or literals[-1] != "":
        return None
    if sum(len(literal) for literal in literals) + len(ordinals) > MAX_INTERPOLATED_INTENT_LEN:
        return None
    return InterpolatedIntent(
        version=INTERPOLATED_INTENT_VERSION,
        literals=tuple(literals),
        ordinals=tuple(ordinals),
    )


def resolve_official(path: Path) -> dict[str, Any]:
    result = subprocess.run(
        ["erc7730", "resolve", "--v2", str(path)],
        cwd=ROOT,
        check=False,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "no diagnostic output"
        raise RuntimeError(f"official resolver failed for {path}: {detail}")
    try:
        resolved = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise ValueError(f"official resolver emitted invalid JSON for {path}") from error
    if not isinstance(resolved, dict):
        raise ValueError(f"official resolver emitted non-object JSON for {path}")
    return resolved


def compare_resolved_descriptor(
    relative: str,
    source: dict[str, Any],
    resolved: dict[str, Any],
    entries: list[ReviewEntry],
) -> tuple[int, int]:
    signatures = signature_metadata(source)

    context = resolved.get("context", {}).get("contract")
    if not isinstance(context, dict):
        raise ValueError(f"{relative}: expected contract context")
    deployments = context.get("deployments")
    if not isinstance(deployments, list) or not deployments:
        raise ValueError(f"{relative}: official resolver returned no deployments")
    resolved_formats = resolved.get("display", {}).get("formats")
    if not isinstance(resolved_formats, dict) or not resolved_formats:
        raise ValueError(f"{relative}: official resolver returned no formats")
    if set(resolved_formats) != set(signatures):
        raise ValueError(f"{relative}: official selector derivation differs from local Keccak derivation")

    basename = Path(relative).name
    candidates = [entry for entry in entries if entry.source == basename]
    expected_deployments = {
        (int(item["chainId"]), str(item["address"]).lower()) for item in deployments
    }
    actual_deployments = {(entry.chain_id, entry.address) for entry in candidates}
    if actual_deployments != expected_deployments:
        raise ValueError(
            f"{relative}: deployment mismatch: review={sorted(actual_deployments)} "
            f"official={sorted(expected_deployments)}"
        )

    checked_fields = 0
    for entry in candidates:
        if entry.context != "contract" or entry.degraded != 0:
            raise ValueError(f"{relative}@{entry.address}: wrong context or degraded fields")
        if set(entry.formats) != set(resolved_formats):
            raise ValueError(f"{relative}@{entry.address}: selector set mismatch")
        for selector, official_format in resolved_formats.items():
            if not isinstance(official_format, dict):
                raise ValueError(f"{relative}:{selector}: resolved format is not an object")
            review_format = entry.formats[selector]
            official_intent = official_format.get("intent")
            if not isinstance(official_intent, str) or review_format.intent != official_intent:
                raise ValueError(f"{relative}:{selector}: intent mismatch")
            official_fields = official_format.get("fields")
            if not isinstance(official_fields, list):
                raise ValueError(f"{relative}:{selector}: fields is not a list")
            if len(review_format.fields) != len(official_fields):
                raise ValueError(f"{relative}:{selector}: field count mismatch")
            projected_fields: list[FieldParameters] = []
            for field_index, official_field in enumerate(official_fields):
                if not isinstance(official_field, dict):
                    raise ValueError(f"{relative}:{selector}: field is not an object")
                projected_fields.append(
                    official_field_parameters(
                        official_field,
                        signatures[selector],
                        f"{relative}:{selector}:field[{field_index}]",
                    )
                )
            interpolation = expected_interpolated_intent(
                official_format,
                selector,
                signatures[selector],
                projected_fields,
                f"{relative}:{selector}",
            )
            for field_index, (review_field, official_field, official_params) in enumerate(
                zip(
                    review_format.fields,
                    official_fields,
                    projected_fields,
                    strict=True,
                )
            ):
                if field_index == 0:
                    official_params = replace(
                        official_params, interpolated_intent=interpolation
                    )
                expected = ReviewField(
                    op=str(official_field.get("format", "raw")),
                    label=str(official_field.get("label", "")),
                    path=expected_simple_path(
                        str(official_field.get("path", "")), signatures[selector]
                    ),
                    params=official_params,
                )
                if review_field != expected:
                    raise ValueError(
                        f"{relative}:{selector}: field mismatch: "
                        f"review={review_field!r} official={expected!r}"
                    )
                checked_fields += 1
    return len(resolved_formats), checked_fields


def compare_descriptor(relative: str, entries: list[ReviewEntry]) -> tuple[int, int]:
    path = REGISTRY / relative
    source = json.loads(path.read_text(encoding="utf-8"))
    resolved = resolve_official(path)
    return compare_resolved_descriptor(relative, source, resolved, entries)


def run_pq1_renderer_conformance() -> None:
    subprocess.run(
        [
            "cargo",
            "test",
            "--locked",
            "--quiet",
            "-p",
            "dbgen",
            "--test",
            "erc7730_upstream_conformance",
        ],
        cwd=ROOT,
        check=True,
    )


def main() -> int:
    if installed_tool_version() != OFFICIAL_TOOL_VERSION:
        raise RuntimeError(
            f"erc7730 package must be exactly {OFFICIAL_TOOL_VERSION}; "
            "run via `make erc7730-cross-parity`"
        )
    expected_root, expected_count = parse_production_descriptor_receipt(
        ROOTS_SOURCE.read_text(encoding="utf-8")
    )
    expected_curation_sha256 = hashlib.sha256(CURATION_MANIFEST.read_bytes()).hexdigest()
    entries = validate_generated_review(
        REVIEW.read_bytes(),
        expected_root=expected_root,
        expected_count=expected_count,
        expected_curation_sha256=expected_curation_sha256,
    )
    formats = 0
    fields = 0
    for descriptor in DESCRIPTORS:
        descriptor_formats, descriptor_fields = compare_descriptor(descriptor, entries)
        formats += descriptor_formats
        fields += descriptor_fields
    run_pq1_renderer_conformance()
    print(
        "ERC-7730 cross parity: PASS "
        f"({len(DESCRIPTORS)} production descriptors, {formats} formats, {fields} fields; "
        "exact generator round-trip + official resolver + Merkle-verified "
        "PQ1 renderer conformance)"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, ValueError, json.JSONDecodeError, subprocess.CalledProcessError) as error:
        print(f"ERC-7730 cross parity: FAIL: {error}", file=sys.stderr)
        raise SystemExit(1)
