-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.Wots.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace sphincs_c10

/-- [sphincs_c10::params::W]
    Source: 'sphincs-c10/src/params.rs', lines 43:0-43:23
    Visibility: public -/
@[global_simps, irreducible] def params.W : Std.Usize := 8#usize

/-- [sphincs_c10::params::LOG_W]
    Source: 'sphincs-c10/src/params.rs', lines 46:0-46:27
    Visibility: public -/
@[global_simps, irreducible] def params.LOG_W : Std.Usize := 3#usize

/-- [sphincs_c10::params::L]
    Source: 'sphincs-c10/src/params.rs', lines 49:0-49:24
    Visibility: public -/
@[global_simps, irreducible] def params.L : Std.Usize := 43#usize

/-- [sphincs_c10::params::W_MASK]
    Source: 'sphincs-c10/src/params.rs', lines 55:0-55:37
    Visibility: public -/
@[global_simps, irreducible]
def params.W_MASK : Result Std.U8 := do
  let i ← params.W - 1#usize
  ok (UScalar.cast .U8 i)

/-- [sphincs_c10::wots::extract_digits]: loop body 0:
    Source: 'sphincs-c10/src/wots.rs', lines 27:4-45:5
    Visibility: public -/
@[rust_loop_body]
def wots.extract_digits_loop.body
  (digest : Array Std.U8 32#usize) (iter : core.ops.range.Range Std.Usize)
  (digits : Array Std.U8 43#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U8
    43#usize)) (Array Std.U8 43#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done digits)
  | some i =>
    let bit_offset ← i * params.LOG_W
    let i1 ← bit_offset / 8#usize
    let byte_idx ← 31#usize - i1
    let bit_in_byte ← bit_offset % 8#usize
    let i2 ← bit_in_byte + params.LOG_W
    if i2 <= 8#usize
    then
      let i3 ← Array.index_usize digest byte_idx
      let i4 ← i3 >>> bit_in_byte
      let i5 ← params.W_MASK
      let i6 ← lift (i4 &&& i5)
      let a ← Array.update digits i i6
      ok (cont (iter1, a))
    else
      let i3 ← Array.index_usize digest byte_idx
      let lo ← i3 >>> bit_in_byte
      let hi ←
        if byte_idx > 0#usize
        then
          do
          let i4 ← byte_idx - 1#usize
          let i5 ← Array.index_usize digest i4
          let i6 ← 8#usize - bit_in_byte
          i5 <<< i6
        else ok 0#u8
      let i4 ← lift (lo ||| hi)
      let i5 ← params.W_MASK
      let i6 ← lift (i4 &&& i5)
      let a ← Array.update digits i i6
      ok (cont (iter1, a))

/-- [sphincs_c10::wots::extract_digits]: loop 0:
    Source: 'sphincs-c10/src/wots.rs', lines 27:4-45:5
    Visibility: public -/
@[rust_loop]
def wots.extract_digits_loop
  (iter : core.ops.range.Range Std.Usize) (digest : Array Std.U8 32#usize)
  (digits : Array Std.U8 43#usize) :
  Result (Array Std.U8 43#usize)
  := do
  loop
    (fun (iter1, digits1) => wots.extract_digits_loop.body digest iter1
      digits1)
    (iter, digits)

/-- [sphincs_c10::wots::extract_digits]:
    Source: 'sphincs-c10/src/wots.rs', lines 16:0-47:1
    Visibility: public -/
def wots.extract_digits
  (digest : Array Std.U8 32#usize) : Result (Array Std.U8 43#usize) := do
  let digits := Array.repeat 43#usize 0#u8
  wots.extract_digits_loop { start := 0#usize, «end» := params.L } digest
    digits

end sphincs_c10
