//! Fisher-Yates shuffle for sign-path DPA defense.
//!
//! Naive SPHINCS+ signing processes WOTS chains and FORS trees in a
//! fixed order (chain 0, chain 1, …; tree 0, tree 1, …). Profiled DPA
//! exploits this: the same secret-bearing hash always lands at the
//! same relative sample index across traces, so trace averaging
//! recovers SK bits.
//!
//! This module produces fresh per-signature permutations of `[0, 1,
//! …, n-1]` so the hash that touches WOTS chain seed *i* (or FORS
//! tree *t*) lands at an attacker-unpredictable time per signature.
//! With l=43 chains the permutation space is 43! ≈ 10^52; with k=13
//! trees it is 13! ≈ 6×10^9. The DPA averaging premise is broken at
//! both layers.
//!
//! **Correctness invariant.** The shuffle is purely COMPUTATIONAL
//! re-ordering — the produced signature bytes are byte-identical to
//! the un-shuffled path for any `(sk, msg, opt_rand)`. The shuffle
//! seed selects the *order* of computation, never the *value*.
//!
//! **Identity shuffle.** `ShuffleSeed::zero()` produces the
//! identity permutation `[0, 1, …, n-1]`. Used as a backwards-
//! compatible default and as the byte-equality regression-test
//! oracle.

use sha2::{Digest, Sha256};
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Per-signature shuffle seed. Derived per-call from the
/// `rng_strong` multi-source TRNG and fed to BOTH double-compute
/// signs unchanged (re-drawing per sign would break the F-13
/// byte-equality FI gate).
///
/// Internally, the seed is label-derived into per-purpose
/// sub-shuffles (one per WOTS layer, one for FORS).
#[derive(Clone, Zeroize, ZeroizeOnDrop)]
pub struct ShuffleSeed(pub [u8; 32]);

impl ShuffleSeed {
    /// The identity-shuffle seed — every `fisher_yates` call with
    /// this returns `[0, 1, …, n-1]`. Used as the default for the
    /// backwards-compatible `sign_with_progress` API and as the
    /// regression-test oracle (`sign_with_shuffle(seed_zero) ==
    /// sign_with_progress`).
    pub const fn zero() -> Self {
        Self([0u8; 32])
    }

    /// Derive a per-purpose sub-seed from a base seed and a label.
    /// Used internally to split one `ShuffleSeed` into independent
    /// WOTS-layer-0, WOTS-layer-1, and FORS shuffles.
    pub fn derive(&self, label: &[u8]) -> [u8; 32] {
        if self.0 == [0u8; 32] {
            // Preserve identity: any sub-derivation of the zero seed
            // is also zero, so all downstream Fisher-Yates calls
            // produce the identity permutation.
            return [0u8; 32];
        }
        let mut h = Sha256::new();
        h.update(b"sphincs-c10-shuffle-v1");
        h.update(&self.0);
        h.update(label);
        let d = h.finalize();
        let mut out = [0u8; 32];
        out.copy_from_slice(&d);
        out
    }
}

/// Fisher-Yates shuffle of `[0, 1, …, n-1]`, returned in the first
/// `n` entries of an owned 64-byte buffer (tail entries are 0).
///
/// Randomness is generated by hashing `(label || seed || counter_be4)`
/// for each fresh 32-byte block; bytes are consumed in pairs as
/// `u16` values and reduced `mod (i+1)` with negligible bias for
/// our usage (n ≤ 64).
///
/// If `seed == [0; 32]` the function returns the identity
/// permutation without touching the RNG, preserving the
/// byte-equality oracle.
///
/// `n` must be ≤ 64 (covers our l=43 and k=13). Returns an owned
/// array (not an `&mut [u8]` out-param): a mutable-slice parameter
/// borrowed inside the shuffle loop is a nested-borrow shape the
/// Aeneas Lean extraction rejects (work-todo §33 P0), and the owned
/// form is the cleaner API anyway.
#[inline(never)]
#[must_use]
pub fn fisher_yates(seed: &[u8; 32], n: usize) -> [u8; 64] {
    debug_assert!(n <= 64);

    let mut buf = [0u8; 64];

    // Initialise identity permutation in all cases.
    let mut t = 0;
    while t < n {
        buf[t] = t as u8;
        t += 1;
    }

    // Identity-seed fast path: skip the hash entirely. `n <= 1` would
    // make the countdown start below underflow (the permutation of a
    // 0- or 1-element prefix is the identity already written above);
    // both checked BEFORE the seed is copied into the RNG state so
    // the early return leaves no unscrubbed seed copy on the stack.
    // Zero-ness is detected with a byte OR-fold, NOT `seed == &[0;32]`:
    // an array `==` poisons the borrow state for every later loop in
    // the function under the Aeneas Lean extraction (probe-bisected,
    // work-todo §33 P0).
    let mut nonzero: u8 = 0;
    let mut s = 0;
    while s < 32 {
        nonzero |= seed[s];
        s += 1;
    }
    if nonzero == 0 || n <= 1 {
        return buf;
    }

    // SHA-256 counter-mode byte stream, PRECOMPUTED into an owned
    // buffer (the original lazy per-byte refill consumed blocks
    // strictly sequentially, so eager generation is byte-identical).
    // n <= 64 needs at most 2*(n-1) = 126 stream bytes = 4 blocks.
    // Precomputing keeps the shuffle loop free of `&mut self` method
    // calls, a borrow shape the Aeneas Lean extraction rejects in
    // loops (work-todo §33 P0). Each 32-byte block is
    // `SHA-256("sphincs-c10-fisher-yates-v1" || seed || counter_be4)`,
    // bytes consumed in pairs as little-endian `u16`s.
    let mut stream = [0u8; 128];
    let mut blk: u32 = 0;
    while blk < 4 {
        let mut h = Sha256::new();
        h.update(b"sphincs-c10-fisher-yates-v1");
        h.update(*seed);
        h.update(blk.to_be_bytes());
        let mut d = [0u8; 32];
        d.copy_from_slice(&h.finalize());
        // Single-variable index `w` (not `blk * 32 + b`): compound
        // index expressions inside loops are a shape the Aeneas Lean
        // extraction rejects (work-todo §33 P0).
        let mut w = (blk as usize) * 32;
        let mut b = 0;
        while b < 32 {
            stream[w] = d[b];
            w += 1;
            b += 1;
        }
        d.zeroize();
        blk += 1;
    }

    // Classic Fisher-Yates: for i = n-1 down to 1, swap buf[i] with
    // buf[j] for random j ∈ [0, i]. A plain `while` countdown (not
    // `(1..n).rev()`) so the loop stays inside the iterator-free Rust
    // fragment the extraction supports.
    let mut pos = 0;
    let mut i = n - 1;
    while i >= 1 {
        let bound = (i + 1) as u16;
        let lo = stream[pos] as u16;
        let hi = stream[pos + 1] as u16;
        pos += 2;
        let r = (hi << 8) | lo;
        let j = (r % bound) as usize;
        let tmp = buf[i];
        buf[i] = buf[j];
        buf[j] = tmp;
        i -= 1;
    }

    // Defensive: scrub the seed-derived stream before returning.
    stream.zeroize();
    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zero_seed_returns_identity() {
        let perm = fisher_yates(&[0u8; 32], 43);
        for (i, &v) in perm[..43].iter().enumerate() {
            assert_eq!(v, i as u8);
        }
    }

    #[test]
    fn nonzero_seed_permutes_all_indices() {
        let mut seed = [0u8; 32];
        seed[0] = 0x42;
        let perm = fisher_yates(&seed, 43);
        // Every index 0..43 appears exactly once.
        let mut seen = [false; 43];
        for &v in perm[..43].iter() {
            seen[v as usize] = true;
        }
        assert!(seen.iter().all(|&b| b));
    }

    #[test]
    fn different_seeds_yield_different_orders() {
        let mut seed_a = [0u8; 32];
        seed_a[0] = 0x01;
        let mut seed_b = [0u8; 32];
        seed_b[0] = 0x02;
        let perm_a = fisher_yates(&seed_a, 43);
        let perm_b = fisher_yates(&seed_b, 43);
        assert_ne!(perm_a, perm_b);
    }

    #[test]
    fn deterministic_for_same_seed() {
        let mut seed = [0u8; 32];
        seed[5] = 0xAB;
        let perm_a = fisher_yates(&seed, 43);
        let perm_b = fisher_yates(&seed, 43);
        assert_eq!(perm_a, perm_b);
    }

    #[test]
    fn derive_zero_yields_zero() {
        let s = ShuffleSeed::zero();
        assert_eq!(s.derive(b"anything"), [0u8; 32]);
    }

    #[test]
    fn derive_nonzero_differs_per_label() {
        let s = ShuffleSeed([0x55u8; 32]);
        let a = s.derive(b"wots-0");
        let b = s.derive(b"wots-1");
        let c = s.derive(b"fors");
        assert_ne!(a, b);
        assert_ne!(a, c);
        assert_ne!(b, c);
    }
}
